<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.23">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="René Canales">

<title>Modelo de efectos aleatorios: Tesis de Magister</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="02-modelos_files/libs/clipboard/clipboard.min.js"></script>
<script src="02-modelos_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="02-modelos_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="02-modelos_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="02-modelos_files/libs/quarto-html/popper.min.js"></script>
<script src="02-modelos_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="02-modelos_files/libs/quarto-html/anchor.min.js"></script>
<link href="02-modelos_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="02-modelos_files/libs/quarto-html/quarto-syntax-highlighting-1fe81d0376b2c50856e68e651e390326.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="02-modelos_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="02-modelos_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="02-modelos_files/libs/bootstrap/bootstrap-07b601b323af04afb06bdce9dd9a3af2.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Modelo de efectos aleatorios: Tesis de Magister</h1>
                      </div>
  </div>
    
  <div class="quarto-title-meta-author">
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-heading">Affiliations</div>
    
      <div class="quarto-title-meta-contents">
      <p class="author">René Canales </p>
    </div>
    <div class="quarto-title-meta-contents">
          <p class="affiliation">
              Instituto de Sociología, Pontificia Universidad Católica de Chile
            </p>
          <p class="affiliation">
              Centro de estudios del conflicto y cohesión social (COES)
            </p>
        </div>
    </div>

  <div class="quarto-title-meta">

        
    
      
    </div>
    
  <div>
    <div class="abstract">
      <div class="block-title">Abstract</div>
      <p><strong>Keywords</strong>:</p>
    </div>
  </div>
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="..\02-modelos.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="modelos-exploratorios" class="level2" data-number="0.1">
<h2 data-number="0.1" class="anchored" data-anchor-id="modelos-exploratorios"><span class="header-section-number">0.1</span> Modelos Exploratorios</h2>
</section>
<section id="modelos-descriptivos" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Modelos Descriptivos</h1>
<section id="modelo-nulo-base-de-comparación" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="modelo-nulo-base-de-comparación"><span class="header-section-number">1.1</span> Modelo Nulo (Base de comparación)</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
=========================================
                             Model 1     
-----------------------------------------
(Intercept)                     -2.34 ***
                                (0.05)   
-----------------------------------------
AIC                          16722.07    
BIC                          16737.88    
Log Likelihood               -8359.04    
Num. obs.                    20052       
Num. groups: idencuesta       4429       
Var: idencuesta (Intercept)      2.97    
=========================================
*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># Intraclass Correlation Coefficient

    Adjusted ICC: 0.475
  Unadjusted ICC: 0.475</code></pre>
</div>
</div>
<p>Antes de estimar modelos con predictores, se ajustó un modelo nulo (solo intercepto y efectos aleatorios por individuo) para evaluar la estructura de dependencia de los datos. El modelo nulo reveló un coeficiente de correlación intraclase (ICC) de 0.475, indicando que 47.5% de la varianza en participación en protestas se debe a diferencias estables entre individuos. Este ICC sustancial justifica plenamente el uso de modelos multinivel con efectos aleatorios por individuo.</p>
<p>Lo anterior indica que aproximadamente la mitad de la varianza en participación en protesta se debe a diferencias entre individuos, mientras que la otra mitad corresponde a variación dentro de individuos a través del tiempo. Este ICC sustancial (&gt;0.1) justifica el uso de modelos de efectos aleatorios que ajusten por la correlación intra-individual y eviten la subestimación de errores estándar inherente a modelos pooled (Hox, 2010).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
============================================================
                                                Model 1     
------------------------------------------------------------
(Intercept)                                         0.60 ***
                                                   (0.04)   
educ_cat_factor_refMedia incompleta o menos        -0.04 ***
                                                   (0.01)   
educ_cat_factor_refTécnica superior incompleta      0.04 *  
                                                   (0.02)   
educ_cat_factor_refTécnica superior completa        0.04 ***
                                                   (0.01)   
educ_cat_factor_refUniversitaria incompleta         0.11 ***
                                                   (0.01)   
educ_cat_factor_refUniversitaria completa           0.08 ***
                                                   (0.01)   
educ_cat_factor_refPostgrado                        0.16 ***
                                                   (0.02)   
edad                                               -0.01 ***
                                                   (0.00)   
edad_cuadratica                                     0.00 ***
                                                   (0.00)   
mujer                                              -0.01 *  
                                                   (0.01)   
ideologia_std                                      -0.03 ***
                                                   (0.00)   
interes_politica                                    0.06 ***
                                                   (0.00)   
factor(year)2017                                   -0.08 ***
                                                   (0.01)   
factor(year)2018                                   -0.05 ***
                                                   (0.01)   
factor(year)2019                                    0.07 ***
                                                   (0.01)   
factor(year)2021                                   -0.12 ***
                                                   (0.01)   
factor(year)2022                                   -0.07 ***
                                                   (0.01)   
factor(year)2023                                   -0.10 ***
                                                   (0.01)   
------------------------------------------------------------
R^2                                                 0.18    
Adj. R^2                                            0.18    
Num. obs.                                       12654       
============================================================
*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
t test of coefficients:

                                                   Estimate   Std. Error
(Intercept)                                     0.595553251  0.049815656
educ_cat_factor_refMedia incompleta o menos    -0.035785148  0.009497160
educ_cat_factor_refTécnica superior incompleta  0.042101846  0.023149525
educ_cat_factor_refTécnica superior completa    0.038132844  0.013152834
educ_cat_factor_refUniversitaria incompleta     0.107342853  0.020343205
educ_cat_factor_refUniversitaria completa       0.076118671  0.014926124
educ_cat_factor_refPostgrado                    0.160343747  0.034644260
edad                                           -0.010901547  0.002013146
edad_cuadratica                                 0.000068297  0.000019695
mujer                                          -0.013528252  0.008916437
ideologia_std                                  -0.027148766  0.001603980
interes_politica                                0.057099573  0.003808728
factor(year)2017                               -0.075792510  0.012303604
factor(year)2018                               -0.051268630  0.011573441
factor(year)2019                                0.072495701  0.012984841
factor(year)2021                               -0.121481216  0.012157709
factor(year)2022                               -0.073954393  0.013076511
factor(year)2023                               -0.101818787  0.012456730
                                                t value              Pr(&gt;|t|)
(Intercept)                                     11.9551 &lt; 0.00000000000000022
educ_cat_factor_refMedia incompleta o menos     -3.7680             0.0001653
educ_cat_factor_refTécnica superior incompleta   1.8187             0.0689822
educ_cat_factor_refTécnica superior completa     2.8992             0.0037475
educ_cat_factor_refUniversitaria incompleta      5.2766 0.0000001337824921725
educ_cat_factor_refUniversitaria completa        5.0997 0.0000003451283649544
educ_cat_factor_refPostgrado                     4.6283 0.0000037236271812576
edad                                            -5.4152 0.0000000623476548776
edad_cuadratica                                  3.4677             0.0005268
mujer                                           -1.5172             0.1292346
ideologia_std                                  -16.9259 &lt; 0.00000000000000022
interes_politica                                14.9918 &lt; 0.00000000000000022
factor(year)2017                                -6.1602 0.0000000007486545148
factor(year)2018                                -4.4299 0.0000095090638253688
factor(year)2019                                 5.5831 0.0000000241136450741
factor(year)2021                                -9.9921 &lt; 0.00000000000000022
factor(year)2022                                -5.6555 0.0000000158750264248
factor(year)2023                                -8.1738 0.0000000000000003272
                                                  
(Intercept)                                    ***
educ_cat_factor_refMedia incompleta o menos    ***
educ_cat_factor_refTécnica superior incompleta .  
educ_cat_factor_refTécnica superior completa   ** 
educ_cat_factor_refUniversitaria incompleta    ***
educ_cat_factor_refUniversitaria completa      ***
educ_cat_factor_refPostgrado                   ***
edad                                           ***
edad_cuadratica                                ***
mujer                                             
ideologia_std                                  ***
interes_politica                               ***
factor(year)2017                               ***
factor(year)2018                               ***
factor(year)2019                               ***
factor(year)2021                               ***
factor(year)2022                               ***
factor(year)2023                               ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Dado que la estructura de datos es longitudinal con mediciones repetidas por individuo (ICC = 0.475), todos los modelos reportados son regresiones logísticas multinivel con efectos aleatorios por individuo. Estimaciones alternativas con modelos pooled confirmaron la dirección y significancia de los efectos principales.</p>
</section>
<section id="modelos-para-h1-no-linealidad" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="modelos-para-h1-no-linealidad"><span class="header-section-number">1.2</span> Modelos para H1 (No linealidad)</h2>
<section id="modelo-básico-de-educación-categórica" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="modelo-básico-de-educación-categórica"><span class="header-section-number">1.2.1</span> Modelo básico de educación categórica</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
============================================================
                                                Model 1     
------------------------------------------------------------
(Intercept)                                        -2.31 ***
                                                   (0.06)   
educ_cat_factor_refMedia incompleta o menos        -0.87 ***
                                                   (0.08)   
educ_cat_factor_refTécnica superior incompleta      0.83 ***
                                                   (0.12)   
educ_cat_factor_refTécnica superior completa        0.50 ***
                                                   (0.09)   
educ_cat_factor_refUniversitaria incompleta         1.43 ***
                                                   (0.11)   
educ_cat_factor_refUniversitaria completa           1.07 ***
                                                   (0.09)   
educ_cat_factor_refPostgrado                        1.63 ***
                                                   (0.18)   
------------------------------------------------------------
AIC                                             16111.93    
Log Likelihood                                  -8047.96    
Num. obs.                                       20052       
Num. groups: idencuesta                          4429       
Var: idencuesta (Intercept)                         2.04    
============================================================
*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
</div>
</div>
</section>
<section id="modelo-con-controles-demográficos" class="level3" data-number="1.2.2">
<h3 data-number="1.2.2" class="anchored" data-anchor-id="modelo-con-controles-demográficos"><span class="header-section-number">1.2.2</span> Modelo con controles demográficos</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
============================================================
                                                Model 1     
------------------------------------------------------------
(Intercept)                                         0.01    
                                                   (0.13)   
educ_cat_factor_refMedia incompleta o menos        -0.53 ***
                                                   (0.08)   
educ_cat_factor_refTécnica superior incompleta      0.55 ***
                                                   (0.12)   
educ_cat_factor_refTécnica superior completa        0.44 ***
                                                   (0.09)   
educ_cat_factor_refUniversitaria incompleta         0.98 ***
                                                   (0.11)   
educ_cat_factor_refUniversitaria completa           0.89 ***
                                                   (0.09)   
educ_cat_factor_refPostgrado                        1.54 ***
                                                   (0.18)   
edad                                               -0.05 ***
                                                   (0.00)   
mujer                                              -0.30 ***
                                                   (0.07)   
------------------------------------------------------------
AIC                                             15697.80    
Log Likelihood                                  -7838.90    
Num. obs.                                       20052       
Num. groups: idencuesta                          4429       
Var: idencuesta (Intercept)                         1.92    
============================================================
*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
============================================================
                                                Model 1     
------------------------------------------------------------
(Intercept)                                         0.47 ** 
                                                   (0.18)   
educ_cat_factor_refMedia incompleta o menos        -0.60 ***
                                                   (0.11)   
educ_cat_factor_refTécnica superior incompleta      0.40 ** 
                                                   (0.15)   
educ_cat_factor_refTécnica superior completa        0.33 ** 
                                                   (0.11)   
educ_cat_factor_refUniversitaria incompleta         0.68 ***
                                                   (0.13)   
educ_cat_factor_refUniversitaria completa           0.58 ***
                                                   (0.11)   
educ_cat_factor_refPostgrado                        0.97 ***
                                                   (0.21)   
edad                                               -0.04 ***
                                                   (0.00)   
mujer                                              -0.20 *  
                                                   (0.08)   
ideologia_std                                      -0.22 ***
                                                   (0.01)   
interes_politica                                    0.44 ***
                                                   (0.03)   
factor(year)2017                                   -0.69 ***
                                                   (0.12)   
factor(year)2018                                   -0.48 ***
                                                   (0.10)   
factor(year)2019                                    0.54 ***
                                                   (0.10)   
factor(year)2021                                   -1.22 ***
                                                   (0.12)   
factor(year)2022                                   -0.73 ***
                                                   (0.12)   
factor(year)2023                                   -1.08 ***
                                                   (0.12)   
------------------------------------------------------------
AIC                                             10015.48    
Log Likelihood                                  -4989.74    
Num. obs.                                       12654       
Num. groups: idencuesta                          3888       
Var: idencuesta (Intercept)                         1.89    
============================================================
*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
</div>
</div>
</section>
<section id="modelo-completo-h1" class="level3" data-number="1.2.3">
<h3 data-number="1.2.3" class="anchored" data-anchor-id="modelo-completo-h1"><span class="header-section-number">1.2.3</span> Modelo Completo H1</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
============================================================
                                                Model 1     
------------------------------------------------------------
(Intercept)                                         0.58 *  
                                                   (0.23)   
educ_cat_factor_refMedia incompleta o menos        -0.60 ***
                                                   (0.11)   
educ_cat_factor_refTécnica superior incompleta      0.40 *  
                                                   (0.15)   
educ_cat_factor_refTécnica superior completa        0.33 ** 
                                                   (0.11)   
educ_cat_factor_refUniversitaria incompleta         0.69 ***
                                                   (0.13)   
educ_cat_factor_refUniversitaria completa           0.59 ***
                                                   (0.11)   
educ_cat_factor_refPostgrado                        0.99 ***
                                                   (0.21)   
edad                                               -0.04 ***
                                                   (0.00)   
mujer                                              -0.21 ** 
                                                   (0.08)   
ideologia_std                                      -0.21 ***
                                                   (0.01)   
interes_politica                                    0.46 ***
                                                   (0.03)   
conf_instituciones                                 -0.13 ** 
                                                   (0.05)   
eficacia_politica                                   0.02    
                                                   (0.04)   
factor(year)2017                                   -0.69 ***
                                                   (0.12)   
factor(year)2018                                   -0.46 ***
                                                   (0.10)   
factor(year)2019                                    0.49 ***
                                                   (0.10)   
factor(year)2021                                   -1.23 ***
                                                   (0.12)   
factor(year)2022                                   -0.72 ***
                                                   (0.12)   
factor(year)2023                                   -1.06 ***
                                                   (0.12)   
------------------------------------------------------------
AIC                                             10009.57    
Log Likelihood                                  -4984.79    
Num. obs.                                       12648       
Num. groups: idencuesta                          3887       
Var: idencuesta (Intercept)                         1.88    
============================================================
*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
</div>
</div>
</section>
<section id="test-específico-para-h1" class="level3" data-number="1.2.4">
<h3 data-number="1.2.4" class="anchored" data-anchor-id="test-específico-para-h1"><span class="header-section-number">1.2.4</span> Test específico para H1</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 10
  effect component group term      estimate std.error statistic p.value conf.low
  &lt;chr&gt;  &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;        &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;
1 fixed  cond      &lt;NA&gt;  educ_cat…     1.39     0.149      3.05 0.00226     1.12
# ℹ 1 more variable: conf.high &lt;dbl&gt;</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast         odds.ratio     SE  df null z.ratio p.value
 Técnica vs Media      0.773 0.0929 Inf    1  -2.144  0.0320

Results are averaged over the levels of: mujer, year 
Tests are performed on the log odds ratio scale </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast        odds.ratio    SE  df null z.ratio p.value
 Univ vs Técnica       1.29 0.156 Inf    1   2.144  0.0320

Results are averaged over the levels of: mujer, year 
Tests are performed on the log odds ratio scale </code></pre>
</div>
</div>
</section>
</section>
<section id="modelos-para-h2-movilidad-educacional" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="modelos-para-h2-movilidad-educacional"><span class="header-section-number">1.3</span> Modelos para H2 (Movilidad Educacional)</h2>
<section id="efecto-principal-de-movilidad" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="efecto-principal-de-movilidad"><span class="header-section-number">1.3.1</span> Efecto principal de Movilidad</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
=========================================
                             Model 1     
-----------------------------------------
(Intercept)                      0.89 ***
                                (0.18)   
movilidad_cat_factor.L          -0.06    
                                (0.10)   
movilidad_cat_factor.Q           0.13    
                                (0.09)   
movilidad_cat_factor.C          -0.11    
                                (0.07)   
edad                            -0.05 ***
                                (0.00)   
mujer                           -0.26 ** 
                                (0.08)   
ideologia_std                   -0.21 ***
                                (0.01)   
interes_politica                 0.51 ***
                                (0.03)   
factor(year)2017                -0.71 ***
                                (0.12)   
factor(year)2018                -0.47 ***
                                (0.10)   
factor(year)2019                 0.55 ***
                                (0.10)   
factor(year)2021                -1.20 ***
                                (0.12)   
factor(year)2022                -0.69 ***
                                (0.12)   
factor(year)2023                -0.98 ***
                                (0.12)   
-----------------------------------------
AIC                           9807.79    
Log Likelihood               -4888.90    
Num. obs.                    12018       
Num. groups: idencuesta       3664       
Var: idencuesta (Intercept)      1.95    
=========================================
*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
</div>
</div>
</section>
<section id="modelo-aditivo-educación-movilidad-sin-interacción" class="level3" data-number="1.3.2">
<h3 data-number="1.3.2" class="anchored" data-anchor-id="modelo-aditivo-educación-movilidad-sin-interacción"><span class="header-section-number">1.3.2</span> Modelo Aditivo (educación + movilidad sin interacción)</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
============================================================
                                                Model 1     
------------------------------------------------------------
(Intercept)                                         0.56 ** 
                                                   (0.19)   
educ_cat_factor_refMedia incompleta o menos        -0.61 ***
                                                   (0.11)   
educ_cat_factor_refTécnica superior incompleta      0.41 ** 
                                                   (0.16)   
educ_cat_factor_refTécnica superior completa        0.32 ** 
                                                   (0.11)   
educ_cat_factor_refUniversitaria incompleta         0.63 ***
                                                   (0.13)   
educ_cat_factor_refUniversitaria completa           0.61 ***
                                                   (0.12)   
educ_cat_factor_refPostgrado                        0.99 ***
                                                   (0.21)   
movilidad_cat_factor.L                             -0.26 *  
                                                   (0.11)   
movilidad_cat_factor.Q                              0.17    
                                                   (0.09)   
movilidad_cat_factor.C                             -0.07    
                                                   (0.07)   
edad                                               -0.04 ***
                                                   (0.00)   
mujer                                              -0.22 ** 
                                                   (0.08)   
ideologia_std                                      -0.22 ***
                                                   (0.01)   
interes_politica                                    0.43 ***
                                                   (0.03)   
factor(year)2017                                   -0.71 ***
                                                   (0.12)   
factor(year)2018                                   -0.50 ***
                                                   (0.10)   
factor(year)2019                                    0.55 ***
                                                   (0.10)   
factor(year)2021                                   -1.23 ***
                                                   (0.12)   
factor(year)2022                                   -0.75 ***
                                                   (0.12)   
factor(year)2023                                   -1.08 ***
                                                   (0.12)   
------------------------------------------------------------
AIC                                              9697.77    
Log Likelihood                                  -4827.88    
Num. obs.                                       12018       
Num. groups: idencuesta                          3664       
Var: idencuesta (Intercept)                         1.85    
============================================================
*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
</div>
</div>
</section>
<section id="modelo-con-interacción" class="level3" data-number="1.3.3">
<h3 data-number="1.3.3" class="anchored" data-anchor-id="modelo-con-interacción"><span class="header-section-number">1.3.3</span> Modelo con interacción</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
===================================================================================
                                                                       Model 1     
-----------------------------------------------------------------------------------
(Intercept)                                                                0.54 ** 
                                                                          (0.20)   
educ_cat_factor_refMedia incompleta o menos                               -0.64 ***
                                                                          (0.14)   
educ_cat_factor_refTécnica superior incompleta                             0.32    
                                                                          (0.19)   
educ_cat_factor_refTécnica superior completa                               0.27    
                                                                          (0.15)   
educ_cat_factor_refUniversitaria incompleta                                0.55 ***
                                                                          (0.17)   
educ_cat_factor_refUniversitaria completa                                  0.13    
                                                                          (0.25)   
educ_cat_factor_refPostgrado                                               0.51    
                                                                          (0.43)   
movilidad_cat_factor.L                                                    -0.31    
                                                                          (0.25)   
movilidad_cat_factor.Q                                                     0.25    
                                                                          (0.20)   
movilidad_cat_factor.C                                                     0.01    
                                                                          (0.15)   
edad                                                                      -0.04 ***
                                                                          (0.00)   
mujer                                                                     -0.22 ** 
                                                                          (0.08)   
ideologia_std                                                             -0.22 ***
                                                                          (0.01)   
interes_politica                                                           0.43 ***
                                                                          (0.03)   
factor(year)2017                                                          -0.71 ***
                                                                          (0.12)   
factor(year)2018                                                          -0.49 ***
                                                                          (0.10)   
factor(year)2019                                                           0.56 ***
                                                                          (0.10)   
factor(year)2021                                                          -1.24 ***
                                                                          (0.12)   
factor(year)2022                                                          -0.75 ***
                                                                          (0.12)   
factor(year)2023                                                          -1.08 ***
                                                                          (0.12)   
educ_cat_factor_refMedia incompleta o menos:movilidad_cat_factor.L         0.20    
                                                                          (0.31)   
educ_cat_factor_refTécnica superior incompleta:movilidad_cat_factor.L     -0.12    
                                                                          (0.45)   
educ_cat_factor_refTécnica superior completa:movilidad_cat_factor.L        0.02    
                                                                          (0.33)   
educ_cat_factor_refUniversitaria incompleta:movilidad_cat_factor.L        -0.40    
                                                                          (0.34)   
educ_cat_factor_refUniversitaria completa:movilidad_cat_factor.L           1.18    
                                                                          (0.62)   
educ_cat_factor_refPostgrado:movilidad_cat_factor.L                        1.64    
                                                                          (1.20)   
educ_cat_factor_refMedia incompleta o menos:movilidad_cat_factor.Q        -0.05    
                                                                          (0.27)   
educ_cat_factor_refTécnica superior incompleta:movilidad_cat_factor.Q     -0.28    
                                                                          (0.38)   
educ_cat_factor_refTécnica superior completa:movilidad_cat_factor.Q        0.20    
                                                                          (0.30)   
educ_cat_factor_refUniversitaria incompleta:movilidad_cat_factor.Q        -0.37    
                                                                          (0.32)   
educ_cat_factor_refUniversitaria completa:movilidad_cat_factor.Q          -0.98 *  
                                                                          (0.49)   
educ_cat_factor_refPostgrado:movilidad_cat_factor.Q                       -0.94    
                                                                          (0.96)   
educ_cat_factor_refMedia incompleta o menos:movilidad_cat_factor.C         0.07    
                                                                          (0.22)   
educ_cat_factor_refTécnica superior incompleta:movilidad_cat_factor.C      0.12    
                                                                          (0.30)   
educ_cat_factor_refTécnica superior completa:movilidad_cat_factor.C        0.15    
                                                                          (0.26)   
educ_cat_factor_refUniversitaria incompleta:movilidad_cat_factor.C        -0.13    
                                                                          (0.31)   
educ_cat_factor_refUniversitaria completa:movilidad_cat_factor.C                   
                                                                                   
educ_cat_factor_refPostgrado:movilidad_cat_factor.C                                
                                                                                   
-----------------------------------------------------------------------------------
AIC                                                                     9712.45    
Log Likelihood                                                         -4819.22    
Num. obs.                                                              12018       
Num. groups: idencuesta                                                 3664       
Var: idencuesta (Intercept)                                                1.83    
===================================================================================
*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
</div>
</div>
</section>
<section id="test-de-interacción-lrt" class="level3" data-number="1.3.4">
<h3 data-number="1.3.4" class="anchored" data-anchor-id="test-de-interacción-lrt"><span class="header-section-number">1.3.4</span> Test de interacción (LRT)</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Data: elsoc_final %&gt;% filter(!is.na(movilidad_cat))
Models:
mod5_aditivo: protesta_dummy ~ educ_cat_factor_ref + movilidad_cat_factor + , zi=~0, disp=~1
mod5_aditivo:     edad + mujer + ideologia_std + interes_politica + factor(year) + , zi=~0, disp=~1
mod5_aditivo:     (1 | idencuesta), zi=~0, disp=~1
mod6_h2_interaccion: protesta_dummy ~ educ_cat_factor_ref * movilidad_cat_factor + , zi=~0, disp=~1
mod6_h2_interaccion:     edad + mujer + ideologia_std + interes_politica + factor(year) + , zi=~0, disp=~1
mod6_h2_interaccion:     (1 | idencuesta), zi=~0, disp=~1
                    Df    AIC  BIC  logLik deviance  Chisq Chi Df Pr(&gt;Chisq)
mod5_aditivo        21 9697.8 9853 -4827.9   9655.8                         
mod6_h2_interaccion 37 9712.4 9986 -4819.2   9638.4 17.317     16     0.3653</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-modelos_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="720"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="análisis-de-mediación" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="análisis-de-mediación"><span class="header-section-number">1.4</span> Análisis de Mediación</h2>
<section id="modelo-con-mediaciones" class="level3" data-number="1.4.1">
<h3 data-number="1.4.1" class="anchored" data-anchor-id="modelo-con-mediaciones"><span class="header-section-number">1.4.1</span> Modelo con mediaciones</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
===================================================================================
                                                                       Model 1     
-----------------------------------------------------------------------------------
(Intercept)                                                                0.26    
                                                                          (0.40)   
educ_cat_factor_refMedia incompleta o menos                               -0.42    
                                                                          (0.23)   
educ_cat_factor_refTécnica superior incompleta                             0.35    
                                                                          (0.39)   
educ_cat_factor_refTécnica superior completa                               0.58 *  
                                                                          (0.23)   
educ_cat_factor_refUniversitaria incompleta                                1.11 ***
                                                                          (0.28)   
educ_cat_factor_refUniversitaria completa                                  0.37    
                                                                          (0.36)   
educ_cat_factor_refPostgrado                                               1.12    
                                                                          (0.59)   
movilidad_cat_factor.L                                                    -0.43    
                                                                          (0.41)   
movilidad_cat_factor.Q                                                    -0.11    
                                                                          (0.33)   
movilidad_cat_factor.C                                                     0.06    
                                                                          (0.23)   
justicia_distributiva                                                     -0.14 *  
                                                                          (0.07)   
meritocracia                                                               0.05    
                                                                          (0.06)   
clase_subjetiva                                                           -0.15 *  
                                                                          (0.08)   
satis_ingreso_std                                                         -0.06    
                                                                          (0.05)   
edad                                                                      -0.03 ***
                                                                          (0.00)   
mujer                                                                     -0.10    
                                                                          (0.11)   
ideologia_std                                                             -0.22 ***
                                                                          (0.02)   
interes_politica                                                           0.49 ***
                                                                          (0.05)   
factor(year)2018                                                          -0.47 ***
                                                                          (0.13)   
factor(year)2019                                                           0.49 ** 
                                                                          (0.17)   
factor(year)2022                                                          -0.87 ***
                                                                          (0.20)   
factor(year)2023                                                          -0.94 ***
                                                                          (0.20)   
educ_cat_factor_refMedia incompleta o menos:movilidad_cat_factor.L         0.43    
                                                                          (0.52)   
educ_cat_factor_refTécnica superior incompleta:movilidad_cat_factor.L      0.36    
                                                                          (0.97)   
educ_cat_factor_refTécnica superior completa:movilidad_cat_factor.L        0.19    
                                                                          (0.53)   
educ_cat_factor_refUniversitaria incompleta:movilidad_cat_factor.L         0.04    
                                                                          (0.58)   
educ_cat_factor_refUniversitaria completa:movilidad_cat_factor.L           1.51    
                                                                          (0.89)   
educ_cat_factor_refPostgrado:movilidad_cat_factor.L                        1.28    
                                                                          (1.62)   
educ_cat_factor_refMedia incompleta o menos:movilidad_cat_factor.Q         0.53    
                                                                          (0.44)   
educ_cat_factor_refTécnica superior incompleta:movilidad_cat_factor.Q     -0.14    
                                                                          (0.78)   
educ_cat_factor_refTécnica superior completa:movilidad_cat_factor.Q        0.35    
                                                                          (0.46)   
educ_cat_factor_refUniversitaria incompleta:movilidad_cat_factor.Q        -0.04    
                                                                          (0.54)   
educ_cat_factor_refUniversitaria completa:movilidad_cat_factor.Q          -1.08    
                                                                          (0.71)   
educ_cat_factor_refPostgrado:movilidad_cat_factor.Q                       -0.38    
                                                                          (1.34)   
educ_cat_factor_refMedia incompleta o menos:movilidad_cat_factor.C         0.15    
                                                                          (0.36)   
educ_cat_factor_refTécnica superior incompleta:movilidad_cat_factor.C      0.56    
                                                                          (0.53)   
educ_cat_factor_refTécnica superior completa:movilidad_cat_factor.C        0.04    
                                                                          (0.38)   
educ_cat_factor_refUniversitaria incompleta:movilidad_cat_factor.C        -0.06    
                                                                          (0.49)   
educ_cat_factor_refUniversitaria completa:movilidad_cat_factor.C                   
                                                                                   
educ_cat_factor_refPostgrado:movilidad_cat_factor.C                                
                                                                                   
-----------------------------------------------------------------------------------
AIC                                                                     3626.00    
Log Likelihood                                                         -1774.00    
Num. obs.                                                               3723       
Num. groups: idencuesta                                                 2252       
Var: idencuesta (Intercept)                                                1.64    
===================================================================================
*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
</div>
</div>
</section>
<section id="comparar-efecto-total-vs-directo" class="level3" data-number="1.4.2">
<h3 data-number="1.4.2" class="anchored" data-anchor-id="comparar-efecto-total-vs-directo"><span class="header-section-number">1.4.2</span> Comparar efecto total vs directo</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 21 × 10
   term    estimate_total se_total p_total estimate_directo se_directo p_directo
   &lt;chr&gt;            &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;            &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;
 1 movili…        -0.313     0.247  0.205           -0.434       0.408    0.288 
 2 movili…         0.248     0.202  0.221           -0.112       0.330    0.733 
 3 movili…         0.0106    0.148  0.943            0.0608      0.229    0.791 
 4 educ_c…         0.202     0.309  0.514            0.429       0.521    0.410 
 5 educ_c…        -0.118     0.446  0.792            0.364       0.969    0.707 
 6 educ_c…         0.0230    0.334  0.945            0.192       0.527    0.715 
 7 educ_c…        -0.404     0.344  0.240            0.0373      0.581    0.949 
 8 educ_c…         1.18      0.623  0.0588           1.51        0.894    0.0914
 9 educ_c…         1.64      1.20   0.170            1.28        1.62     0.430 
10 educ_c…        -0.0515    0.267  0.847            0.531       0.445    0.233 
# ℹ 11 more rows
# ℹ 3 more variables: efecto_indirecto &lt;dbl&gt;, cambio_pct &lt;dbl&gt;, reduccion &lt;lgl&gt;</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 24 × 10
   term    estimate_total se_total p_total estimate_directo se_directo p_directo
   &lt;chr&gt;            &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;            &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;
 1 educ_c…        -0.637     0.137 3.51e-6          -0.419       0.228 0.0663   
 2 educ_c…         0.319     0.191 9.51e-2           0.352       0.393 0.370    
 3 educ_c…         0.271     0.149 6.96e-2           0.578       0.231 0.0124   
 4 educ_c…         0.553     0.166 8.94e-4           1.11        0.282 0.0000865
 5 educ_c…         0.135     0.247 5.85e-1           0.370       0.356 0.299    
 6 educ_c…         0.509     0.425 2.31e-1           1.12        0.589 0.0575   
 7 educ_c…         0.202     0.309 5.14e-1           0.429       0.521 0.410    
 8 educ_c…        -0.118     0.446 7.92e-1           0.364       0.969 0.707    
 9 educ_c…         0.0230    0.334 9.45e-1           0.192       0.527 0.715    
10 educ_c…        -0.404     0.344 2.40e-1           0.0373      0.581 0.949    
# ℹ 14 more rows
# ℹ 3 more variables: efecto_indirecto &lt;dbl&gt;, prop_mediada &lt;dbl&gt;,
#   reduccion &lt;lgl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 21 × 10
   term    estimate_total se_total p_total estimate_directo se_directo p_directo
   &lt;chr&gt;            &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;            &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;
 1 movili…        -0.313     0.247  0.205           -0.434       0.408    0.288 
 2 movili…         0.248     0.202  0.221           -0.112       0.330    0.733 
 3 movili…         0.0106    0.148  0.943            0.0608      0.229    0.791 
 4 educ_c…         0.202     0.309  0.514            0.429       0.521    0.410 
 5 educ_c…        -0.118     0.446  0.792            0.364       0.969    0.707 
 6 educ_c…         0.0230    0.334  0.945            0.192       0.527    0.715 
 7 educ_c…        -0.404     0.344  0.240            0.0373      0.581    0.949 
 8 educ_c…         1.18      0.623  0.0588           1.51        0.894    0.0914
 9 educ_c…         1.64      1.20   0.170            1.28        1.62     0.430 
10 educ_c…        -0.0515    0.267  0.847            0.531       0.445    0.233 
# ℹ 11 more rows
# ℹ 3 more variables: efecto_indirecto &lt;dbl&gt;, cambio_pct &lt;dbl&gt;, reduccion &lt;lgl&gt;</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 24 × 10
   term    estimate_total se_total p_total estimate_directo se_directo p_directo
   &lt;chr&gt;            &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;            &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;
 1 educ_c…        -0.637     0.137 3.51e-6          -0.419       0.228 0.0663   
 2 educ_c…         0.319     0.191 9.51e-2           0.352       0.393 0.370    
 3 educ_c…         0.271     0.149 6.96e-2           0.578       0.231 0.0124   
 4 educ_c…         0.553     0.166 8.94e-4           1.11        0.282 0.0000865
 5 educ_c…         0.135     0.247 5.85e-1           0.370       0.356 0.299    
 6 educ_c…         0.509     0.425 2.31e-1           1.12        0.589 0.0575   
 7 educ_c…         0.202     0.309 5.14e-1           0.429       0.521 0.410    
 8 educ_c…        -0.118     0.446 7.92e-1           0.364       0.969 0.707    
 9 educ_c…         0.0230    0.334 9.45e-1           0.192       0.527 0.715    
10 educ_c…        -0.404     0.344 2.40e-1           0.0373      0.581 0.949    
# ℹ 14 more rows
# ℹ 3 more variables: efecto_indirecto &lt;dbl&gt;, prop_mediada &lt;dbl&gt;,
#   reduccion &lt;lgl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-modelos_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="720"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-modelos_files/figure-html/unnamed-chunk-20-2.png" class="img-fluid figure-img" width="720"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="kwosgnzxzr" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#kwosgnzxzr table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#kwosgnzxzr thead, #kwosgnzxzr tbody, #kwosgnzxzr tfoot, #kwosgnzxzr tr, #kwosgnzxzr td, #kwosgnzxzr th {
  border-style: none;
}

#kwosgnzxzr p {
  margin: 0;
  padding: 0;
}

#kwosgnzxzr .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#kwosgnzxzr .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#kwosgnzxzr .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#kwosgnzxzr .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#kwosgnzxzr .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#kwosgnzxzr .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#kwosgnzxzr .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#kwosgnzxzr .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#kwosgnzxzr .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#kwosgnzxzr .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#kwosgnzxzr .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#kwosgnzxzr .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#kwosgnzxzr .gt_spanner_row {
  border-bottom-style: hidden;
}

#kwosgnzxzr .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#kwosgnzxzr .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#kwosgnzxzr .gt_from_md > :first-child {
  margin-top: 0;
}

#kwosgnzxzr .gt_from_md > :last-child {
  margin-bottom: 0;
}

#kwosgnzxzr .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#kwosgnzxzr .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#kwosgnzxzr .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#kwosgnzxzr .gt_row_group_first td {
  border-top-width: 2px;
}

#kwosgnzxzr .gt_row_group_first th {
  border-top-width: 2px;
}

#kwosgnzxzr .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#kwosgnzxzr .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#kwosgnzxzr .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#kwosgnzxzr .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#kwosgnzxzr .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#kwosgnzxzr .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#kwosgnzxzr .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#kwosgnzxzr .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#kwosgnzxzr .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#kwosgnzxzr .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#kwosgnzxzr .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#kwosgnzxzr .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#kwosgnzxzr .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#kwosgnzxzr .gt_left {
  text-align: left;
}

#kwosgnzxzr .gt_center {
  text-align: center;
}

#kwosgnzxzr .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#kwosgnzxzr .gt_font_normal {
  font-weight: normal;
}

#kwosgnzxzr .gt_font_bold {
  font-weight: bold;
}

#kwosgnzxzr .gt_font_italic {
  font-style: italic;
}

#kwosgnzxzr .gt_super {
  font-size: 65%;
}

#kwosgnzxzr .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#kwosgnzxzr .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#kwosgnzxzr .gt_indent_1 {
  text-indent: 5px;
}

#kwosgnzxzr .gt_indent_2 {
  text-indent: 10px;
}

#kwosgnzxzr .gt_indent_3 {
  text-indent: 15px;
}

#kwosgnzxzr .gt_indent_4 {
  text-indent: 20px;
}

#kwosgnzxzr .gt_indent_5 {
  text-indent: 25px;
}

#kwosgnzxzr .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#kwosgnzxzr div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-bootstrap="false">
<thead>
<tr class="gt_heading header">
<td colspan="7" class="gt_heading gt_title gt_font_normal">Análisis de Mediación: Educación → Protesta</td>
</tr>
<tr class="gt_heading even">
<td colspan="7" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border">Comparación de efectos totales vs. directos</td>
</tr>
<tr class="gt_col_headings header">
<th id="Nivel-Educativo" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Nivel Educativo</th>
<th id="Efecto-Total" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">Efecto Total</th>
<th id="Sig." class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">Sig.</th>
<th id="Efecto-Directo" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">Efecto Directo</th>
<th id="Sig.-" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">Sig.</th>
<th id="Efecto-Indirecto" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">Efecto Indirecto</th>
<th id="a%-Mediado" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">% Mediado</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="Nivel Educativo">Media incompleta o menos</td>
<td class="gt_row gt_center" headers="Efecto Total">−0.637</td>
<td class="gt_row gt_center" headers="Sig.">***</td>
<td class="gt_row gt_center" headers="Efecto Directo">−0.419</td>
<td class="gt_row gt_center" headers="Sig. "></td>
<td class="gt_row gt_center" headers="Efecto Indirecto">−0.218</td>
<td class="gt_row gt_center" headers="% Mediado">34.3</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Nivel Educativo">Técnica superior incompleta</td>
<td class="gt_row gt_center" headers="Efecto Total">0.319</td>
<td class="gt_row gt_center" headers="Sig."></td>
<td class="gt_row gt_center" headers="Efecto Directo">0.352</td>
<td class="gt_row gt_center" headers="Sig. "></td>
<td class="gt_row gt_center" headers="Efecto Indirecto">−0.034</td>
<td class="gt_row gt_center" headers="% Mediado">−10.5</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Nivel Educativo">Técnica superior completa</td>
<td class="gt_row gt_center" headers="Efecto Total">0.271</td>
<td class="gt_row gt_center" headers="Sig."></td>
<td class="gt_row gt_center" headers="Efecto Directo">0.578</td>
<td class="gt_row gt_center" headers="Sig. ">***</td>
<td class="gt_row gt_center" headers="Efecto Indirecto">−0.307</td>
<td class="gt_row gt_center" headers="% Mediado">−113.2</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Nivel Educativo">Universitaria incompleta</td>
<td class="gt_row gt_center" headers="Efecto Total">0.553</td>
<td class="gt_row gt_center" headers="Sig.">***</td>
<td class="gt_row gt_center" headers="Efecto Directo">1.106</td>
<td class="gt_row gt_center" headers="Sig. ">***</td>
<td class="gt_row gt_center" headers="Efecto Indirecto">−0.553</td>
<td class="gt_row gt_center" headers="% Mediado">−100.0</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Nivel Educativo">Universitaria completa</td>
<td class="gt_row gt_center" headers="Efecto Total">0.135</td>
<td class="gt_row gt_center" headers="Sig."></td>
<td class="gt_row gt_center" headers="Efecto Directo">0.370</td>
<td class="gt_row gt_center" headers="Sig. "></td>
<td class="gt_row gt_center" headers="Efecto Indirecto">−0.235</td>
<td class="gt_row gt_center" headers="% Mediado">−174.2</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Nivel Educativo">Postgrado</td>
<td class="gt_row gt_center" headers="Efecto Total">0.509</td>
<td class="gt_row gt_center" headers="Sig."></td>
<td class="gt_row gt_center" headers="Efecto Directo">1.119</td>
<td class="gt_row gt_center" headers="Sig. "></td>
<td class="gt_row gt_center" headers="Efecto Indirecto">−0.610</td>
<td class="gt_row gt_center" headers="% Mediado">−120.0</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Nivel Educativo">Media incompleta o menos:movilidad_cat_factor.L</td>
<td class="gt_row gt_center" headers="Efecto Total">0.202</td>
<td class="gt_row gt_center" headers="Sig."></td>
<td class="gt_row gt_center" headers="Efecto Directo">0.429</td>
<td class="gt_row gt_center" headers="Sig. "></td>
<td class="gt_row gt_center" headers="Efecto Indirecto">−0.227</td>
<td class="gt_row gt_center" headers="% Mediado">−112.7</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Nivel Educativo">Técnica superior incompleta:movilidad_cat_factor.L</td>
<td class="gt_row gt_center" headers="Efecto Total">−0.118</td>
<td class="gt_row gt_center" headers="Sig."></td>
<td class="gt_row gt_center" headers="Efecto Directo">0.364</td>
<td class="gt_row gt_center" headers="Sig. "></td>
<td class="gt_row gt_center" headers="Efecto Indirecto">−0.482</td>
<td class="gt_row gt_center" headers="% Mediado">408.6</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Nivel Educativo">Técnica superior completa:movilidad_cat_factor.L</td>
<td class="gt_row gt_center" headers="Efecto Total">0.023</td>
<td class="gt_row gt_center" headers="Sig."></td>
<td class="gt_row gt_center" headers="Efecto Directo">0.192</td>
<td class="gt_row gt_center" headers="Sig. "></td>
<td class="gt_row gt_center" headers="Efecto Indirecto">−0.169</td>
<td class="gt_row gt_center" headers="% Mediado">−733.2</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Nivel Educativo">Universitaria incompleta:movilidad_cat_factor.L</td>
<td class="gt_row gt_center" headers="Efecto Total">−0.404</td>
<td class="gt_row gt_center" headers="Sig."></td>
<td class="gt_row gt_center" headers="Efecto Directo">0.037</td>
<td class="gt_row gt_center" headers="Sig. "></td>
<td class="gt_row gt_center" headers="Efecto Indirecto">−0.441</td>
<td class="gt_row gt_center" headers="% Mediado">109.2</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Nivel Educativo">Universitaria completa:movilidad_cat_factor.L</td>
<td class="gt_row gt_center" headers="Efecto Total">1.177</td>
<td class="gt_row gt_center" headers="Sig."></td>
<td class="gt_row gt_center" headers="Efecto Directo">1.509</td>
<td class="gt_row gt_center" headers="Sig. "></td>
<td class="gt_row gt_center" headers="Efecto Indirecto">−0.332</td>
<td class="gt_row gt_center" headers="% Mediado">−28.2</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Nivel Educativo">Postgrado:movilidad_cat_factor.L</td>
<td class="gt_row gt_center" headers="Efecto Total">1.641</td>
<td class="gt_row gt_center" headers="Sig."></td>
<td class="gt_row gt_center" headers="Efecto Directo">1.279</td>
<td class="gt_row gt_center" headers="Sig. "></td>
<td class="gt_row gt_center" headers="Efecto Indirecto">0.362</td>
<td class="gt_row gt_center" headers="% Mediado">22.1</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Nivel Educativo">Media incompleta o menos:movilidad_cat_factor.Q</td>
<td class="gt_row gt_center" headers="Efecto Total">−0.051</td>
<td class="gt_row gt_center" headers="Sig."></td>
<td class="gt_row gt_center" headers="Efecto Directo">0.531</td>
<td class="gt_row gt_center" headers="Sig. "></td>
<td class="gt_row gt_center" headers="Efecto Indirecto">−0.582</td>
<td class="gt_row gt_center" headers="% Mediado">1,130.7</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Nivel Educativo">Técnica superior incompleta:movilidad_cat_factor.Q</td>
<td class="gt_row gt_center" headers="Efecto Total">−0.276</td>
<td class="gt_row gt_center" headers="Sig."></td>
<td class="gt_row gt_center" headers="Efecto Directo">−0.143</td>
<td class="gt_row gt_center" headers="Sig. "></td>
<td class="gt_row gt_center" headers="Efecto Indirecto">−0.133</td>
<td class="gt_row gt_center" headers="% Mediado">48.2</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Nivel Educativo">Técnica superior completa:movilidad_cat_factor.Q</td>
<td class="gt_row gt_center" headers="Efecto Total">0.199</td>
<td class="gt_row gt_center" headers="Sig."></td>
<td class="gt_row gt_center" headers="Efecto Directo">0.348</td>
<td class="gt_row gt_center" headers="Sig. "></td>
<td class="gt_row gt_center" headers="Efecto Indirecto">−0.149</td>
<td class="gt_row gt_center" headers="% Mediado">−74.6</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Nivel Educativo">Universitaria incompleta:movilidad_cat_factor.Q</td>
<td class="gt_row gt_center" headers="Efecto Total">−0.375</td>
<td class="gt_row gt_center" headers="Sig."></td>
<td class="gt_row gt_center" headers="Efecto Directo">−0.035</td>
<td class="gt_row gt_center" headers="Sig. "></td>
<td class="gt_row gt_center" headers="Efecto Indirecto">−0.340</td>
<td class="gt_row gt_center" headers="% Mediado">90.7</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Nivel Educativo">Universitaria completa:movilidad_cat_factor.Q</td>
<td class="gt_row gt_center" headers="Efecto Total">−0.978</td>
<td class="gt_row gt_center" headers="Sig.">***</td>
<td class="gt_row gt_center" headers="Efecto Directo">−1.077</td>
<td class="gt_row gt_center" headers="Sig. "></td>
<td class="gt_row gt_center" headers="Efecto Indirecto">0.099</td>
<td class="gt_row gt_center" headers="% Mediado">−10.1</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Nivel Educativo">Postgrado:movilidad_cat_factor.Q</td>
<td class="gt_row gt_center" headers="Efecto Total">−0.939</td>
<td class="gt_row gt_center" headers="Sig."></td>
<td class="gt_row gt_center" headers="Efecto Directo">−0.383</td>
<td class="gt_row gt_center" headers="Sig. "></td>
<td class="gt_row gt_center" headers="Efecto Indirecto">−0.556</td>
<td class="gt_row gt_center" headers="% Mediado">59.2</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Nivel Educativo">Media incompleta o menos:movilidad_cat_factor.C</td>
<td class="gt_row gt_center" headers="Efecto Total">0.067</td>
<td class="gt_row gt_center" headers="Sig."></td>
<td class="gt_row gt_center" headers="Efecto Directo">0.151</td>
<td class="gt_row gt_center" headers="Sig. "></td>
<td class="gt_row gt_center" headers="Efecto Indirecto">−0.084</td>
<td class="gt_row gt_center" headers="% Mediado">−125.1</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Nivel Educativo">Técnica superior incompleta:movilidad_cat_factor.C</td>
<td class="gt_row gt_center" headers="Efecto Total">0.124</td>
<td class="gt_row gt_center" headers="Sig."></td>
<td class="gt_row gt_center" headers="Efecto Directo">0.555</td>
<td class="gt_row gt_center" headers="Sig. "></td>
<td class="gt_row gt_center" headers="Efecto Indirecto">−0.431</td>
<td class="gt_row gt_center" headers="% Mediado">−347.3</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Nivel Educativo">Técnica superior completa:movilidad_cat_factor.C</td>
<td class="gt_row gt_center" headers="Efecto Total">0.151</td>
<td class="gt_row gt_center" headers="Sig."></td>
<td class="gt_row gt_center" headers="Efecto Directo">0.037</td>
<td class="gt_row gt_center" headers="Sig. "></td>
<td class="gt_row gt_center" headers="Efecto Indirecto">0.114</td>
<td class="gt_row gt_center" headers="% Mediado">75.3</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Nivel Educativo">Universitaria incompleta:movilidad_cat_factor.C</td>
<td class="gt_row gt_center" headers="Efecto Total">−0.130</td>
<td class="gt_row gt_center" headers="Sig."></td>
<td class="gt_row gt_center" headers="Efecto Directo">−0.060</td>
<td class="gt_row gt_center" headers="Sig. "></td>
<td class="gt_row gt_center" headers="Efecto Indirecto">−0.070</td>
<td class="gt_row gt_center" headers="% Mediado">54.1</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Nivel Educativo">Universitaria completa:movilidad_cat_factor.C</td>
<td class="gt_row gt_center" headers="Efecto Total">NA</td>
<td class="gt_row gt_center" headers="Sig.">NA</td>
<td class="gt_row gt_center" headers="Efecto Directo">NA</td>
<td class="gt_row gt_center" headers="Sig. ">NA</td>
<td class="gt_row gt_center" headers="Efecto Indirecto">NA</td>
<td class="gt_row gt_center" headers="% Mediado">NA</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Nivel Educativo">Postgrado:movilidad_cat_factor.C</td>
<td class="gt_row gt_center" headers="Efecto Total">NA</td>
<td class="gt_row gt_center" headers="Sig.">NA</td>
<td class="gt_row gt_center" headers="Efecto Directo">NA</td>
<td class="gt_row gt_center" headers="Sig. ">NA</td>
<td class="gt_row gt_center" headers="Efecto Indirecto">NA</td>
<td class="gt_row gt_center" headers="% Mediado">NA</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
</section>
<section id="robutez-y-diagnósticos" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="robutez-y-diagnósticos"><span class="header-section-number">1.5</span> Robutez y Diagnósticos</h2>
<section id="modelos-alternativos" class="level3" data-number="1.5.1">
<h3 data-number="1.5.1" class="anchored" data-anchor-id="modelos-alternativos"><span class="header-section-number">1.5.1</span> Modelos Alternativos</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
=========================================
                             Model 1     
-----------------------------------------
(Intercept)                     -0.48    
                                (0.26)   
educ_years                       0.17 ***
                                (0.01)   
movilidad_years                 -0.10 ** 
                                (0.03)   
edad                            -0.04 ***
                                (0.00)   
mujer                           -0.28 ***
                                (0.08)   
ideologia_std                   -0.22 ***
                                (0.01)   
factor(year)2017                -0.56 ***
                                (0.12)   
factor(year)2018                -0.45 ***
                                (0.10)   
factor(year)2019                 0.75 ***
                                (0.10)   
factor(year)2021                -1.08 ***
                                (0.11)   
factor(year)2022                -0.63 ***
                                (0.12)   
factor(year)2023                -1.04 ***
                                (0.12)   
educ_years:movilidad_years       0.01 *  
                                (0.00)   
-----------------------------------------
AIC                           9945.99    
Log Likelihood               -4958.99    
Num. obs.                    12026       
Num. groups: idencuesta       3664       
Var: idencuesta (Intercept)      2.03    
=========================================
*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
===================================================================================
                                                                       Model 1     
-----------------------------------------------------------------------------------
(Intercept)                                                                1.76 ***
                                                                          (0.23)   
educ_cat_factor_refMedia incompleta o menos                               -0.50 ** 
                                                                          (0.16)   
educ_cat_factor_refTécnica superior incompleta                             0.63 ** 
                                                                          (0.24)   
educ_cat_factor_refTécnica superior completa                               0.36 *  
                                                                          (0.18)   
educ_cat_factor_refUniversitaria incompleta                                0.57 ** 
                                                                          (0.21)   
educ_cat_factor_refUniversitaria completa                                  0.42    
                                                                          (0.29)   
educ_cat_factor_refPostgrado                                               0.91    
                                                                          (0.48)   
movilidad_cat_factor.L                                                    -0.70 *  
                                                                          (0.30)   
movilidad_cat_factor.Q                                                     0.27    
                                                                          (0.24)   
movilidad_cat_factor.C                                                    -0.22    
                                                                          (0.18)   
edad                                                                      -0.05 ***
                                                                          (0.00)   
mujer                                                                     -0.17    
                                                                          (0.09)   
ideologia_std                                                             -0.28 ***
                                                                          (0.02)   
educ_cat_factor_refMedia incompleta o menos:movilidad_cat_factor.L         0.53    
                                                                          (0.37)   
educ_cat_factor_refTécnica superior incompleta:movilidad_cat_factor.L      0.38    
                                                                          (0.56)   
educ_cat_factor_refTécnica superior completa:movilidad_cat_factor.L        0.28    
                                                                          (0.41)   
educ_cat_factor_refUniversitaria incompleta:movilidad_cat_factor.L        -0.02    
                                                                          (0.44)   
educ_cat_factor_refUniversitaria completa:movilidad_cat_factor.L           0.81    
                                                                          (0.73)   
educ_cat_factor_refPostgrado:movilidad_cat_factor.L                        1.38    
                                                                          (1.34)   
educ_cat_factor_refMedia incompleta o menos:movilidad_cat_factor.Q        -0.29    
                                                                          (0.32)   
educ_cat_factor_refTécnica superior incompleta:movilidad_cat_factor.Q     -0.12    
                                                                          (0.47)   
educ_cat_factor_refTécnica superior completa:movilidad_cat_factor.Q        0.12    
                                                                          (0.36)   
educ_cat_factor_refUniversitaria incompleta:movilidad_cat_factor.Q        -0.08    
                                                                          (0.41)   
educ_cat_factor_refUniversitaria completa:movilidad_cat_factor.Q          -0.21    
                                                                          (0.57)   
educ_cat_factor_refPostgrado:movilidad_cat_factor.Q                       -0.28    
                                                                          (1.09)   
educ_cat_factor_refMedia incompleta o menos:movilidad_cat_factor.C         0.14    
                                                                          (0.26)   
educ_cat_factor_refTécnica superior incompleta:movilidad_cat_factor.C      0.13    
                                                                          (0.37)   
educ_cat_factor_refTécnica superior completa:movilidad_cat_factor.C        0.12    
                                                                          (0.30)   
educ_cat_factor_refUniversitaria incompleta:movilidad_cat_factor.C         0.30    
                                                                          (0.39)   
educ_cat_factor_refUniversitaria completa:movilidad_cat_factor.C                   
                                                                                   
educ_cat_factor_refPostgrado:movilidad_cat_factor.C                                
                                                                                   
-----------------------------------------------------------------------------------
AIC                                                                     6039.87    
Log Likelihood                                                         -2989.94    
Num. obs.                                                               6952       
Num. groups: idencuesta                                                 2846       
Var: idencuesta (Intercept)                                                1.55    
===================================================================================
*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> Family: binomial  ( logit )
Formula:          
protesta_dummy ~ educ_cat_factor_ref * movilidad_cat_factor +  
    edad + mujer + ideologia_std + interes_politica + factor(year) +  
    (1 | idencuesta)
Data: elsoc_final %&gt;% filter(!is.na(movilidad_cat))

      AIC       BIC    logLik -2*log(L)  df.resid 
   9712.4    9986.0   -4819.2    9638.4     11981 

Random effects:

Conditional model:
 Groups     Name        Variance Std.Dev.
 idencuesta (Intercept) 1.831    1.353   
Number of obs: 12018, groups:  idencuesta, 3664

Conditional model:
                                                                      Estimate
(Intercept)                                                            0.53527
educ_cat_factor_refMedia incompleta o menos                           -0.63708
educ_cat_factor_refTécnica superior incompleta                         0.31894
educ_cat_factor_refTécnica superior completa                           0.27124
educ_cat_factor_refUniversitaria incompleta                            0.55281
educ_cat_factor_refUniversitaria completa                              0.13493
educ_cat_factor_refPostgrado                                           0.50886
movilidad_cat_factor.L                                                -0.31281
movilidad_cat_factor.Q                                                 0.24758
movilidad_cat_factor.C                                                 0.01057
edad                                                                  -0.04252
mujer                                                                 -0.22228
ideologia_std                                                         -0.21752
interes_politica                                                       0.42677
factor(year)2017                                                      -0.71229
factor(year)2018                                                      -0.49209
factor(year)2019                                                       0.55558
factor(year)2021                                                      -1.23599
factor(year)2022                                                      -0.74889
factor(year)2023                                                      -1.07782
educ_cat_factor_refMedia incompleta o menos:movilidad_cat_factor.L     0.20184
educ_cat_factor_refTécnica superior incompleta:movilidad_cat_factor.L -0.11787
educ_cat_factor_refTécnica superior completa:movilidad_cat_factor.L    0.02304
educ_cat_factor_refUniversitaria incompleta:movilidad_cat_factor.L    -0.40393
educ_cat_factor_refUniversitaria completa:movilidad_cat_factor.L       1.17677
educ_cat_factor_refPostgrado:movilidad_cat_factor.L                    1.64111
educ_cat_factor_refMedia incompleta o menos:movilidad_cat_factor.Q    -0.05147
educ_cat_factor_refTécnica superior incompleta:movilidad_cat_factor.Q -0.27594
educ_cat_factor_refTécnica superior completa:movilidad_cat_factor.Q    0.19906
educ_cat_factor_refUniversitaria incompleta:movilidad_cat_factor.Q    -0.37466
educ_cat_factor_refUniversitaria completa:movilidad_cat_factor.Q      -0.97835
educ_cat_factor_refPostgrado:movilidad_cat_factor.Q                   -0.93860
educ_cat_factor_refMedia incompleta o menos:movilidad_cat_factor.C     0.06712
educ_cat_factor_refTécnica superior incompleta:movilidad_cat_factor.C  0.12413
educ_cat_factor_refTécnica superior completa:movilidad_cat_factor.C    0.15086
educ_cat_factor_refUniversitaria incompleta:movilidad_cat_factor.C    -0.13023
educ_cat_factor_refUniversitaria completa:movilidad_cat_factor.C            NA
educ_cat_factor_refPostgrado:movilidad_cat_factor.C                         NA
                                                                      Std. Error
(Intercept)                                                              0.20275
educ_cat_factor_refMedia incompleta o menos                              0.13735
educ_cat_factor_refTécnica superior incompleta                           0.19108
educ_cat_factor_refTécnica superior completa                             0.14947
educ_cat_factor_refUniversitaria incompleta                              0.16640
educ_cat_factor_refUniversitaria completa                                0.24721
educ_cat_factor_refPostgrado                                             0.42515
movilidad_cat_factor.L                                                   0.24679
movilidad_cat_factor.Q                                                   0.20248
movilidad_cat_factor.C                                                   0.14753
edad                                                                     0.00308
mujer                                                                    0.08016
ideologia_std                                                            0.01468
interes_politica                                                         0.02907
factor(year)2017                                                         0.12023
factor(year)2018                                                         0.10353
factor(year)2019                                                         0.10279
factor(year)2021                                                         0.11679
factor(year)2022                                                         0.11723
factor(year)2023                                                         0.12314
educ_cat_factor_refMedia incompleta o menos:movilidad_cat_factor.L       0.30949
educ_cat_factor_refTécnica superior incompleta:movilidad_cat_factor.L    0.44627
educ_cat_factor_refTécnica superior completa:movilidad_cat_factor.L      0.33430
educ_cat_factor_refUniversitaria incompleta:movilidad_cat_factor.L       0.34394
educ_cat_factor_refUniversitaria completa:movilidad_cat_factor.L         0.62263
educ_cat_factor_refPostgrado:movilidad_cat_factor.L                      1.19678
educ_cat_factor_refMedia incompleta o menos:movilidad_cat_factor.Q       0.26680
educ_cat_factor_refTécnica superior incompleta:movilidad_cat_factor.Q    0.37835
educ_cat_factor_refTécnica superior completa:movilidad_cat_factor.Q      0.29810
educ_cat_factor_refUniversitaria incompleta:movilidad_cat_factor.Q       0.32485
educ_cat_factor_refUniversitaria completa:movilidad_cat_factor.Q         0.48651
educ_cat_factor_refPostgrado:movilidad_cat_factor.Q                      0.96023
educ_cat_factor_refMedia incompleta o menos:movilidad_cat_factor.C       0.22013
educ_cat_factor_refTécnica superior incompleta:movilidad_cat_factor.C    0.29702
educ_cat_factor_refTécnica superior completa:movilidad_cat_factor.C      0.25717
educ_cat_factor_refUniversitaria incompleta:movilidad_cat_factor.C       0.30613
educ_cat_factor_refUniversitaria completa:movilidad_cat_factor.C              NA
educ_cat_factor_refPostgrado:movilidad_cat_factor.C                           NA
                                                                      z value
(Intercept)                                                             2.640
educ_cat_factor_refMedia incompleta o menos                            -4.638
educ_cat_factor_refTécnica superior incompleta                          1.669
educ_cat_factor_refTécnica superior completa                            1.815
educ_cat_factor_refUniversitaria incompleta                             3.322
educ_cat_factor_refUniversitaria completa                               0.546
educ_cat_factor_refPostgrado                                            1.197
movilidad_cat_factor.L                                                 -1.268
movilidad_cat_factor.Q                                                  1.223
movilidad_cat_factor.C                                                  0.072
edad                                                                  -13.807
mujer                                                                  -2.773
ideologia_std                                                         -14.820
interes_politica                                                       14.684
factor(year)2017                                                       -5.924
factor(year)2018                                                       -4.753
factor(year)2019                                                        5.405
factor(year)2021                                                      -10.583
factor(year)2022                                                       -6.388
factor(year)2023                                                       -8.753
educ_cat_factor_refMedia incompleta o menos:movilidad_cat_factor.L      0.652
educ_cat_factor_refTécnica superior incompleta:movilidad_cat_factor.L  -0.264
educ_cat_factor_refTécnica superior completa:movilidad_cat_factor.L     0.069
educ_cat_factor_refUniversitaria incompleta:movilidad_cat_factor.L     -1.174
educ_cat_factor_refUniversitaria completa:movilidad_cat_factor.L        1.890
educ_cat_factor_refPostgrado:movilidad_cat_factor.L                     1.371
educ_cat_factor_refMedia incompleta o menos:movilidad_cat_factor.Q     -0.193
educ_cat_factor_refTécnica superior incompleta:movilidad_cat_factor.Q  -0.729
educ_cat_factor_refTécnica superior completa:movilidad_cat_factor.Q     0.668
educ_cat_factor_refUniversitaria incompleta:movilidad_cat_factor.Q     -1.153
educ_cat_factor_refUniversitaria completa:movilidad_cat_factor.Q       -2.011
educ_cat_factor_refPostgrado:movilidad_cat_factor.Q                    -0.977
educ_cat_factor_refMedia incompleta o menos:movilidad_cat_factor.C      0.305
educ_cat_factor_refTécnica superior incompleta:movilidad_cat_factor.C   0.418
educ_cat_factor_refTécnica superior completa:movilidad_cat_factor.C     0.587
educ_cat_factor_refUniversitaria incompleta:movilidad_cat_factor.C     -0.425
educ_cat_factor_refUniversitaria completa:movilidad_cat_factor.C           NA
educ_cat_factor_refPostgrado:movilidad_cat_factor.C                        NA
                                                                                  Pr(&gt;|z|)
(Intercept)                                                                       0.008288
educ_cat_factor_refMedia incompleta o menos                                 0.000003511092
educ_cat_factor_refTécnica superior incompleta                                    0.095089
educ_cat_factor_refTécnica superior completa                                      0.069574
educ_cat_factor_refUniversitaria incompleta                                       0.000894
educ_cat_factor_refUniversitaria completa                                         0.585184
educ_cat_factor_refPostgrado                                                      0.231353
movilidad_cat_factor.L                                                            0.204973
movilidad_cat_factor.Q                                                            0.221409
movilidad_cat_factor.C                                                            0.942894
edad                                                                  &lt; 0.0000000000000002
mujer                                                                             0.005555
ideologia_std                                                         &lt; 0.0000000000000002
interes_politica                                                      &lt; 0.0000000000000002
factor(year)2017                                                            0.000000003133
factor(year)2018                                                            0.000002001313
factor(year)2019                                                            0.000000064724
factor(year)2021                                                      &lt; 0.0000000000000002
factor(year)2022                                                            0.000000000168
factor(year)2023                                                      &lt; 0.0000000000000002
educ_cat_factor_refMedia incompleta o menos:movilidad_cat_factor.L                0.514284
educ_cat_factor_refTécnica superior incompleta:movilidad_cat_factor.L             0.791682
educ_cat_factor_refTécnica superior completa:movilidad_cat_factor.L               0.945048
educ_cat_factor_refUniversitaria incompleta:movilidad_cat_factor.L                0.240225
educ_cat_factor_refUniversitaria completa:movilidad_cat_factor.L                  0.058760
educ_cat_factor_refPostgrado:movilidad_cat_factor.L                               0.170289
educ_cat_factor_refMedia incompleta o menos:movilidad_cat_factor.Q                0.847027
educ_cat_factor_refTécnica superior incompleta:movilidad_cat_factor.Q             0.465808
educ_cat_factor_refTécnica superior completa:movilidad_cat_factor.Q               0.504287
educ_cat_factor_refUniversitaria incompleta:movilidad_cat_factor.Q                0.248773
educ_cat_factor_refUniversitaria completa:movilidad_cat_factor.Q                  0.044328
educ_cat_factor_refPostgrado:movilidad_cat_factor.Q                               0.328335
educ_cat_factor_refMedia incompleta o menos:movilidad_cat_factor.C                0.760451
educ_cat_factor_refTécnica superior incompleta:movilidad_cat_factor.C             0.676001
educ_cat_factor_refTécnica superior completa:movilidad_cat_factor.C               0.557478
educ_cat_factor_refUniversitaria incompleta:movilidad_cat_factor.C                0.670533
educ_cat_factor_refUniversitaria completa:movilidad_cat_factor.C                        NA
educ_cat_factor_refPostgrado:movilidad_cat_factor.C                                     NA
                                                                         
(Intercept)                                                           ** 
educ_cat_factor_refMedia incompleta o menos                           ***
educ_cat_factor_refTécnica superior incompleta                        .  
educ_cat_factor_refTécnica superior completa                          .  
educ_cat_factor_refUniversitaria incompleta                           ***
educ_cat_factor_refUniversitaria completa                                
educ_cat_factor_refPostgrado                                             
movilidad_cat_factor.L                                                   
movilidad_cat_factor.Q                                                   
movilidad_cat_factor.C                                                   
edad                                                                  ***
mujer                                                                 ** 
ideologia_std                                                         ***
interes_politica                                                      ***
factor(year)2017                                                      ***
factor(year)2018                                                      ***
factor(year)2019                                                      ***
factor(year)2021                                                      ***
factor(year)2022                                                      ***
factor(year)2023                                                      ***
educ_cat_factor_refMedia incompleta o menos:movilidad_cat_factor.L       
educ_cat_factor_refTécnica superior incompleta:movilidad_cat_factor.L    
educ_cat_factor_refTécnica superior completa:movilidad_cat_factor.L      
educ_cat_factor_refUniversitaria incompleta:movilidad_cat_factor.L       
educ_cat_factor_refUniversitaria completa:movilidad_cat_factor.L      .  
educ_cat_factor_refPostgrado:movilidad_cat_factor.L                      
educ_cat_factor_refMedia incompleta o menos:movilidad_cat_factor.Q       
educ_cat_factor_refTécnica superior incompleta:movilidad_cat_factor.Q    
educ_cat_factor_refTécnica superior completa:movilidad_cat_factor.Q      
educ_cat_factor_refUniversitaria incompleta:movilidad_cat_factor.Q       
educ_cat_factor_refUniversitaria completa:movilidad_cat_factor.Q      *  
educ_cat_factor_refPostgrado:movilidad_cat_factor.Q                      
educ_cat_factor_refMedia incompleta o menos:movilidad_cat_factor.C       
educ_cat_factor_refTécnica superior incompleta:movilidad_cat_factor.C    
educ_cat_factor_refTécnica superior completa:movilidad_cat_factor.C      
educ_cat_factor_refUniversitaria incompleta:movilidad_cat_factor.C       
educ_cat_factor_refUniversitaria completa:movilidad_cat_factor.C         
educ_cat_factor_refPostgrado:movilidad_cat_factor.C                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                          GVIF Df GVIF^(1/(2*Df))
educ_cat_factor_ref   1.727404  6        1.046605
movilidad_cat_factor  1.226785  3        1.034653
edad                 47.947160  1        6.924389
edad_cuadratica      46.891377  1        6.847728
mujer                 1.013106  1        1.006532
ideologia_std         1.016119  1        1.008027
interes_politica      1.189939  1        1.090843
factor(year)          1.041250  6        1.003374</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-modelos_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="720"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-modelos_files/figure-html/unnamed-chunk-25-2.png" class="img-fluid figure-img" width="720"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Asymptotic one-sample Kolmogorov-Smirnov test

data:  simulationOutput$scaledResiduals
D = 0.0066959, p-value = 0.6541
alternative hypothesis: two-sided</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-modelos_files/figure-html/unnamed-chunk-25-3.png" class="img-fluid figure-img" width="720"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    DHARMa nonparametric dispersion test via sd of residuals fitted vs.
    simulated

data:  simulationOutput
dispersion = 0.98426, p-value = 0.346
alternative hypothesis: two.sided</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-modelos_files/figure-html/unnamed-chunk-25-4.png" class="img-fluid figure-img" width="720"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    DHARMa outlier test based on exact binomial test with approximate
    expectations

data:  sim_residuals
outliers at both margin(s) = 17, observations = 12018, p-value = 0.1826
alternative hypothesis: true probability of success is not equal to 0.001998002
95 percent confidence interval:
 0.0008242336 0.0022638604
sample estimates:
frequency of outliers (expected: 0.001998001998002 ) 
                                         0.001414545 </code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-modelos_files/figure-html/unnamed-chunk-25-5.png" class="img-fluid figure-img" width="720"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    DHARMa zero-inflation test via comparison to expected zeros with
    simulation under H0 = fitted model

data:  simulationOutput
ratioObsSim = 0.9928, p-value = 0.206
alternative hypothesis: two.sided</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-modelos_files/figure-html/unnamed-chunk-25-6.png" class="img-fluid figure-img" width="720"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-modelos_files/figure-html/unnamed-chunk-25-7.png" class="img-fluid figure-img" width="720"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="tablas-de-resultados" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="tablas-de-resultados"><span class="header-section-number">1.6</span> Tablas de Resultados</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-modelos_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="720"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="viitxwcqro" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#viitxwcqro table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#viitxwcqro thead, #viitxwcqro tbody, #viitxwcqro tfoot, #viitxwcqro tr, #viitxwcqro td, #viitxwcqro th {
  border-style: none;
}

#viitxwcqro p {
  margin: 0;
  padding: 0;
}

#viitxwcqro .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#viitxwcqro .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#viitxwcqro .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#viitxwcqro .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#viitxwcqro .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#viitxwcqro .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#viitxwcqro .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#viitxwcqro .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#viitxwcqro .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#viitxwcqro .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#viitxwcqro .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#viitxwcqro .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#viitxwcqro .gt_spanner_row {
  border-bottom-style: hidden;
}

#viitxwcqro .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#viitxwcqro .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#viitxwcqro .gt_from_md > :first-child {
  margin-top: 0;
}

#viitxwcqro .gt_from_md > :last-child {
  margin-bottom: 0;
}

#viitxwcqro .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#viitxwcqro .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#viitxwcqro .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#viitxwcqro .gt_row_group_first td {
  border-top-width: 2px;
}

#viitxwcqro .gt_row_group_first th {
  border-top-width: 2px;
}

#viitxwcqro .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#viitxwcqro .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#viitxwcqro .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#viitxwcqro .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#viitxwcqro .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#viitxwcqro .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#viitxwcqro .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#viitxwcqro .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#viitxwcqro .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#viitxwcqro .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#viitxwcqro .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#viitxwcqro .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#viitxwcqro .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#viitxwcqro .gt_left {
  text-align: left;
}

#viitxwcqro .gt_center {
  text-align: center;
}

#viitxwcqro .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#viitxwcqro .gt_font_normal {
  font-weight: normal;
}

#viitxwcqro .gt_font_bold {
  font-weight: bold;
}

#viitxwcqro .gt_font_italic {
  font-style: italic;
}

#viitxwcqro .gt_super {
  font-size: 65%;
}

#viitxwcqro .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#viitxwcqro .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#viitxwcqro .gt_indent_1 {
  text-indent: 5px;
}

#viitxwcqro .gt_indent_2 {
  text-indent: 10px;
}

#viitxwcqro .gt_indent_3 {
  text-indent: 15px;
}

#viitxwcqro .gt_indent_4 {
  text-indent: 20px;
}

#viitxwcqro .gt_indent_5 {
  text-indent: 25px;
}

#viitxwcqro .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#viitxwcqro div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-bootstrap="false">
<thead>
<tr class="gt_heading header">
<td colspan="5" class="gt_heading gt_title gt_font_normal">Modelos de Regresión Logística Multinivel</td>
</tr>
<tr class="gt_heading even">
<td colspan="5" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border">Variable dependiente: Participación en protestas (dummy)</td>
</tr>
<tr class="gt_col_headings header">
<th id="Variable" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Variable</th>
<th id="RE-Simple" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">RE Simple</th>
<th id="RE-Full-(H1)" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">RE Full (H1)</th>
<th id="RE-Aditivo" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">RE Aditivo</th>
<th id="RE-Interacción-(H2)" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">RE Interacción (H2)</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">Educación</td>
<td class="gt_row gt_center" headers="RE Simple"></td>
<td class="gt_row gt_center" headers="RE Full (H1)"></td>
<td class="gt_row gt_center" headers="RE Aditivo"></td>
<td class="gt_row gt_center" headers="RE Interacción (H2)"></td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">Media incompleta o menos</td>
<td class="gt_row gt_center" headers="RE Simple">-0.869***</td>
<td class="gt_row gt_center" headers="RE Full (H1)">-0.598***</td>
<td class="gt_row gt_center" headers="RE Aditivo">-0.610***</td>
<td class="gt_row gt_center" headers="RE Interacción (H2)">-0.637***</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">Universitaria incompleta</td>
<td class="gt_row gt_center" headers="RE Simple">1.432***</td>
<td class="gt_row gt_center" headers="RE Full (H1)">0.686***</td>
<td class="gt_row gt_center" headers="RE Aditivo">0.627***</td>
<td class="gt_row gt_center" headers="RE Interacción (H2)">0.553***</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">Universitaria completa</td>
<td class="gt_row gt_center" headers="RE Simple">1.069***</td>
<td class="gt_row gt_center" headers="RE Full (H1)">0.586***</td>
<td class="gt_row gt_center" headers="RE Aditivo">0.609***</td>
<td class="gt_row gt_center" headers="RE Interacción (H2)">0.135</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">Postgrado</td>
<td class="gt_row gt_center" headers="RE Simple">1.630***</td>
<td class="gt_row gt_center" headers="RE Full (H1)">0.986***</td>
<td class="gt_row gt_center" headers="RE Aditivo">0.994***</td>
<td class="gt_row gt_center" headers="RE Interacción (H2)">0.509</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">Movilidad (lineal)</td>
<td class="gt_row gt_center" headers="RE Simple"></td>
<td class="gt_row gt_center" headers="RE Full (H1)"></td>
<td class="gt_row gt_center" headers="RE Aditivo">-0.260*</td>
<td class="gt_row gt_center" headers="RE Interacción (H2)">-0.313</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">Edad</td>
<td class="gt_row gt_center" headers="RE Simple"></td>
<td class="gt_row gt_center" headers="RE Full (H1)">-0.044***</td>
<td class="gt_row gt_center" headers="RE Aditivo">-0.043***</td>
<td class="gt_row gt_center" headers="RE Interacción (H2)">-0.043***</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">Mujer</td>
<td class="gt_row gt_center" headers="RE Simple"></td>
<td class="gt_row gt_center" headers="RE Full (H1)">-0.205**</td>
<td class="gt_row gt_center" headers="RE Aditivo">-0.222**</td>
<td class="gt_row gt_center" headers="RE Interacción (H2)">-0.222**</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">Ideología (izq-der)</td>
<td class="gt_row gt_center" headers="RE Simple"></td>
<td class="gt_row gt_center" headers="RE Full (H1)">-0.214***</td>
<td class="gt_row gt_center" headers="RE Aditivo">-0.217***</td>
<td class="gt_row gt_center" headers="RE Interacción (H2)">-0.218***</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">Interés político</td>
<td class="gt_row gt_center" headers="RE Simple"></td>
<td class="gt_row gt_center" headers="RE Full (H1)">0.456***</td>
<td class="gt_row gt_center" headers="RE Aditivo">0.426***</td>
<td class="gt_row gt_center" headers="RE Interacción (H2)">0.427***</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable"></td>
<td class="gt_row gt_center" headers="RE Simple"></td>
<td class="gt_row gt_center" headers="RE Full (H1)"></td>
<td class="gt_row gt_center" headers="RE Aditivo"></td>
<td class="gt_row gt_center" headers="RE Interacción (H2)"></td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">N observaciones</td>
<td class="gt_row gt_center" headers="RE Simple">20,052</td>
<td class="gt_row gt_center" headers="RE Full (H1)">12,648</td>
<td class="gt_row gt_center" headers="RE Aditivo">12,018</td>
<td class="gt_row gt_center" headers="RE Interacción (H2)">12,018</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">AIC</td>
<td class="gt_row gt_center" headers="RE Simple">16,111.9</td>
<td class="gt_row gt_center" headers="RE Full (H1)">10,009.6</td>
<td class="gt_row gt_center" headers="RE Aditivo">9,697.8</td>
<td class="gt_row gt_center" headers="RE Interacción (H2)">9,712.4</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">BIC</td>
<td class="gt_row gt_center" headers="RE Simple">16,175.2</td>
<td class="gt_row gt_center" headers="RE Full (H1)">10,158.5</td>
<td class="gt_row gt_center" headers="RE Aditivo">9,853.0</td>
<td class="gt_row gt_center" headers="RE Interacción (H2)">9,986.0</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">SD efectos aleatorios</td>
<td class="gt_row gt_center" headers="RE Simple">1.430</td>
<td class="gt_row gt_center" headers="RE Full (H1)">1.370</td>
<td class="gt_row gt_center" headers="RE Aditivo">1.360</td>
<td class="gt_row gt_center" headers="RE Interacción (H2)">1.353</td>
</tr>
</tbody><tfoot>
<tr class="gt_footnotes odd">
<td colspan="5" class="gt_footnote">* p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td>
</tr>
<tr class="gt_sourcenotes even">
<td colspan="5" class="gt_sourcenote">Fuente: Elaboración propia con datos ELSOC (2016-2023)</td>
</tr>
</tfoot>

</table>

</div>
</div>
</div>
<p>Conclusiones principales:</p>
<ul>
<li>Modelo óptimo: RE Aditivo (menor AIC)</li>
<li>Hipótesis H2 rechazada: La interacción NO mejora el modelo</li>
<li>Efectos robustos: Educación, ideología e interés político son predictores consistentes</li>
<li>Movilidad social: Efecto lineal negativo en modelo aditivo</li>
<li>Mediación: Variables actitudinales median ~40-50% del efecto educativo</li>
</ul>
<p>Para evaluar la hipótesis H1 sobre el efecto de la educación, se estimó una serie de modelos logísticos multinivel. El Modelo 2 (RE Full) muestra que, controlando variables demográficas, actitudinales y temporales, la educación mantiene un efecto positivo robusto sobre la participación en protestas. El gradiente educativo es claro: desde un efecto negativo en educación media incompleta o menos (β = -0.598, p &lt; 0.001) hasta un efecto positivo máximo en postgrado (β = 0.986, p &lt; 0.001), pasando por niveles intermedios significativos en educación universitaria. La inclusión de ideología política e interés político (Modelo 3) reduce los coeficientes educativos aproximadamente 40-50% respecto al modelo demográfico básico (Modelo 2), sugiriendo mediación parcial por variables actitudinales. Sin embargo, los efectos educativos se mantienen significativos, indicando que la educación opera tanto directamente como a través de actitudes políticas.</p>
<p>Para evaluar la hipótesis H2 sobre movilidad social, se estimaron dos modelos adicionales: uno con efectos aditivos de educación y movilidad (Modelo 4) y otro con interacciones entre ambas (Modelo 5). El Modelo 4 muestra un efecto lineal negativo de la movilidad social (β = -0.260, p &lt; 0.05), consistente con la hipótesis de integración: mayor movilidad ascendente se asocia con menor participación en protestas, controlando nivel educativo alcanzado. El modelo con interacciones (Modelo 5) no mejora el ajuste respecto al modelo aditivo (ΔAIC = +14.6; ΔBIC = +133.0), y solo una de las 18 interacciones resulta significativa. Por tanto, se rechaza la hipótesis H2 de que el efecto de la educación varía según la trayectoria de movilidad social. Los datos apoyan un modelo donde educación y movilidad tienen efectos independientes y aditivos sobre la protesta.</p>
<p>En conclusión, el Modelo 4 (RE Aditivo) se adopta como modelo final por su balance óptimo entre ajuste estadístico, parsimonia y claridad interpretativa. Modelo final: RE Aditivo (Modelo 4/5 sin interacciones)</p>
<p>El rechazo de la hipótesis de interacción (H2) tiene implicaciones teóricas importantes. Sugiere que los efectos de la educación sobre la participación política son relativamente universales y no dependen críticamente de la trayectoria de movilidad social experimentada. Esto es consistente con teorías que enfatizan la educación como proveedora de recursos cívicos generales (Brady et al., 1995) más que como marcador de posiciones sociales particulares.</p>
<p>No obstante, el efecto independiente de la movilidad social (controlando educación alcanzada) indica que las trayectorias de ascenso o descenso tienen consecuencias propias. El efecto negativo de la movilidad ascendente sobre la protesta puede interpretarse desde teorías de integración social: quienes experimentan ascenso pueden desarrollar mayor identificación con el sistema, independientemente de su nivel educativo final.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-modelos_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="720"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-modelos_files/figure-html/unnamed-chunk-29-2.png" class="img-fluid figure-img" width="720"></p>
</figure>
</div>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>