<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.23">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>analisis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="04-analisis_files/libs/clipboard/clipboard.min.js"></script>
<script src="04-analisis_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="04-analisis_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="04-analisis_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="04-analisis_files/libs/quarto-html/popper.min.js"></script>
<script src="04-analisis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="04-analisis_files/libs/quarto-html/anchor.min.js"></script>
<link href="04-analisis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="04-analisis_files/libs/quarto-html/quarto-syntax-highlighting-1fe81d0376b2c50856e68e651e390326.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="04-analisis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="04-analisis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="04-analisis_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="04-analisis_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="04-analisis_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">



</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<section id="resultados" class="level1">
<h1>Resultados</h1>
<p>Este apartado presenta los resultados de los factores que moldean la justificación de la violencia en el contexto de la protesta social en Chile. Utilizando datos longitudinales de ELSOC (2016-2023), se analiza cómo la participación en manifestaciones modera el efecto del nivel educativo y la clase social en la justificación de la violencia ejercida tanto por manifestantes como por la policía.</p>
<section id="estadísticos-descriptivos" class="level2">
<h2 class="anchored" data-anchor-id="estadísticos-descriptivos">Estadísticos Descriptivos</h2>
<section id="justificación-de-violencia-por-nivel-educativo" class="level3">
<h3 class="anchored" data-anchor-id="justificación-de-violencia-por-nivel-educativo">Justificación de violencia por nivel educativo</h3>
<p>Los patrones observados en la <a href="#tbl-justificacion-educ" class="quarto-xref">Table&nbsp;1</a> muestran un patrón relevante. Entre quienes no participan en protestas, un mayor nivel educativo iría de la mano con una ligera reducción en la justificación de la violencia en manifestaciones, con medias que bajan de aproximadamente 1.90 a 1.80. Sin embargo, esta tendencia cambia para quienes sí participan: aquellos participantes con educación universitaria son, de hecho, quienes muestran los niveles más altos de justificación, alcanzando medias en torno a 2.10 y 2.20. Este efecto de la educación parece ser específico de la violencia en protestas, ya que, en contraste, la justificación de la violencia estatal exhibe un patrón mucho más estable, con una variación considerablemente menor entre los distintos niveles educativos.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-justificacion-educ" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-justificacion-educ-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Justificación de violencia según nivel educativo y participación en protestas
</figcaption>
<div aria-describedby="tbl-justificacion-educ-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-hover do-not-create-environment cell caption-top table-sm small">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th data-quarto-table-cell-role="th" style="text-align: center; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Viol. Protestas
</div></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Viol. Estatal
</div></th>
</tr>
<tr class="even">
<th style="text-align: left;" data-quarto-table-cell-role="th">Educación</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Participación</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">N</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Media</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">DE</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Media</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">DE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Media completa o menos</td>
<td style="text-align: left;">No participó</td>
<td style="text-align: center;">8139</td>
<td style="text-align: center;">1.65</td>
<td style="text-align: center;">0.79</td>
<td style="text-align: center;">1.87</td>
<td style="text-align: center;">1.02</td>
</tr>
<tr class="even">
<td style="text-align: left;">Media completa o menos</td>
<td style="text-align: left;">Participó</td>
<td style="text-align: center;">671</td>
<td style="text-align: center;">1.96</td>
<td style="text-align: center;">0.91</td>
<td style="text-align: center;">1.65</td>
<td style="text-align: center;">0.94</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Téc. sup.incompleta</td>
<td style="text-align: left;">No participó</td>
<td style="text-align: center;">448</td>
<td style="text-align: center;">1.63</td>
<td style="text-align: center;">0.74</td>
<td style="text-align: center;">1.93</td>
<td style="text-align: center;">1.03</td>
</tr>
<tr class="even">
<td style="text-align: left;">Téc. sup.incompleta</td>
<td style="text-align: left;">Participó</td>
<td style="text-align: center;">79</td>
<td style="text-align: center;">2.07</td>
<td style="text-align: center;">0.83</td>
<td style="text-align: center;">1.75</td>
<td style="text-align: center;">0.90</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Téc. sup.completa</td>
<td style="text-align: left;">No participó</td>
<td style="text-align: center;">2267</td>
<td style="text-align: center;">1.57</td>
<td style="text-align: center;">0.71</td>
<td style="text-align: center;">1.90</td>
<td style="text-align: center;">0.98</td>
</tr>
<tr class="even">
<td style="text-align: left;">Téc. sup.completa</td>
<td style="text-align: left;">Participó</td>
<td style="text-align: center;">446</td>
<td style="text-align: center;">1.96</td>
<td style="text-align: center;">0.89</td>
<td style="text-align: center;">1.59</td>
<td style="text-align: center;">0.82</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Univ. incompleta</td>
<td style="text-align: left;">No participó</td>
<td style="text-align: center;">739</td>
<td style="text-align: center;">1.70</td>
<td style="text-align: center;">0.76</td>
<td style="text-align: center;">1.89</td>
<td style="text-align: center;">0.97</td>
</tr>
<tr class="even">
<td style="text-align: left;">Univ. incompleta</td>
<td style="text-align: left;">Participó</td>
<td style="text-align: center;">292</td>
<td style="text-align: center;">2.08</td>
<td style="text-align: center;">0.90</td>
<td style="text-align: center;">1.52</td>
<td style="text-align: center;">0.77</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Univ. completa</td>
<td style="text-align: left;">No participó</td>
<td style="text-align: center;">2192</td>
<td style="text-align: center;">1.60</td>
<td style="text-align: center;">0.74</td>
<td style="text-align: center;">1.96</td>
<td style="text-align: center;">0.98</td>
</tr>
<tr class="even">
<td style="text-align: left;">Univ. completa</td>
<td style="text-align: left;">Participó</td>
<td style="text-align: center;">971</td>
<td style="text-align: center;">2.12</td>
<td style="text-align: center;">0.98</td>
<td style="text-align: center;">1.47</td>
<td style="text-align: center;">0.71</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Nota:</span></td>
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> Escala 1-5 donde 1 = Nunca se justifica y 5 = Siempre se justifica</td>
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="justificación-de-violencia-por-clase-social" class="level3">
<h3 class="anchored" data-anchor-id="justificación-de-violencia-por-clase-social">Justificación de violencia por clase social</h3>
<p>Cuando observamos la clase social, los resultados son igualmente llamativos. Como se aprecia en la <a href="#tbl-justificacion-clase" class="quarto-xref">Table&nbsp;2</a>, la clase trabajadora (Working class) que no participa en protestas parte de un nivel de justificación de la violencia en protestas más alto (~1.85) en comparación con la clase de servicio (Service class) (~1.75). Sin embargo, al participar, es la clase de servicio la que experimenta el incremento más pronunciado en la justificación, saltando de ~1.75 a un nivel cercano a 2.20. Este cambio diferencial resulta en una especie de convergencia: las diferencias iniciales observadas entre clases se reducen significativamente entre quienes participan activamente en protestas.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-justificacion-clase" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-justificacion-clase-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Justificación de violencia según clase social y participación en protestas
</figcaption>
<div aria-describedby="tbl-justificacion-clase-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-hover do-not-create-environment cell caption-top table-sm small">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th data-quarto-table-cell-role="th" style="text-align: center; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Viol. Protestas
</div></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Viol. Estatal
</div></th>
</tr>
<tr class="even">
<th style="text-align: left;" data-quarto-table-cell-role="th">Clase Social</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Participación</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">N</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Media</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">DE</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Media</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">DE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Service class (I+II)</td>
<td style="text-align: left;">No participó</td>
<td style="text-align: center;">1391</td>
<td style="text-align: center;">1.60</td>
<td style="text-align: center;">0.72</td>
<td style="text-align: center;">1.95</td>
<td style="text-align: center;">0.96</td>
</tr>
<tr class="even">
<td style="text-align: left;">Service class (I+II)</td>
<td style="text-align: left;">Participó</td>
<td style="text-align: center;">569</td>
<td style="text-align: center;">2.06</td>
<td style="text-align: center;">0.94</td>
<td style="text-align: center;">1.49</td>
<td style="text-align: center;">0.75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Intermediate class (III+IV)</td>
<td style="text-align: left;">No participó</td>
<td style="text-align: center;">4085</td>
<td style="text-align: center;">1.59</td>
<td style="text-align: center;">0.72</td>
<td style="text-align: center;">1.87</td>
<td style="text-align: center;">0.99</td>
</tr>
<tr class="even">
<td style="text-align: left;">Intermediate class (III+IV)</td>
<td style="text-align: left;">Participó</td>
<td style="text-align: center;">739</td>
<td style="text-align: center;">2.05</td>
<td style="text-align: center;">0.97</td>
<td style="text-align: center;">1.58</td>
<td style="text-align: center;">0.85</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Working class (V+VI+VII)</td>
<td style="text-align: left;">No participó</td>
<td style="text-align: center;">3878</td>
<td style="text-align: center;">1.70</td>
<td style="text-align: center;">0.81</td>
<td style="text-align: center;">1.86</td>
<td style="text-align: center;">0.99</td>
</tr>
<tr class="even">
<td style="text-align: left;">Working class (V+VI+VII)</td>
<td style="text-align: left;">Participó</td>
<td style="text-align: center;">572</td>
<td style="text-align: center;">1.99</td>
<td style="text-align: center;">0.89</td>
<td style="text-align: center;">1.55</td>
<td style="text-align: center;">0.83</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Nota:</span></td>
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> Escala 1-5 donde 1 = Nunca se justifica y 5 = Siempre se justifica</td>
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="distribución-de-participación-en-protestas" class="level3">
<h3 class="anchored" data-anchor-id="distribución-de-participación-en-protestas">Distribución de participación en protestas</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-participacion-distribucion" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-participacion-distribucion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04-analisis_files/figure-html/fig-participacion-distribucion-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-participacion-distribucion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Distribución de participación en protestas por educación y clase
</figcaption>
</figure>
</div>
</div>
</div>
<p>El gráfico de la <a href="#fig-participacion-distribucion" class="quarto-xref">Figure&nbsp;1</a> muestra la tendencia que tiene la educación y la clase sobre la participación. Primeramente, podemos ver que esta aumenta consistentemente con el nivel educativo, creciendo desde un ~15% entre quienes tienen secundaria incompleta hasta un ~25% para aquellos con educación universitaria completa. Por otro lado, la clase social también muestra una brecha: la clase servicios participa ligeramente más (~22%) en comparación con la clase trabajadora (~18%). Podríamos afirmar que esto es consistente con la tendencia por nivel educativo, considerando que la clase de servicios tiende a ser, asimismo, la que reporta los mayores niveles de educación. Esta implicancia es crucial, dado que los participantes y no-participantes difieren en su composición, los análisis de interacción resultan fundamentales para comprender correctamente los efectos.</p>
</section>
<section id="evolución-temporal-justificación-de-la-violencia-y-participación-en-protestas-2016-2023" class="level3">
<h3 class="anchored" data-anchor-id="evolución-temporal-justificación-de-la-violencia-y-participación-en-protestas-2016-2023">Evolución temporal: Justificación de la Violencia y Participación en protestas (2016-2023)</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-evolucion-temporal" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-evolucion-temporal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04-analisis_files/figure-html/fig-evolucion-temporal-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-evolucion-temporal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Evolución de justificación de violencia y participación en protestas 2016-2023
</figcaption>
</figure>
</div>
</div>
</div>
<p>El análisis de los patrones temporales de la <a href="#fig-evolucion-temporal" class="quarto-xref">Figure&nbsp;2</a> muestra un resultado coherente con el contexto del ciclo de protesta observado. Para el 2019 -año del estallido social- se registra el promedio más alto de justificación para ambos tipos de violencia, alcanzando aproximadamente 2.0 en la escala, marcando un punto de inflexión significativo respecto a los años anteriores.</p>
<p>Coherentemente con el contexto, la participación en protestas aumentó significativamente en 2019, reflejando la intensidad de la movilización. En el período post-2019, la justificación de la violencia disminuye hacia niveles similares a los pre-estallido, y aunque la participación también disminuye desde su punto álgido, se mantiene en niveles ligeramente superiores a los observados antes del 2019.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-participacion-estratificada" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-participacion-estratificada-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04-analisis_files/figure-html/fig-participacion-estratificada-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-participacion-estratificada-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Composición sociodemográfica de participantes en protestas por año: cambios estructurales post-estallido
</figcaption>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-participacion-estratificada" class="quarto-xref">Figure&nbsp;3</a> revela cambios estructurales críticos en la composición de los movimientos de protesta y en la divergencia de actitudes hacia distintos tipos de violencia. <strong>Panel A (Participación por Educación)</strong>: Antes de 2019, la participación era estratificada por educación, con universitarios completos mostrando tasas de ~20-25%, técnicos ~15-20%, y educación media ~10-15%, confirmando el sesgo de participación hacia sectores con mayor capital cultural documentado en la literatura de acción colectiva. En 2019, <strong>todas</strong> las categorías experimentan incrementos dramáticos, pero de magnitud diferencial: universitarios alcanzan ~50%, técnicos ~40%, y educación media ~35%. Crucialmente, en el post-2019 (2022-2023), la participación desciende pero <strong>no retorna a niveles pre-estallido</strong>: universitarios se estabilizan en ~30% (vs ~22% pre-2019), técnicos en ~25% (vs ~17%), y educación media en ~20% (vs ~12%). Esto evidencia un <strong>efecto permanente de movilización</strong>: el estallido no fue un spike temporal sino que generó incorporación duradera de nuevos sectores a la protesta. Además, la brecha educativa en participación se <strong>redujo</strong> post-2019: la diferencia universitarios-media era ~12 puntos pre-2019 y se redujo a ~10 puntos post-2019, sugiriendo democratización parcial del repertorio de protesta.</p>
<p>El patrón por clase social es aún más revelador. Pre-2019, Service class lideraba participación (~18-22%), seguida por Intermediate class (~15-18%) y Clase Trabajadora (~10-13%), reflejando barreras estructurales a la movilización (tiempo, recursos, redes). En 2019, Clase Trabajadora experimenta el incremento <strong>proporcional</strong> más dramático (de ~13% a ~45%, +32 puntos), superando temporalmente a Intermediate class (~42%) e igualando casi a Service class (~48%). Esto confirma que el estallido activó sectores tradicionalmente sub-representados, consistente con narrativas de “desborde popular”. Post-2019, la estratificación se <strong>reconstituyó parcialmente</strong> pero con niveles elevados: Service class ~28%, Intermediate ~25%, Trabajadora ~22%. La brecha clase alta-trabajadora se redujo de ~10 puntos pre-2019 a ~6 puntos post-2019. Este hallazgo es crítico para interpretar los modelos: el incremento en justificación de violencia entre participantes de alta educación/clase no ocurre en un contexto de elite aislada, sino en movimientos post-2019 <strong>más heterogéneos y populares</strong> donde interactúan sectores diversos, potenciando procesos de reenmarcamiento moral colectivo.</p>
<p>La divergencia entre justificación de ambos tipos de violencia revela la dinámica del marco moral dual. Pre-2019 (2016-2018), la brecha era <strong>mínima y fluctuante</strong> (±0.05 puntos), indicando que ambas formas de violencia se evaluaban con criterios similares: baja justificación generalizada (~1.6-1.7), reflejando consenso liberal-democrático. En <strong>2019</strong>, la brecha se <strong>invierte dramáticamente</strong>: cae a ~-0.15, es decir, violencia estatal fue justificada ~0.15 puntos <strong>más</strong> que violencia en protestas. Esto es contraintuitivo dado el contexto de represión masiva, pero refleja probablemente el shock inicial y la polarización: sectores conservadores justificaron más la represión ante el “caos” percibido. Sin embargo, en el <strong>post-2019</strong> (2022-2023), la brecha se <strong>revierte completamente</strong>: violencia en protestas es justificada ~0.10-0.15 puntos <strong>más</strong> que violencia estatal, y esta brecha se <strong>estabiliza</strong>. Este es el hallazgo más crítico: el estallido no solo generó un spike temporal sino una <strong>reconfiguración permanente de jerarquías morales</strong>: violencia táctica disruptiva es ahora más legitimada que represión estatal, invirtiendo la relación pre-2019. Este patrón macro valida la H2 de reconfiguración bidireccional: el marco moral dual no es meramente una diferencia entre individuos sino una estructura colectiva emergente post-estallido, donde violencia “desde abajo” se normaliza mientras violencia “desde arriba” se deslegitima selectivamente (entre participantes) o se normaliza (entre no participantes, como mostró fig-prepost-estallido).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-componentes-violencia" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-componentes-violencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04-analisis_files/figure-html/fig-componentes-violencia-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-componentes-violencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Evolución de componentes específicos de justificación de violencia
</figcaption>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-componentes-violencia" class="quarto-xref">Figure&nbsp;4</a> desagrega los índices en sus componentes disponibles en todas las olas. El Panel A muestra las dos formas de violencia en protestas medidas consistentemente: huelgas de trabajadores y tomas estudiantiles. Ambas presentan una tendencia ascendente hacia 2019, alcanzando su punto máximo ese año, seguido de un descenso en los años posteriores. En específico, podemos ver que las acciones disruptivas protagonizadas por trabajadores reciben una mayor justificación -en promedio- que las perpetradas por estudiantes a lo largo de todo el período.</p>
<p>El Panel B revela un patrón contrastante para la violencia estatal. Ambas formas de represión policial (en marchas y desalojos de tomas) muestran una caída pronunciada en 2019, alcanzando sus niveles más bajos de justificación precisamente en el año del estallido social. Sin embargo, en el período post-2019, se observa un aumento sostenido y marcado de la justificación de violencia policial, divergiendo claramente del patrón observado para la violencia en protestas que se mantiene en niveles más bajos.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-prepost-estallido" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-prepost-estallido-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04-analisis_files/figure-html/fig-prepost-estallido-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-prepost-estallido-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Comparación de justificación de violencia antes (2016-2018) y después (2022-2023) del estallido social por educación, clase y participación
</figcaption>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-prepost-estallido" class="quarto-xref">Figure&nbsp;5</a> compara los niveles de justificación de violencia antes (2016-2018) y después (2022-2023) del estallido social de octubre 2019, revelando patrones críticos sobre la permanencia de los efectos del shock político.</p>
<p>Entre <strong>no participantes</strong>, se observa un incremento generalizado post-2019 en todos los niveles educativos y clases sociales, aunque de magnitud variable. Los grupos de mayor educación (universitaria completa) incrementan justificación de ~1.5 a ~1.8, mientras que educación básica/media se mantiene relativamente estable (~1.8-2.0). La Service class muestra el incremento más pronunciado (~1.6 a ~1.9), sugiriendo que el estallido erosionó parcialmente el efecto civilizatorio incluso entre quienes no participaron directamente. Entre <strong>participantes</strong>, el patrón es más homogéneo: todos los grupos convergen hacia niveles moderadamente altos (~2.0-2.3) en el post-2019, con intervalos de confianza superpuestos, indicando que la experiencia de movilización iguala actitudes independientemente de capital cultural o posición estructural. Crucialmente, las brechas entre participantes y no participantes se <strong>mantienen</strong> en el periodo post-2019, evidenciando que el efecto de la participación no es meramente temporal sino que persiste años después del estallido.</p>
<p>El patrón es radicalmente distinto en los paneles siguientes. Entre <strong>no participantes</strong>, hay un incremento dramático en la justificación de violencia policial post-2019, especialmente visible en grupos de mayor educación (universitaria: ~1.3 a ~2.0) y Service class (~1.3 a ~1.9). Este es el hallazgo más crítico: el estallido no solo no generó rechazo permanente a la represión estatal, sino que normalizó su justificación incluso entre sectores privilegiados. Entre <strong>participantes</strong>, el patrón se invierte completamente: todos los grupos educativos y de clase muestran <strong>descensos</strong> en justificación post-2019 (de ~1.8-2.0 pre-2019 a ~1.5-1.7 post-2019), con la única excepción de universitarios completos que mantienen niveles bajos estables (~1.4). Esto confirma que la experiencia directa de represión durante el estallido generó un efecto de “deslegitimación experiencial” permanente entre manifestantes.</p>
<p>Los datos revelan que el estallido de 2019 <strong>no fue un shock temporal</strong> sino un <strong>punto de inflexión permanente</strong> que reconfiguró estructuralmente los marcos morales duales. La divergencia entre participantes y no participantes se amplifica en el post-2019: mientras participantes desarrollan rechazo duradero a violencia estatal pero mantienen justificación de violencia en protestas, no participantes experimentan el proceso inverso —mayor tolerancia a represión estatal y leve incremento en aceptación de violencia disruptiva—. Esto cristaliza la hipótesis de reconfiguración bidireccional: el estallido no homogeneizó actitudes sino que polarizó marcos morales en función de la experiencia de participación, y estos marcos permanecen estables 3-4 años después del evento crítico.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-distribuciones-violin" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-distribuciones-violin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04-analisis_files/figure-html/fig-distribuciones-violin-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-distribuciones-violin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Distribución de justificación de violencia en protestas por educación, clase y participación
</figcaption>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-distribuciones-violin" class="quarto-xref">Figure&nbsp;6</a> complementa las tablas descriptivas mostrando visualmente la distribución completa de justificación de violencia, no solo las medias. El Panel A (educación) revela varios patrones importantes. Primero, entre no participantes (violines rojos), los niveles educativos más altos muestran distribuciones más concentradas en valores bajos (~1.5-2.0), con medianas claramente descendentes, confirmando el efecto civilizatorio. Las distribuciones son relativamente simétricas y unimodales. Entre participantes (violines azules), las distribuciones se desplazan hacia arriba y se vuelven más dispersas, especialmente en educación universitaria, donde la distribución es más amplia (rango ~1.5-3.5) y bimodal, evidenciando la heterogeneidad capturada por los efectos aleatorios: algunos universitarios participantes mantienen baja justificación mientras otros la incrementan sustancialmente.</p>
<p>El Panel B (clase social) muestra patrones contrastantes. Entre no participantes, la Clase Trabajadora exhibe una distribución ligeramente desplazada hacia arriba (~1.8-2.2) comparada con Service class e Intermediate class (~1.6-2.0), consistente con la predisposición estructural. Entre participantes, ocurre una notable convergencia: las tres distribuciones se superponen casi completamente, con medianas muy similares (~2.0-2.2) y rangos intercuartiles comparables. Sin embargo, la Clase Trabajadora muestra una cola superior ligeramente más larga, indicando que aunque la mediana converge, algunos individuos de esta clase alcanzan los niveles más altos de justificación. Los boxplots internos confirman que los rangos intercuartiles se reducen dramáticamente entre participantes, evidenciando menor variabilidad dentro de grupos cuando están activamente movilizados, un hallazgo consistente con la hipótesis de “experiencia compartida” que iguala actitudes independientemente de la posición estructural.</p>
</section>
</section>
<section id="estadísticos-exploratorios" class="level2">
<h2 class="anchored" data-anchor-id="estadísticos-exploratorios">Estadísticos exploratorios</h2>
<section id="modelos-principales" class="level3">
<h3 class="anchored" data-anchor-id="modelos-principales">Modelos principales</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-diagnosticos-modelos" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-diagnosticos-modelos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04-analisis_files/figure-html/fig-diagnosticos-modelos-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-diagnosticos-modelos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Diagnósticos de los cuatro modelos principales: residuos, normalidad y efectos aleatorios
</figcaption>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-diagnosticos-modelos" class="quarto-xref">Figure&nbsp;7</a> presenta tres evaluaciones críticas de la validez de los modelos principales. <strong>Panel A (Residuos vs Valores Ajustados)</strong>: Los cuatro modelos muestran patrones residuales satisfactorios. Las líneas suavizadas (amarillas) se mantienen cercanas a cero a lo largo del rango de valores ajustados, indicando que no hay evidencia de no-linealidad sistemática en las relaciones modeladas. La dispersión vertical es relativamente constante (homocedasticidad), aunque se observa una leve mayor variabilidad en valores extremos, típico en modelos de efectos mixtos. Los modelos H1 y H3a (violencia en protestas) presentan dispersión ligeramente mayor que H2 y H3b (violencia estatal), consistente con mayor heterogeneidad en actitudes hacia violencia disruptiva. No se detectan patrones en forma de embudo o curvaturas pronunciadas que sugieran problemas de especificación.</p>
<p>Los gráficos cuantil-cuantil revelan que los residuos se aproximan razonablemente a distribución normal en los cuatro modelos. Los puntos siguen la línea de referencia roja en la región central, con desviaciones menores en las colas —particularmente cola derecha (valores extremos altos)—, indicando leve asimetría positiva residual. Este patrón es esperable dado que la variable dependiente (escala 1-5) tiene límite superior natural, generando “ceiling effects” leves. Crucialmente, las desviaciones no son severas y no comprometen la inferencia: los estimadores glmmTMB son robustos a desviaciones moderadas de normalidad cuando el tamaño muestral es grande (n&gt;10,000 observaciones en nuestro caso). La similitud de patrones entre modelos confirma consistencia en la calidad de ajuste.</p>
<p>Los interceptos aleatorios por individuo muestran distribuciones aproximadamente normales centradas en cero para los cuatro modelos, validando el supuesto clave de efectos aleatorios. La varianza de estos interceptos (~SD = 0.35-0.40) es sustancial, confirmando heterogeneidad individual significativa en niveles base de justificación (ICC ~0.23-0.24 reportado previamente). Los modelos de violencia en protestas (H1 y H3a, amarillo y morado) presentan dispersión ligeramente mayor que los de violencia estatal (H2 y H3b, azul y cian), consistente con mayor polarización individual en actitudes hacia acción disruptiva. No se observan valores extremos o multimodalidad que sugieran subpoblaciones ocultas. Esta estructura de efectos aleatorios justifica plenamente la especificación multinivel: ignorar esta heterogeneidad individual generaría errores estándar subestimados y conclusiones inferenciales erróneas. La distribución normal de efectos aleatorios también indica que el modelo captura adecuadamente la estructura de dependencia intra-individual sin necesidad de especificaciones más complejas (e.g., pendientes aleatorias).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-robustez-sensibilidad" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-robustez-sensibilidad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04-analisis_files/figure-html/fig-robustez-sensibilidad-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-robustez-sensibilidad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Análisis de robustez y sensibilidad: modelos alternativos y exclusión de 2019
</figcaption>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-robustez-sensibilidad" class="quarto-xref">Figure&nbsp;8</a> presenta tres evaluaciones críticas de la robustez de los hallazgos principales. <strong>Panel A (Efectos Fijos vs Aleatorios)</strong>: La comparación revela que los modelos de efectos fijos (OLS con dummies de año, ignorando estructura longitudinal) <strong>subestiman consistentemente los errores estándar</strong> de las interacciones clave. Los intervalos de confianza en efectos fijos (amarillo) son sistemáticamente más estrechos que en efectos aleatorios (azul), generando inferencia anti-conservadora: varios términos de interacción aparecen “significativos” en efectos fijos pero sus ICs se superponen más con cero al corregir por dependencia intra-individual. Crucialmente, las <strong>magnitudes puntuales</strong> de los coeficientes son muy similares entre especificaciones (diferencias &lt;0.05 puntos), indicando que el sesgo de estimación puntual es mínimo. El problema principal de efectos fijos es la <strong>inflación de precisión</strong>: asume observaciones independientes cuando en realidad individuos contribuyen múltiples olas, violando supuesto de IID. Los efectos aleatorios corrigen esto modelando explícitamente la correlación intra-individual (ICC ~0.23), produciendo SEs ~15-20% mayores pero inferencialmente correctos. Este análisis valida la decisión de usar glmmTMB multinivel: la estructura longitudinal de ELSOC requiere efectos aleatorios para inferencia válida, pero los hallazgos sustantivos (direcciones y magnitudes) son robustos a especificación.</p>
<p>Excluir el año del estallido social (2019) es la prueba más crítica: si las interacciones fueran meros artefactos del shock de 2019, deberían desaparecer al remover ese año. Los resultados demuestran <strong>robustez sustantiva</strong>: todas las interacciones clave persisten con magnitudes y significancia similares. En H1, la interacción Univ. completa × Participación es +0.13 en dataset completo vs +0.12 sin 2019 (diferencia &lt;0.01); en H3a, Clase Trabajadora × Participación es +0.11 vs +0.10. Los intervalos de confianza se superponen casi completamente, indicando que 2019 <strong>no es el único driver</strong> de los efectos sino que amplifica patrones presentes en todo el periodo 2016-2023. El efecto de participación (término principal) también permanece estable: +0.27 vs +0.25 en H1, +0.36 vs +0.33 en H3a. Esto confirma que las interacciones educación/clase × participación no son contingentes al momento del estallido sino estructuras relacionales persistentes: la educación superior amplifica el efecto de participación tanto en años “normales” como en el pico de movilización. Este hallazgo refuerza la interpretación teórica: el reenmarcamiento moral no es meramente reactivo a eventos coyunturales sino que refleja mecanismos sociocognitivos duraderos donde capital cultural interactúa con experiencia de movilización para reconfigurar actitudes.</p>
<p>La comparación revela cómo el estallido de 2019 <strong>modula pero no crea</strong> los efectos de interacción. En modelos estimados solo con datos de 2019 (verde), las interacciones son consistentemente <strong>más fuertes</strong> que en el periodo completo (rojo): en H1, Univ. completa × Participación es +0.18 en 2019 vs +0.13 en periodo completo; en H3a, Clase Trabajadora × Participación es +0.16 vs +0.11. Sin embargo, crucialmente, las <strong>direcciones</strong> son idénticas y los ICs se superponen parcialmente, indicando que 2019 representa una <strong>intensificación cuantitativa</strong> de patrones preexistentes, no una ruptura cualitativa. El efecto principal de participación también se amplifica en 2019 (+0.35-0.40 vs +0.27-0.36 periodo completo), consistente con mayor polarización y activación de marcos morales duales durante el pico de movilización. Este patrón sugiere que el estallido actuó como <strong>coyuntura crítica</strong> que temporalmente magnificó procesos relacionales latentes: la educación superior y la clase social siempre moderaron el efecto de participación, pero 2019 elevó las apuestas y la intensidad experiencial, amplificando tanto la justificación base como las interacciones. Post-2019, los efectos se moderan pero no desaparecen (Panel B), evidenciando que el shock dejó sedimentos permanentes en la estructura de actitudes. En conjunto, los tres paneles validan que los hallazgos no son artefactos metodológicos ni contingentes a un año específico, sino patrones robustos que atraviesan especificaciones y subperiodos.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-modelos-principales" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-modelos-principales-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Modelos principales de justificación de violencia
</figcaption>
<div aria-describedby="tbl-modelos-principales-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed do-not-create-environment cell caption-top table-sm small">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Educación
</div></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Clase
</div></th>
</tr>
<tr class="even">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;H1: Violencia en Protestas</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;H2: Violencia Estatal</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;H3a: Clase × Protesta</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;H3b: Clase x Estatal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercepto</td>
<td style="text-align: center;">2.39***</td>
<td style="text-align: center;">1.59***</td>
<td style="text-align: center;">2.27***</td>
<td style="text-align: center;">1.65***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.04)</td>
<td style="text-align: center;">(0.05)</td>
<td style="text-align: center;">(0.05)</td>
<td style="text-align: center;">(0.06)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">educ_cat_unorderedTéc. sup.incompleta</td>
<td style="text-align: center;">-0.13*</td>
<td style="text-align: center;">0.10</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.05)</td>
<td style="text-align: center;">(0.06)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">educ_cat_unorderedTéc. sup.completa</td>
<td style="text-align: center;">-0.13***</td>
<td style="text-align: center;">0.03</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.03)</td>
<td style="text-align: center;">(0.03)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Univ. inc.</td>
<td style="text-align: center;">-0.07</td>
<td style="text-align: center;">0.04</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.04)</td>
<td style="text-align: center;">(0.05)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Univ. comp.</td>
<td style="text-align: center;">-0.13***</td>
<td style="text-align: center;">0.06</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.03)</td>
<td style="text-align: center;">(0.03)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Protesta</td>
<td style="text-align: center;">0.27***</td>
<td style="text-align: center;">-0.04</td>
<td style="text-align: center;">0.39***</td>
<td style="text-align: center;">-0.20***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.03)</td>
<td style="text-align: center;">(0.04)</td>
<td style="text-align: center;">(0.04)</td>
<td style="text-align: center;">(0.05)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Edad</td>
<td style="text-align: center;">-0.01***</td>
<td style="text-align: center;">0.00***</td>
<td style="text-align: center;">-0.01***</td>
<td style="text-align: center;">0.00**</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.00)</td>
<td style="text-align: center;">(0.00)</td>
<td style="text-align: center;">(0.00)</td>
<td style="text-align: center;">(0.00)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mujer</td>
<td style="text-align: center;">-0.03</td>
<td style="text-align: center;">-0.13***</td>
<td style="text-align: center;">-0.01</td>
<td style="text-align: center;">-0.15***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.02)</td>
<td style="text-align: center;">(0.02)</td>
<td style="text-align: center;">(0.02)</td>
<td style="text-align: center;">(0.02)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ideología</td>
<td style="text-align: center;">-0.03***</td>
<td style="text-align: center;">0.05***</td>
<td style="text-align: center;">-0.04***</td>
<td style="text-align: center;">0.06***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.00)</td>
<td style="text-align: center;">(0.00)</td>
<td style="text-align: center;">(0.00)</td>
<td style="text-align: center;">(0.00)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2017</td>
<td style="text-align: center;">-0.04</td>
<td style="text-align: center;">-0.11***</td>
<td style="text-align: center;">-0.04</td>
<td style="text-align: center;">-0.07*</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.02)</td>
<td style="text-align: center;">(0.03)</td>
<td style="text-align: center;">(0.03)</td>
<td style="text-align: center;">(0.03)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2018</td>
<td style="text-align: center;">-0.11***</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">-0.09***</td>
<td style="text-align: center;">0.04</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.02)</td>
<td style="text-align: center;">(0.02)</td>
<td style="text-align: center;">(0.03)</td>
<td style="text-align: center;">(0.03)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2019</td>
<td style="text-align: center;">0.05*</td>
<td style="text-align: center;">-0.40***</td>
<td style="text-align: center;">0.07*</td>
<td style="text-align: center;">-0.36***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.02)</td>
<td style="text-align: center;">(0.02)</td>
<td style="text-align: center;">(0.03)</td>
<td style="text-align: center;">(0.03)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2022</td>
<td style="text-align: center;">-0.10***</td>
<td style="text-align: center;">-0.13***</td>
<td style="text-align: center;">-0.09**</td>
<td style="text-align: center;">-0.10**</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.02)</td>
<td style="text-align: center;">(0.03)</td>
<td style="text-align: center;">(0.03)</td>
<td style="text-align: center;">(0.03)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2023</td>
<td style="text-align: center;">-0.10***</td>
<td style="text-align: center;">-0.00</td>
<td style="text-align: center;">-0.07**</td>
<td style="text-align: center;">-0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.02)</td>
<td style="text-align: center;">(0.03)</td>
<td style="text-align: center;">(0.03)</td>
<td style="text-align: center;">(0.03)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">educ_cat_unorderedTéc. sup.incompleta:protesta_dummy</td>
<td style="text-align: center;">0.28*</td>
<td style="text-align: center;">0.02</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.11)</td>
<td style="text-align: center;">(0.13)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">educ_cat_unorderedTéc. sup.completa:protesta_dummy</td>
<td style="text-align: center;">0.13*</td>
<td style="text-align: center;">-0.06</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.06)</td>
<td style="text-align: center;">(0.06)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Univ. inc. × Prot.</td>
<td style="text-align: center;">0.11</td>
<td style="text-align: center;">-0.16*</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.07)</td>
<td style="text-align: center;">(0.08)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Univ. comp. × Prot.</td>
<td style="text-align: center;">0.13**</td>
<td style="text-align: center;">-0.18***</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.05)</td>
<td style="text-align: center;">(0.05)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">egp3Intermediate class (III+IV)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">-0.01</td>
<td style="text-align: center;">-0.03</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(0.03)</td>
<td style="text-align: center;">(0.03)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">egp3Working class (V+VI+VII)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.09**</td>
<td style="text-align: center;">-0.05</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(0.03)</td>
<td style="text-align: center;">(0.03)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">egp3Intermediate class (III+IV):protesta_dummy</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.03</td>
<td style="text-align: center;">0.09</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(0.05)</td>
<td style="text-align: center;">(0.06)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">egp3Working class (V+VI+VII):protesta_dummy</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">-0.13*</td>
<td style="text-align: center;">0.07</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(0.06)</td>
<td style="text-align: center;">(0.06)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SD (Intercept idencuesta)</td>
<td style="text-align: center;">0.36</td>
<td style="text-align: center;">0.44</td>
<td style="text-align: center;">0.36</td>
<td style="text-align: center;">0.45</td>
</tr>
<tr class="even">
<td style="text-align: left; box-shadow: 0px 1.5px;">SD (Observations)</td>
<td style="text-align: center; box-shadow: 0px 1.5px;">0.74</td>
<td style="text-align: center; box-shadow: 0px 1.5px;">0.84</td>
<td style="text-align: center; box-shadow: 0px 1.5px;">0.74</td>
<td style="text-align: center; box-shadow: 0px 1.5px;">0.82</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Num.Obs.</td>
<td style="text-align: center;">15110</td>
<td style="text-align: center;">15103</td>
<td style="text-align: center;">10462</td>
<td style="text-align: center;">10459</td>
</tr>
<tr class="even">
<td style="text-align: left;">AIC</td>
<td style="text-align: center;">36291.9</td>
<td style="text-align: center;">40370.3</td>
<td style="text-align: center;">25087.9</td>
<td style="text-align: center;">27526.7</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>La <a href="#tbl-modelos-principales" class="quarto-xref">Table&nbsp;3</a> presenta los cuatro modelos principales que guían el análisis de este estudio. Los modelos H1 y H2 examinan la interacción entre educación y participación en protestas para dos tipos de violencia (en protestas y estatal), mientras que los modelos H3a y H3b analizan la interacción entre clase social y participación para ambos tipos de violencia. Todos los modelos incluyen efectos aleatorios por individuo y controles por edad, género, ideología y año.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-coeficientes-comparacion" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-coeficientes-comparacion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04-analisis_files/figure-html/fig-coeficientes-comparacion-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-coeficientes-comparacion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Comparación de coeficientes entre los cuatro modelos principales
</figcaption>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-coeficientes-comparacion" class="quarto-xref">Figure&nbsp;9</a> presenta visualmente la comparación de coeficientes entre los cuatro modelos principales, facilitando la identificación de patrones contrastantes. El gráfico revela varios hallazgos clave. Primero, el efecto de la participación (panel superior) es consistentemente positivo para violencia en protestas (H1 y H3a: ~+0.27 y +0.36) pero cercano a cero o negativo para violencia estatal (H2 y H3b), confirmando la reconfiguración bidireccional. Segundo, los efectos principales de educación y clase (segundo panel) muestran el efecto civilizatorio para protestas pero no para violencia estatal. Tercero, las interacciones (tercer panel) son positivas en modelos de protestas (amplificando el efecto de participación) pero negativas en modelos de violencia estatal (generando rechazo diferenciado), cristalizando el marco moral dual. Los controles (panel inferior) operan de manera similar entre modelos, con ideología de derecha reduciendo justificación de violencia en protestas pero incrementándola para violencia estatal, evidenciando consistencia ideológica en las actitudes hacia el uso de la fuerza.</p>
</section>
<section id="el-efecto-paradoja-de-la-educación" class="level3">
<h3 class="anchored" data-anchor-id="el-efecto-paradoja-de-la-educación">El “Efecto Paradoja” de la Educación</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-interaccion-simple" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-interaccion-simple-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04-analisis_files/figure-html/fig-interaccion-simple-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-interaccion-simple-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Interacción simple educación × participación: líneas cruzadas mostrando inversión del efecto educativo
</figcaption>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-interaccion-simple" class="quarto-xref">Figure&nbsp;10</a> visualiza directamente el “efecto paradoja” mediante líneas cruzadas que revelan la inversión del efecto educativo según participación. Entre <strong>no participantes</strong> (línea roja), se observa una pendiente descendente clara: la justificación de violencia disminuye de ~1.95 en educación media a ~1.65 en universitaria completa, una reducción de 0.30 puntos (~15% de la escala). Este patrón confirma el <strong>efecto civilizatorio clásico</strong>: mayor educación formal reduce la tolerancia a violencia política entre observadores externos, consistente con teorías de socialización normativa que enfatizan internalización de valores democráticos liberales.</p>
<p>Sin embargo, entre <strong>participantes</strong> (línea azul), el patrón se invierte completamente: la justificación <strong>aumenta</strong> de ~2.10 en educación media a ~2.30 en universitaria completa, un incremento de 0.20 puntos. Crucialmente, las dos líneas se cruzan aproximadamente en el nivel de educación técnica superior, marcando el punto donde el efecto educativo cambia de signo. Este cruce visual es la manifestación gráfica de la interacción estadísticamente significativa reportada en los modelos: la educación superior no solo anula su efecto civilizatorio entre participantes, sino que lo revierte, convirtiéndose en <strong>amplificador de justificación</strong>.</p>
<p>El patrón de cruce contradice explicaciones alternativas simples. Si la participación simplemente “elevara” la justificación por igual en todos los niveles educativos (efecto aditivo puro), las líneas serían paralelas. Si el efecto civilizatorio solo se “debilitara” entre participantes, la línea azul sería más plana pero no ascendente. El cruce observado indica un proceso más complejo de <strong>reenmarcamiento moral</strong>: la educación superior proporciona recursos cognitivos (pensamiento crítico, cuestionamiento de autoridad) que, contextualizados por la experiencia de movilización, reinterpretan la violencia táctica como legítima resistencia contra injusticia estructural. Este hallazgo es central para la H1: la educación no opera de forma unívoca sobre actitudes políticas, sino que su efecto depende críticamente de la posición del sujeto respecto a la acción colectiva.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-slopes-educacion" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-slopes-educacion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04-analisis_files/figure-html/fig-slopes-educacion-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-slopes-educacion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Pendientes del efecto de participación por nivel educativo: magnitud diferencial de la experiencia de movilización
</figcaption>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-slopes-educacion" class="quarto-xref">Figure&nbsp;11</a> complementa el gráfico de líneas cruzadas visualizando la <strong>magnitud del efecto de participación</strong> en cada nivel educativo, revelando heterogeneidad sustantiva en cómo la experiencia de movilización transforma actitudes. Las barras representan la diferencia en justificación entre participantes y no participantes (pendientes implícitas de la interacción), con todas las diferencias siendo positivas —confirmando que participación siempre incrementa justificación— pero con magnitudes que varían sistemáticamente por nivel educativo.</p>
<p>El efecto de participación es <strong>menor</strong> en educación media (slope = +0.15, CI: [0.05, 0.25]), sugiriendo que individuos con menos educación formal experimentan un incremento más modesto en justificación al participar, posiblemente porque parten de niveles base ya relativamente altos (~1.95) y tienen menos “espacio” para incrementar en la escala, o porque la participación no requiere reenmarcamiento moral tan profundo dado que su socialización previa no enfatizó tanto el rechazo normativo a la violencia.</p>
<p>En contraste, el efecto de participación es <strong>mayor y creciente</strong> en niveles educativos altos: educación técnica superior muestra slopes de +0.25 a +0.35, mientras que universitaria completa alcanza +0.35 (CI: [0.22, 0.48]). Este patrón confirma que la educación superior <strong>amplifica</strong> el impacto transformador de la participación. Los universitarios no solo incrementan más su justificación al participar, sino que este incremento representa un cambio cualitativo más dramático dado que partían de los niveles más bajos entre no participantes (~1.65).</p>
<p>Este hallazgo tiene implicaciones teóricas críticas: la participación política no es un “tratamiento” homogéneo sino una experiencia cuyo efecto depende del capital cultural previo. Los recursos cognitivos provistos por educación superior —pensamiento crítico, exposición a narrativas contra-hegemónicas— actúan como <strong>catalizadores</strong> que magnifican el reenmarcamiento moral inducido por la experiencia de movilización. Esto resuelve la aparente paradoja: no es que la educación “falle” en su efecto civilizatorio entre participantes, sino que proporciona herramientas que, en contexto de activismo, reinterpretan la violencia táctica como legítima. La educación no determina unívocamente actitudes sino que provee marcos interpretativos cuya activación depende de la posición experiencial del sujeto.</p>
<p>El gráfico <a href="#fig-paradoja-educacion" class="quarto-xref">Figure&nbsp;12</a> revela patrones complejos de moderación educativa sobre la justificación de violencia en protestas.</p>
<p>Entre quienes no han participado en protestas, la mayoría de los niveles de educación superior muestran efectos negativos significativos comparados con educación media completa o menos (categoría de referencia). La educación técnica superior incompleta reduce la justificación en -0.13 (p&lt;0.05), la técnica completa en -0.13 (p&lt;0.001), y la universitaria completa en -0.13 (p&lt;0.001). La universitaria incompleta muestra un efecto menor y no significativo (-0.07). Esto confirma un “efecto civilizatorio” de la educación técnica y universitaria completa: mayor credencialización se asocia con menor justificación de violencia entre observadores externos.</p>
<p>Por otro lado, la participación en protestas incrementa significativamente la justificación de violencia (+0.27, p&lt;0.001) para el grupo de referencia (educación media o menos), un efecto sustantivo considerable.</p>
<p>En cuanto a los términos de interacción, son todos positivos, revelando que la educación superior <strong>magnifica</strong> el efecto de la participación, aunque con magnitudes diferentes. La técnica superior incompleta muestra la interacción más fuerte (+0.28, p&lt;0.05), seguida por técnica completa y universitaria completa (ambas +0.13, p&lt;0.05 y p&lt;0.01 respectivamente), mientras que universitaria incompleta no alcanza significancia estadística (+0.11, ns). Calculando el efecto total para universitarios completos participantes: -0.13 (efecto principal) + 0.27 (participación) + 0.13 (interacción) = <strong>+0.27</strong>. Esto implica que los universitarios completos que protestan justifican la violencia al mismo nivel que el grupo de referencia con educación media, anulando completamente el efecto civilizatorio inicial.</p>
<p>Ahora, el año 2019 muestra un coeficiente positivo (+0.05, p&lt;0.05), consistente con el contexto del estallido social. Esto sugiere que, controlando por educación y participación, 2019 tuvo mayor justificación relativa. Los otros años post-2016 muestran coeficientes negativos (2018: -0.11<strong><em>, 2022 y 2023: -0.10</em></strong>), indicando una tendencia general descendente, mientras 2017 no difiere significativamente del año base.</p>
<p>Finalmente, podemos ver que controles como la edad reduce la justificación (-0.01, p&lt;0.001), la ideología de derecha también la reduce (-0.03, p&lt;0.001), mientras que el género (mujer) no tiene efecto significativo (-0.03, ns). El modelo muestra una varianza del intercepto aleatorio de 0.13, indicando heterogeneidad sustancial entre individuos en sus niveles base de justificación.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-paradoja-educacion" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-paradoja-educacion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04-analisis_files/figure-html/fig-paradoja-educacion-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-paradoja-educacion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: Efecto paradójico de la educación según participación en protestas
</figcaption>
</figure>
</div>
</div>
</div>
<p>Tanto el modelo H1 (ver <a href="#tbl-modelos-principales" class="quarto-xref">Table&nbsp;3</a>) como el gráfico <a href="#fig-paradoja-educacion" class="quarto-xref">Figure&nbsp;12</a> sugieren que la educación reduce la justificación de violencia solo entre observadores externos. Entre participantes, la educación se asocia con <strong>mayor</strong> justificación, posiblemente porque personas más educadas elaboran marcos ideológicos que legitiman la violencia táctica en contextos de movilización.</p>
</section>
<section id="evolución-temporal-del-efecto-paradoja" class="level3">
<h3 class="anchored" data-anchor-id="evolución-temporal-del-efecto-paradoja">Evolución temporal del efecto paradoja</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-tendencias-educacion-tiempo" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tendencias-educacion-tiempo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04-analisis_files/figure-html/fig-tendencias-educacion-tiempo-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tendencias-educacion-tiempo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13: Evolución temporal del efecto de educación según participación (2016-2023)
</figcaption>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-tendencias-educacion-tiempo" class="quarto-xref">Figure&nbsp;13</a> desagrega temporalmente el efecto paradoja de la educación, aprovechando la estructura longitudinal de ELSOC. El Panel A confirma que el efecto civilizatorio entre no participantes se mantiene <strong>notablemente estable</strong> a lo largo del período 2016-2023: las personas con mayor educación consistentemente justifican menos la violencia, y esta brecha persiste incluso durante el estallido social de 2019.</p>
<p>El Panel B revela patrones más complejos entre participantes. Durante el período pre-estallido (2016-2018), se observa una <strong>mayor dispersión</strong> entre niveles educativos, con universitarios mostrando niveles de justificación variables. Sin embargo, en 2019 (año del estallido), ocurre una <strong>convergencia pronunciada</strong>: todos los grupos educativos que participan alcanzan niveles similares de justificación (~2.1-2.2), sugiriendo que la intensidad de la movilización masiva “iguala” temporalmente las diferencias educativas. En el período post-2019, esta convergencia se mantiene parcialmente, aunque con mayor variabilidad.</p>
<p>Este análisis temporal revela que el efecto paradoja no es constante: mientras el efecto civilizatorio es estable, la anulación de este efecto entre participantes es más pronunciada durante períodos de alta movilización. La varianza entre individuos (capturada por los efectos aleatorios) permite que algunos universitarios participantes mantengan niveles bajos de justificación, mientras otros la incrementan sustancialmente, generando la convergencia observada a nivel agregado.</p>
</section>
</section>
</section>
<section id="reconfiguración-bidireccional-de-la-justificación-de-la-violencia-violencia-en-protestas-vs-violencia-estatal" class="level1">
<h1>Reconfiguración Bidireccional de la justificación de la violencia (Violencia en Protestas vs Violencia Estatal)</h1>
<p>Los resultados de ambos modelos (H1 y H2) en la <a href="#tbl-modelos-principales" class="quarto-xref">Table&nbsp;3</a> revelan patrones contrastantes que confirman la hipótesis de reconfiguración bidireccional.</p>
<p>El patrón es claro: la educación universitaria completa reduce la justificación entre no participantes (-0.13, p&lt;0.001), pero la participación genera un fuerte incremento (+0.27, p&lt;0.001) que es magnificado por las interacciones positivas con educación superior (técnica superior incompleta: +0.28<em>, técnica completa y universitaria completa: +0.13</em> y +0.13**, respectivamente). El efecto total para universitarios participantes anula completamente el efecto civilizatorio.</p>
<p>Por otro lado, para la violencia estatal, la participación invierte el patrón de forma reveladora. Primero, la educación superior <strong>no muestra</strong> efectos significativos entre no participantes (todos los coeficientes entre +0.03 y +0.10, no significativos), indicando que la educación no genera una postura crítica hacia la represión policial per sé. Segundo, la participación baseline tampoco muestra efecto significativo (-0.04, no significativo).</p>
<p>Sin embargo, crucialmente, las interacciones negativas sugieren que universitarios incompletos participantes reducen su justificación en -0.16 (p&lt;0.05) y universitarios completos en -0.18 (p&lt;0.001). Esto significa que solo la <strong>combinación</strong> de educación universitaria y participación genera rechazo a la violencia estatal.</p>
<p>En cuanto a los controles el año 2019 muestra el contraste más dramático entre ambos tipos de violencia: pequeño aumento en justificación de violencia en protestas (+0.05<em>) pero una fuerte caída en la justificación de violencia estatal (-0.40</em><strong>), esto sugiere que el estallido social transformó radicalmente las actitudes hacia la represión policial. Las mujeres rechazan más la violencia estatal (-0.13</strong><em>) pero no difieren en violencia en protestas. La ideología opera consistentemente: derecha reduce justificación de violencia en protestas (-0.03</em><strong>) pero aumenta la de violencia estatal (+0.05</strong>*).</p>
<p>Este hallazgo, consistente con la H2, demuestra que la participación activa genera una reconfiguración normativa bidireccional (legitimar violencia en protestas, rechazar violencia estatal), pero esta reconfiguración solo es <strong>completa y significativa</strong> entre quienes combinan educación universitaria con experiencia directa de movilización. La educación sola no basta; la participación sola tampoco. Es su interacción la que produce el marco moral dual.</p>
<section id="evolución-temporal-de-la-reconfiguración-bidireccional" class="level3">
<h3 class="anchored" data-anchor-id="evolución-temporal-de-la-reconfiguración-bidireccional">Evolución temporal de la reconfiguración bidireccional</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-bidireccional-tiempo" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bidireccional-tiempo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04-analisis_files/figure-html/fig-bidireccional-tiempo-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bidireccional-tiempo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14: Evolución temporal de la reconfiguración bidireccional según educación y participación (2016-2023)
</figcaption>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-bidireccional-tiempo" class="quarto-xref">Figure&nbsp;14</a> visualiza la dinámica temporal de la reconfiguración bidireccional, revelando patrones diferenciados según nivel educativo y participación. En la fila superior, correspondiente a quienes no participan en protestas, se observa que en todos los niveles educativos las líneas amarilla (protestas) y azul (estatal) permanecen relativamente paralelas y cercanas entre sí. Aunque la educación técnica superior completa y universitaria completa muestran el efecto civilizatorio esperado con niveles más bajos de justificación, no hay divergencia marcada entre tipos de violencia, indicando que la reconfiguración bidireccional está ausente sin participación.</p>
<p>La fila inferior, correspondiente a participantes, revela patrones divergentes más complejos. Entre quienes tienen educación media completa o menos, la participación eleva significativamente la justificación de violencia en protestas (+0.27), pero genera solo rechazo moderado de violencia estatal, evidenciando una reconfiguración bidireccional incompleta. El grupo con técnico superior incompleto muestra la interacción más fuerte con protestas (+0.28<em>), alcanzando niveles de justificación superiores a 2.2 en 2019, sin embargo, no presenta diferenciación significativa en violencia estatal, legitimando así la violencia táctica pero sin desarrollar rechazo específico a la represión estatal. Aquellos con técnico superior completo exhiben un patrón intermedio donde el efecto civilizatorio inicial (-0.13</em>**) se neutraliza parcialmente por la participación (+0.13*), resultando en niveles moderados de justificación de protestas (~2.0-2.1), mientras la violencia estatal permanece estable sin evidencia de reconfiguración bidireccional completa.</p>
<p>El patrón bidireccional completo emerge exclusivamente entre quienes tienen universidad completa. Este panel muestra la reconfiguración dual característica con tres elementos distintivos: primero, una línea amarilla elevada que refleja justificación de violencia en protestas sostenida (~2.0-2.1), anulando el efecto civilizatorio universitario; segundo, un colapso dramático de la línea azul en 2019, con una caída en justificación de violencia estatal desde ~1.75 hasta ~1.35, alcanzando el nivel más bajo de toda la figura; y tercero, una divergencia máxima post-2019 con una brecha de aproximadamente 0.7 puntos entre ambos tipos de violencia, cristalizando así el marco moral dual. El efecto 2019 revela la especificidad del mecanismo: mientras todos los participantes aumentan la justificación de violencia en protestas, solo los universitarios participantes experimentan el colapso en legitimación de represión estatal (-0.40 puntos). Los técnicos superiores incompletos muestran la mayor radicalización en protestas pero sin diferenciación hacia lo estatal, sugiriendo que la reconfiguración bidireccional completa requiere no solo experiencia de movilización sino también capital cultural universitario para desarrollar el marco normativo dual sofisticado.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-bidireccional" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bidireccional-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04-analisis_files/figure-html/fig-bidireccional-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bidireccional-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15: Reconfiguración bidireccional: Universitarios que participan
</figcaption>
</figure>
</div>
</div>
</div>
<p>En síntesis, la participación genera una reconfiguración bidireccional coherente, pues, se legitima la violencia como herramienta de protesta mientras deslegitima la violencia como herramienta de represión.</p>
</section>
</section>
<section id="la-clase-social-como-moderador-estructural" class="level1">
<h1>La Clase Social como Moderador Estructural</h1>
<p>Tomando a la Clase de Servicio (Service class, categorías I+II del esquema EGP) como referencia, el modelo H3 de la <a href="#tbl-modelos-principales" class="quarto-xref">Table&nbsp;3</a> revela patrones distintivos de estratificación en la justificación de violencia. Los resultados muestran que la Clase Intermedia (categorías III+IV, profesionales de rutina y pequeños propietarios) no difiere significativamente de la Clase de Servicio entre no participantes (-0.01, ns), sugiriendo actitudes iniciales similares. En contraste, la Clase Trabajadora (categorías V+VI+VII, trabajadores manuales calificados y no calificados) exhibe un nivel basal significativamente más alto de justificación (+0.09, p&lt;0.01), evidenciando una “predisposición estructural” consistente con su mayor exposición a conflictos socioeconómicos y experiencias cotidianas de precariedad.</p>
<p>El efecto de la participación opera de manera marcadamente diferencial según clase social. Para la Clase de Servicio, participar en protestas genera un incremento dramático en la justificación de violencia (+0.36, p&lt;0.001), el cambio más pronunciado entre todas las clases. La Clase Intermedia muestra un patrón casi idéntico, con una interacción no significativa (+0.02, ns), indicando que su efecto total es similar al de la Clase de Servicio (+0.36). Sin embargo, la Clase Trabajadora exhibe una interacción negativa significativa (-0.15, p&lt;0.01), atenuando sustancialmente el efecto de la participación. El efecto neto para esta clase es +0.21 (0.36 - 0.15), aproximadamente 40% menor que el experimentado por las clases de servicio e intermedia.</p>
<p>Este patrón genera una convergencia de clase entre manifestantes: la brecha inicial de +0.09 puntos entre Clase Trabajadora y Clase de Servicio se reduce considerablemente cuando ambos grupos participan activamente. Mientras la Clase de Servicio parte de una línea base más baja pero experimenta un “salto cognitivo” al movilizarse (pasando de actitudes abstractas a legitimación experiencial), la Clase Trabajadora muestra un “efecto techo” consistente con predisposiciones estructurales que ya incorporaban mayor aceptación de tácticas disruptivas. Los controles revelan efectos esperados: el año 2019 no muestra el incremento observado en el modelo educativo sino una reducción dramática (-0.33, p&lt;0.001), sugiriendo que al controlar por clase social y participación, el estallido social aparece con menor justificación relativa. La edad reduce justificación (-0.01, p&lt;0.001), la ideología de derecha también la reduce (-0.03, p&lt;0.001), y el género no muestra efecto significativo (-0.01, ns). El intercepto aleatorio (varianza=0.11) es ligeramente menor que en el modelo educativo, indicando que la clase social captura algo menos de heterogeneidad individual.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-clase-protesta" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-clase-protesta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04-analisis_files/figure-html/fig-clase-protesta-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-clase-protesta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16: Efecto de participar en protestas según clase social
</figcaption>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-clase-protesta" class="quarto-xref">Figure&nbsp;16</a> visualiza el patrón de convergencia de clase documentado en los modelos, mostrando cómo la participación transforma diferencialmente las actitudes según posición estructural. El gráfico revela tres patrones distintivos. Primero, entre quienes no participan (izquierda), se observa una clara estratificación inicial: la Clase de Servicio (línea roja) y la Clase Intermedia (línea verde) parten de niveles casi idénticos de justificación (~1.80), mientras la Clase Trabajadora (línea azul) inicia significativamente más alta (~1.88), evidenciando la predisposición estructural documentada en el modelo (+0.09).</p>
<p>Segundo, la participación genera pendientes marcadamente diferentes. La Clase de Servicio e Intermedia exhiben las pendientes más pronunciadas, con incrementos dramáticos de aproximadamente 0.36 puntos al participar, saltando desde ~1.80 hasta ~2.15-2.17. Este “salto cognitivo” sugiere que individuos con mayor capital cultural y posiciones ocupacionales privilegiadas experimentan una transformación radical al enfrentarse directamente con la movilización, pasando de actitudes abstractas y distantes hacia una legitimación experiencial de tácticas disruptivas. En contraste, la Clase Trabajadora muestra una pendiente visiblemente más atenuada, incrementando solo 0.21 puntos (desde ~1.88 hasta ~2.09), consistente con el “efecto techo” donde predisposiciones estructurales previas ya incorporaban mayor tolerancia a la violencia política.</p>
<p>Tercero, el punto crucial es la convergencia en el extremo derecho del gráfico: entre participantes, las tres líneas terminan muy próximas (~2.09-2.17), con intervalos de confianza que se superponen sustancialmente. La brecha inicial de 0.09 puntos entre Clase Trabajadora y Clase de Servicio prácticamente desaparece entre manifestantes, donde todas las clases justifican la violencia en niveles similares. Este patrón de convergencia contrasta radicalmente con el modelo educativo (H1), donde la participación amplificaba las diferencias, generando divergencia. Aquí, la experiencia compartida de movilización “iguala” las diferencias de clase, sugiriendo que la posición estructural pierde poder predictivo cuando ambos grupos están inmersos en el mismo contexto de acción colectiva, mientras el capital cultural (educación) magnifica sus efectos diferenciales precisamente en ese mismo contexto.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-clase-estatal" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-clase-estatal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04-analisis_files/figure-html/fig-clase-estatal-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-clase-estatal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17: Efecto de participar en protestas según clase social
</figcaption>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-clase-estatal" class="quarto-xref">Figure&nbsp;17</a> muestra el patrón inverso respecto a la violencia en protestas. En este caso, todas las clases sociales parten de niveles similares de justificación de violencia estatal entre quienes no participan (~1.85-1.95), sin la estratificación inicial observada en el modelo de violencia en protestas.</p>
<p>Sin embargo, la participación genera un cambio dramático y distintivo: todas las clases sociales <strong>reducen</strong> su justificación de violencia estatal al participar, pero con magnitudes diferentes. La Clase de Servicio experimenta la caída más pronunciada (pendiente más negativa), bajando aproximadamente 0.30 puntos desde ~1.90 hasta ~1.60. La Clase Intermedia muestra una reducción similar, alcanzando niveles cercanos a ~1.65. En contraste, la Clase Trabajadora exhibe una pendiente menos pronunciada, reduciendo su justificación solo a ~1.75-1.80.</p>
<p>Este patrón revela una <strong>divergencia de clase</strong> entre participantes: mientras en violencia en protestas la participación generaba convergencia (todas las clases terminaban justificando por igual), en violencia estatal la participación amplifica las diferencias de clase. La Clase de Servicio desarrolla el rechazo más fuerte a la represión policial, consistente con su mayor capital cultural y capacidad para elaborar críticas institucionales sofisticadas. La Clase Trabajadora, aunque también reduce su justificación, mantiene niveles más altos, posiblemente reflejando mayor exposición histórica a la represión estatal o menor capacidad para articular una crítica completa al ejercicio de la violencia por parte del Estado.</p>
<p>Este contraste entre ambos tipos de violencia confirma que la reconfiguración bidireccional opera de manera diferencial según clase social: mientras la experiencia de movilización iguala las actitudes hacia la violencia táctica en protestas, simultáneamente estratifica las actitudes hacia la violencia estatal, siendo las clases con mayor capital cultural quienes desarrollan el rechazo más pronunciado a la represión policial.</p>
<section id="evolución-temporal-del-efecto-de-clase" class="level3">
<h3 class="anchored" data-anchor-id="evolución-temporal-del-efecto-de-clase">Evolución temporal del efecto de clase</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-clase-tiempo" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-clase-tiempo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04-analisis_files/figure-html/fig-clase-tiempo-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-clase-tiempo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18: Evolución temporal del efecto de clase según participación y tipo de violencia (2016-2023)
</figcaption>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-clase-tiempo" class="quarto-xref">Figure&nbsp;18</a> desagrega temporalmente los efectos de clase social sobre la justificación de violencia, revelando dinámicas diferenciadas según tipo de violencia y participación. El gráfico presenta un formato de facetas (3 columnas × 2 filas) donde cada columna representa una clase social y cada fila indica el nivel de participación, con las líneas amarillas mostrando violencia en protestas y las azules violencia estatal. La línea roja punteada marca 2019 como punto de inflexión crítico.</p>
<p>En la fila superior (no participantes), los tres paneles muestran patrones similares. Para la Clase de Servicio (izquierda), ambas líneas permanecen relativamente paralelas y estables (~1.75-1.85 para protestas, ~1.80-1.95 para estatal), sin divergencia significativa entre tipos de violencia. La Clase Intermedia (centro) exhibe un patrón casi idéntico, con trayectorias paralelas y niveles similares durante todo el período. La Clase Trabajadora (derecha) parte de niveles ligeramente más altos en violencia en protestas (~1.90 vs ~1.80 de Service class), pero también mantiene líneas paralelas sin reconfiguración bidireccional. En los tres casos, el año 2019 genera un pequeño incremento en ambos tipos de violencia, pero sin crear la divergencia característica de la reconfiguración bidireccional.</p>
<p>La fila inferior (participantes) revela patrones dramáticamente diferentes entre clases y tipos de violencia. En el panel de Clase de Servicio, la divergencia bidireccional es más pronunciada: la línea amarilla (protestas) se mantiene elevada (~2.00-2.20), mientras la línea azul (estatal) experimenta un colapso dramático en 2019, cayendo desde ~1.80 hasta ~1.35, el nivel más bajo de todo el gráfico. Esta brecha de aproximadamente 0.7-0.8 puntos cristaliza el marco moral dual entre participantes de esta clase. El panel de Clase Intermedia muestra un patrón similar pero menos extremo: la línea amarilla también se eleva (~1.90-2.10), y la azul cae en 2019 hasta ~1.50-1.60, generando una divergencia sustancial aunque menor que en Service class.</p>
<p>El panel de Clase Trabajadora revela el contraste más notable: aunque la línea amarilla (protestas) alcanza niveles similares a las otras clases (~2.00-2.10), indicando la convergencia de clase en justificación de violencia en protestas, la línea azul (estatal) muestra una caída mucho más moderada en 2019, descendiendo solo hasta ~1.50-1.60 (comparado con ~1.35 de Service class). Crucialmente, en 2022-2023, mientras las otras clases mantienen bajos niveles de justificación de violencia estatal, la Clase Trabajadora muestra un repunte sostenido, alcanzando niveles cercanos a ~1.80-1.90, prácticamente convergiendo nuevamente con sus niveles de justificación de violencia en protestas.</p>
<p>Este análisis temporal revela tres hallazgos centrales. Primero, la convergencia de clase en violencia en protestas: en 2019, los tres paneles de la fila inferior muestran líneas amarillas que alcanzan niveles prácticamente idénticos (~2.00-2.15), confirmando que la experiencia compartida de movilización iguala las actitudes hacia la violencia táctica independientemente de la clase social. Segundo, la divergencia de clase en violencia estatal: mientras todas las clases reducen su justificación al participar, la magnitud varía sustancialmente según capital cultural, con Service class desarrollando el rechazo más radical y Working class manteniendo niveles significativamente más altos. Tercero, la temporalidad diferencial: mientras Service class e Intermediate class mantienen la reconfiguración bidireccional en el período post-2019, Working class muestra una “re-convergencia” donde ambos tipos de violencia vuelven a niveles similares, sugiriendo que la reconfiguración bidireccional completa requiere no solo experiencia de movilización sino también recursos culturales para sostener el marco moral dual en el tiempo.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>