% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  13pt,
]{article}
\usepackage{xcolor}
\usepackage[margin=2cm]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
  \setmainfont[]{Times New Roman}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage{setspace}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother





\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


\usepackage[noblocks]{authblk}
\usepackage{array}
\usepackage{colortbl}
\usepackage{threeparttable}
\renewcommand*{\Authsep}{, }
\renewcommand*{\Authand}{, }
\renewcommand*{\Authands}{, }
\renewcommand\Affilfont{\small}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Actitudes hacia la violencia política en el ciclo contencioso chileno: Un ánálisis longitudinal desde la educación y la participación},
  pdfauthor={René Canales \& Daniel Miranda},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Actitudes hacia la violencia política en el ciclo contencioso
chileno: Un ánálisis longitudinal desde la educación y la participación}


  \author{René Canales \& Daniel Miranda}
  
\date{March, 2026}
\begin{document}
\maketitle
\begin{abstract}
El estallido social chileno de octubre 2019 generó una paradoja: ¿por
qué las clases medias educadas legitimaron violencia disruptiva,
contrario a su tradicional moderación democrática? Utilizando datos
longitudinales de ELSOC (2016-2023, 20.007 observaciones/3.666
individuos), este estudio desafía el ``efecto civilizatorio'' de la
educación mediante modelos multinivel. Los hallazgos revelan que la
educación opera como amplificador cognitivo condicional: reduce la
justificación de violencia entre no participantes, pero la incrementa
dramáticamente entre manifestantes. Los universitarios movilizados
alcanzan los niveles más altos, invirtiendo completamente el efecto
civilizatorio. El análisis evidencia una ``reconfiguración
bidireccional'': los participantes educados legitiman violencia de
protesta mientras rechazan violencia estatal, desarrollando marcos
morales duales sofisticados. La clase social modera estructuralmente
estos efectos: la clase trabajadora exhibe ``efecto techo'' (alta
tolerancia basal), mientras la clase de servicio experimenta ``salto
cognitivo'' radical, convergiendo con sectores populares. Estos
hallazgos iluminan cómo la transversalidad del movimiento chileno
emergió de la transformación actitudinal de sectores profesionales que,
mediante participación, rearticularon marcos morales legitimando la
transgresión normativa como expresión política válida, contribuyendo a
literaturas sobre educación política, desigualdad y socialización..
\newline \textbf{Keywords}: Actitudes hacia la violencia · Protestas ·
Estratificación · · Chile
\end{abstract}


\setstretch{1.5}
\section{Introducción}\label{introducciuxf3n}

El 18 de octubre de 2019 marcó un antes y un después en la historia
política de Chile. Lo que comenzó con la evasión masiva del metro en
Santiago por parte de estudiantes en respuesta a las alzas en las
tarifas en el pasaje, se transformó en cuestión de horas en el
acontecimiento contencioso más impactante desde el retorno a la
democracia (Somma et al., 2021). Durante semanas, miles de personas
ocuparon las calles de todo el país, desafiando tanto la herencia
neoliberal de la dictadura (Canales, 2022; Garcés, 2020; Araujo, 2025)
como los límites históricos de la acción colectiva (Somma, 2021; Cox et
al., 2024; Pleyers, 2023). La llamada ``primavera chilena'' combinó
masividad, transversalidad social y repertorios confrontacionales en
proporciones nunca antes vistas: desde marchas multitudinarias hasta
bloqueos, enfrentamientos con Carabineros y ataques a la infraestructura
pública (Rivera et al., 2025).

La reacción estatal fue, igualmente, excepcional: el gobierno liderado
por el entonces presidente Sebastián Piñera, decretó estado de
emergencia llamando al despliegue de militares en las calles por primera
vez desde el retorno a la democracia (Somma et al., 2021; Thaler et al.,
2023). La represión produjo más de 8.000 víctimas de violencia policial,
más de 400 casos de trauma ocular y al menos 34 muertes, configurando
---según Amnistía Internacional--- la crisis de derechos humanos más
grave desde el fin de la dictadura (Amnistía Internacional, 2020; Human
Rights Watch, 2019; Rodríguez et al., 2021). Este escenario profundizó
la polarización mediática y política, instalando en el debate público
una pregunta persistente: ¿cuándo, y para quién, la violencia política
resulta legítima? Diversos estudios han mostrado que la justificación de
la violencia durante el estallido no fue homogénea. Disi Pavlic et
al.~(2025) evidencian que su aceptación varía según la proximidad
temporal, espacial e ideológica; mientras que González y Le Foulon
(2020) muestran que los manifestantes más intensivos ---jóvenes,
educados y de izquierda--- tendían a justificar con mayor frecuencia la
violencia en protesta que quienes estaban al margen de estos eventos.
Este patrón resulta contraintuitivo frente a la literatura clásica que
asocia educación con mayor aceptación de las normas democráticas y
rechazo a la violencia (Dewey, 2024; Lipset, 1959; Nie et al., 1996).
¿Cómo explicar, entonces, que sectores más educados hayan mostrado mayor
disposición a justificar la violencia en el ciclo de movilización?

El problema remite a una limitación teórica fundamental de buena parte
de la literatura sobre actitudes políticas y conflicto: la tendencia a
modelar los efectos de la educación como lineales, estables y
universales, sin considerar que estos pueden ser contingentes al
contexto de acción y las experiencias participativas. Este supuesto se
encuentra en el corazón del modelo de recursos (Verba, Schlozman \&
Brady, 1995), según el cual la participación y las actitudes políticas
dependen del acceso diferencial a recursos ---educación, tiempo, dinero
y habilidades cívicas---. Desde esta perspectiva, mayores niveles de
recursos se asocian con actitudes más convencionales y mayor compromiso
institucional.

Sin embargo, este enfoque deja fuera la posibilidad de que la
participación política sea una experiencia transformadora y no solo el
reflejo de predisposiciones previas. McAdam (1989) demostró que el
activismo de alto riesgo tiene ``consecuencias biográficas'' duraderas:
altera marcos interpretativos, identidades colectivas y evaluaciones
morales sobre la legitimidad de la acción. Participar en protestas
expone a los individuos a discursos alternativos (Snow \& Benford,
1988a), genera solidaridad grupal y, en contextos represivos, puede
confrontarlos directamente con la violencia estatal. Estas experiencias
no solo reconfiguran actitudes políticas, sino que modulan cómo operan
los efectos de la educación sobre la justificación de la violencia.

Estas dimensiones explican por qué la participación en protesta no opera
de modo uniforme sobre las actitudes, sino que activa potenciales de
cambio diferenciales anclados en trayectorias y repertorios
(Pérez-Ahumada, 2023; Pérez-Ahumada \& Andrade, 2021; McAdam, 1989;
Tarrow, 1998; Snow \& Benford, 1988; Gurr, 2000).

A partir de estas limitaciones, este estudio propone un modelo
alternativo para comprender la legitimidad subjetiva de la violencia
política. El argumento central es que los efectos de la educación sobre
las actitudes hacia la violencia son condicionales a la participación en
protestas y operan mediante mecanismos diferenciados: Efecto educativo
condicional. La educación no tiene un efecto civilizatorio universal,
sino que actúa como amplificador cognitivo. Entre quienes no participan,
la educación reduce la justificación de la violencia (efecto
civilizatorio clásico); entre quienes participan, ese efecto se
invierte, pues la educación provee marcos ideológicos más elaborados
para legitimar la violencia táctica en contextos específicos de
movilización (Snow \& Benford, 1988).

Reconfiguración moral de la violencia. La participación en protestas
genera una distinción normativa entre tipos de violencia: los
universitarios movilizados tienden a justificar la violencia de protesta
mientras rechazan la estatal, coherente con teorías de legitimidad y
justicia procedimental (Davenport, 1995; Muñoz \& Anduiza, 2019; Tyler,
2006). La pregunta que orienta este estudio es, por tanto: ¿Cómo
interactúan la educación y la participación en protestas para moldear
actitudes hacia la violencia política en el contexto chileno a través
del tiempo?

Este trabajo busca contribuir a dos campos. Primero, a la literatura
sobre educación y actitudes políticas, al mostrar que el ``efecto
civilizatorio'' es condicional y depende del contexto participativo (Nie
et al., 1996; Weakliem, 2002). Segundo, a la literatura sobre
participación y socialización política (McAdam, 1989; Giugni, 2004), al
evidenciar que la participación no tiene efectos uniformes, sino que
interactúa con recursos cognitivos e interpretativos de manera compleja.

Sustantivamente, este estudio busca iluminar las bases de la
legitimación de la violencia durante el ciclo contencioso chileno:
mostrar cómo la participación en protestas puede transformar marcos
morales y habilitar la legitimación de ciertas formas de transgresión
normativa como expresión de conflicto político. El Caso chileno ofrece
un escenario empírico excepcional para examinar cómo estos mecanismos
operan en situaciones de crisis profunda. El estallido social de 2019 no
sólo activó dinámicas participativas masivas, sino que reconfiguró de
manera acelerada las percepciones de injusticia, los marcos morales y
las fronteras de lo políticamente aceptable. La combinación de malestar
estructural, agotamiento institucional y una respuesta estatal percibida
como ilegítima generó un entorno donde la educación dejó de funcionar
como predictor lineal de compromiso normativo. Por el contrario, este
factor se articuló con las experiencias de protesta para producir
transformaciones actitudinales diferenciadas. Analizar el ciclo
contencioso chileno permite, por tanto, situar empíricamente el
argumento de este estudio: que la legitimidad subjetiva de la violencia
política es el resultado de una interacción contingente entre recursos
interpretativos y vivencias participativas, cuya configuración concreta
solo puede entenderse a la luz del colapso del pacto social que definió
este periodo.

\section{Antecedentes teóricos y
empíricos}\label{antecedentes-teuxf3ricos-y-empuxedricos}

\subsection{Justificación de la
violencia}\label{justificaciuxf3n-de-la-violencia}

La justificación de la violencia en contextos de protesta constituye un
fenómeno complejo, que se vale de una distinción importante entre las
actitudes hacia la violencia ejercida por manifestantes como aquella
empleada por las fuerzas de agentes del Estado (Marx, 1998; Disi Pavlic
et al., 2025), las cuales son distintas pero no necesariamente
excluyentes. En este apartado, se examinan los marcos que explican cómo
los ciudadanos evalúan y justifican diferentes formas de violencia en el
contexto de movilizaciones sociales, considerando tanto los
determinantes estructurales de estas actitudes como las experiencias
transformadoras derivadas de la participación política y la exposición a
eventos contenciosos.

\subsubsection{Justificación de la Violencia por Parte de
Manifestantes}\label{justificaciuxf3n-de-la-violencia-por-parte-de-manifestantes}

La literatura sobre política contenciosa ha documentado extensamente
cómo ciertos sectores de la ciudadanía pueden llegar a justificar el uso
de tácticas violentas por parte de manifestantes como respuesta a
condiciones de la percepción de injusticia en la protesta (Goodwin,
2001; Tilly, 1998). Estudios muestran que, en gran medida, la exposición
a la represión puede incrementar significativamente la disposición de
las personas a justificar la violencia contra las fuerzas policiales
(Della Porta, 2018; Disi Pavlic et al., 2025; Earl et al., 2022; Gerber
et al., 2023).

En esta línea, la teoría de la reactancia psicológica (Brehm, 1966)
constituye uno de los marcos fundamentales para comprender las
respuestas ciudadanas ante el policiamiento restrictivo. Esta sostiene
que cuando los individuos perciben que sus libertades están siendo
amenazadas o restringidas de manera injustificada, experimentan un
estado motivacional dirigido a restaurar esas libertades. En contextos
de protesta, la represión puede ser interpretada como una restricción
ilegítima de derechos fundamentales, generando una reacción
compensatoria que se manifiesta en el apoyo a tácticas confrontacionales
como forma de resistencia (Adam-Troian et al., 2020).

Esta perspectiva ayuda a explicar por qué incluso ciudadanos sin
afiliación previa a los movimientos involucrados pueden desarrollar
actitudes favorables hacia la violencia de protesta cuando perciben que
las autoridades están reprimiendo de manera desproporcionada, o injusta,
las manifestaciones (Disi-Pavlic et al., 2025). La reactancia no solo
afecta a quienes participan directamente, sino también a observadores
que internalizan la restricción de libertades como una amenaza al orden
democrático.

Por su parte, la teoría de la radicalización (Kruglanski et al., 2014)
sugiere que esta exposición puede alimentar el apoyo a la violencia como
reacción a la injusticia percibida, mediante un proceso de ``búsqueda de
significado'' donde los individuos reinterpretan sus sistemas de valores
ante experiencias de amenaza o agravio. Este proceso de radicalización
no se limita a los participantes directos de las protestas, sino que
puede extenderse a observadores que, sin participar activamente,
experimentan indirectamente los efectos de la represión a través de
medios de comunicación o narrativas comunitarias (Luna, 2024).

La literatura sobre escalamiento de protestas documenta cómo las
dinámicas de confrontación entre manifestantes y policía pueden generar
ciclos de violencia que transforman progresivamente las actitudes
políticas de las personas (Francisco, 1995; Koopmans, 1993). Cuando el
Estado responde con represión a demandas percibidas como legítimas,
puede desencadenar lo que Goodwin (2001) denomina ``radicalización por
exclusión'': la clausura de canales institucionales de expresión empuja
a sectores previamente moderados hacia la justificación de tácticas más
transgresivas.

Por otro lado, hay estudios (Tyler \& Blader, 2003; Tyler, 2006) que se
inclinan por la teoría de la justicia procedimental como marco sólido
para explicar actitudes hacia la violencia policial y la de
manifestantes, al centrar la evaluación en la equidad de los procesos
más que en sus resultados. Su legitimidad se ancla en ciertas
dimensiones ---voz, neutralidad, trato respetuoso y confiabilidad---
que, en contextos de protesta, se asocian con mayor aceptación de la
acción policial y menor apoyo a la violencia contra autoridades (Jackson
et al., 2013; Sunshine \& Tyler, 2003); a la inversa, la injusticia
percibida erosiona la legitimidad y eleva la justificación de la
resistencia (Gerber \& Jackson, 2017).

La evidencia es consistente con que el trato policial injusto predice la
disposición a justificar violencia. Maguire et al.~(2020) muestran cómo
en movimientos como Occupy Wall Street la injusticia procedimental era
un predictor robusto entre quienes apoyaban tácticas confrontacionales.
Donde interacciones con la policía pueden llevar incluso a previamente
no violentos a enmarcar la violencia como autodefensa o represalia
(Tyler et al., 2018; Drury \& Reicher, 2018; Saavedra \& Drury, 2019).
Zhu \& Chou (2025) muestran en el caso de Hong Kong, cómo la baja
percepción de justicia procedimental incrementó el apoyo público a la
violencia de manifestantes al fomentar la identificación con
protestantes militantes.

En Chile, percepciones de justicia procedimental y legitimidad policial,
mediadas por identidad grupal, influyen en actitudes hacia violencia
policial y de manifestantes (Gerber et al., 2018). Durante el estallido
social de 2019, la crisis de legitimidad de Carabineros ---exacerbada
por denuncias masivas de violaciones de derechos humanos--- reconfiguró
las actitudes intergrupales: la percepción de impunidad y de irrespeto a
procedimientos normalizó la justificación de la violencia de protesta
como autodefensa legítima (Gerber et al., 2023; Carrasco Paillamilla \&
Disi Pavlic, 2023).

\subsubsection{Identidad Grupal y Actitudes Diferenciadas hacia la
Violencia}\label{identidad-grupal-y-actitudes-diferenciadas-hacia-la-violencia}

Las actitudes hacia la violencia en contextos de protesta no son
homogéneas, sino que están profundamente mediadas por identidades
grupales y posiciones en la estructura social (Reinka \& Leach, 2017;
Gerber et al., 2018). La violencia política no se evalúa de forma
abstracta, sino en función de quién la ejerce, contra quién se dirige y
qué objetivos persigue. En este marco, la literatura ha identificado dos
orientaciones ideológicas centrales para explicar estas evaluaciones: la
Orientación de Dominancia Social (SDO) y el Autoritarismo de Derecha
(RWA). La SDO expresa una preferencia por jerarquías grupales y la
legitimación de la desigualdad, lo que se traduce en un mayor respaldo a
prácticas que preservan el orden social existente (Pratto et al., 1994).
En contextos de protesta, altos niveles de SDO se asocian con apoyo a la
represión policial y con un rechazo sistemático a la violencia de
protesta, entendida como una amenaza a jerarquías consideradas legítimas
(Krause, 2009; Onursal et al., 2023). De forma complementaria, el RWA
---caracterizado por sumisión a la autoridad, convencionalismo y
agresión autoritaria--- se vincula con mayor tolerancia al uso de la
fuerza por parte de autoridades y oposición a protestas que emplean
tácticas disruptivas o confrontacionales (Altemeyer, 1998; Jost et al.,
2003). Finalmente, las creencias en un mundo justo y la tendencia a
culpabilizar a las víctimas operan como mecanismos cognitivos que
refuerzan la justificación de la violencia estatal (Lerner, 1980; Ryan,
2010). Estas creencias favorecen atribuciones causales sesgadas que
responsabilizan a los manifestantes por la represión sufrida,
minimizando la responsabilidad institucional y la desproporción del uso
de la fuerza, especialmente cuando las víctimas pertenecen a grupos
estigmatizados o las protestas adoptan repertorios transgresivos (Gerber
et al., 2016; Arthur \& Case, 1994; Thompson et al., 2004).

\subsubsection{Razonamiento Motivado, Ideología Política y el Efecto de
Actitud
Previa}\label{razonamiento-motivado-ideologuxeda-poluxedtica-y-el-efecto-de-actitud-previa}

El enfoque de razonamiento motivado (Taber \& Lodge, 2012) ofrece un
marco integrador para comprender cómo las predisposiciones ideológicas y
las identidades grupales estructuran las respuestas ciudadanas frente a
eventos de protesta y policiamiento. En contraste con los modelos
racionalistas, este enfoque sostiene que el procesamiento de información
política es inherentemente sesgado y orientado a proteger actitudes e
identidades preexistentes, lo que condiciona la interpretación de hechos
políticamente cargados como el uso de la fuerza policial o la violencia
de protesta. Este razonamiento opera principalmente a través de dos
mecanismos: el sesgo de confirmación, que favorece la atención y el
recuerdo de información consistente con creencias previas, y el sesgo de
descredibilización, que implica el rechazo crítico de información
incongruente, aun cuando sea objetivamente válida (Taber \& Lodge,
2006). En contextos de protesta, estos sesgos se manifiestan en el
``efecto de actitud previa'', mediante el cual individuos con distintas
orientaciones ideológicas interpretan de forma divergente los mismos
eventos: la violencia policial o de protesta puede ser vista como
legítima o ilegítima dependiendo del grado de simpatía con el movimiento
social (Hsiao \& Radnitz, 2021; Gutting, 2020). La evidencia empírica
muestra que estas dinámicas se intensifican según el nivel de
estructuración ideológica. Estudios en el contexto del estallido social
chileno indican que personas de izquierda aumentaron su tolerancia hacia
la violencia de protesta tras la exposición a represión policial,
mientras que individuos de derecha mantuvieron un rechazo estable,
independientemente de las tácticas observadas (Disi Pavlic et al.,
2025). En contraste, los centristas exhibieron los cambios actitudinales
más pronunciados, lo que es consistente con el modelo
Receive-Accept-Sample de Zaller (1992): al carecer de filtros
ideológicos robustos, estos individuos son más permeables a información
contradictoria y, por tanto, más susceptibles a cambios actitudinales
frente a eventos salientes como el policiamiento represivo.

\subsubsection{Efectos de Proximidad, Exposición y Mecanismos de Cambio
Actitudinal}\label{efectos-de-proximidad-exposiciuxf3n-y-mecanismos-de-cambio-actitudinal}

La proximidad espacial y temporal a protestas influye en las actitudes
políticas, pero de forma contingente y no unidireccional, operando a
través de mecanismos informacionales, psicológicos y emocionales
(Wallace et al., 2014; Disi Pavlic, 2021; Ketchley \& El-Rayyes, 2021).
Informacionalmente, la cercanía incrementa saliencia y accesibilidad
mediante redes locales, observación directa y cobertura mediática,
funcionando como heurístico contextual que señala la existencia de
agravios (Branton et al., 2015; Tertytchnaya \& Lankina, 2020).
Psicológicamente, la exposición repetida puede normalizar repertorios
inicialmente percibidos como transgresivos (mero efecto de exposición),
aunque sus efectos dependen del tipo de evento: protestas pacíficas
elevan simpatía y apoyo, mientras la violencia sostenida genera backlash
y demanda de orden (Ayoub et al., 2021; Mazumder, 2018; Wasow, 2020; Xu
\& Guo, 2023; Muñoz \& Anduiza, 2019).

En el plano emocional e identitario, la percepción de injusticia
procedimental activa identificación y solidaridad, transformando la
indignación moral en mayor justificación de resistencia; por el
contrario, la violencia indiscriminada contra terceros induce alienación
(Adam-Troian et al., 2020; Muñoz \& Anduiza, 2019). En síntesis, la
proximidad no obra mecánicamente: sus efectos dependen del repertorio
observado, del encuadre informacional y de las respuestas afectivas
detonadas por el contexto.

\subsection{El policing: Estilos, Consecuencias y Efectos
Diferenciales}\label{el-policing-estilos-consecuencias-y-efectos-diferenciales}

El policing de protestas se refiere al conjunto de estrategias, tácticas
y tecnologías empleadas por fuerzas policiales para gestionar, controlar
o suprimir manifestaciones públicas (Marx, 1998; Disi Pavlic et al.,
2025). La literatura identifica dos grandes enfoques: el manejo
negociado, que privilegia la comunicación, la tolerancia a disrupciones
menores y el uso mínimo de la fuerza, y el modelo de fuerza escalada,
basado en la demostración coercitiva, arrestos preventivos y baja
tolerancia a desviaciones (Della Porta \& Fillieule, 2007).
Recientemente se ha propuesto distinguir entre policing activo
---intervención directa con agentes químicos, proyectiles y detenciones
masivas--- y policing pasivo ---monitoreo, facilitación de derechos y
contención selectiva (Disi Pavlic et al., 2025).

La adopción de uno u otro enfoque responde a determinantes políticos e
institucionales: la seguridad electoral del gobierno (Aytaç et al.,
2017), la identidad de los manifestantes (Davenport et al., 2011; Medel
\& Somma, 2022), los repertorios utilizados y su etiquetamiento (Ortiz,
2015), así como legados autoritarios y culturas policiales que priorizan
el control por sobre la facilitación (Bonner \& Dammert, 2022; Ortiz,
2015).

Estas decisiones tienen efectos sustantivos. Sobre los movimientos, la
fuerza escalada puede elevar costos y fragmentar, pero también gatillar
escalamiento y radicalización cuando se percibe como desproporcionada;
su eficacia, además, depende del timing represivo (Koopmans, 1993;
Francisco, 1995; Muller \& Weede, 1990). Sobre el sistema político, el
policiamiento excesivo erosiona la legitimidad de la policía y del
gobierno, pudiendo incluso precipitar crisis y sanciones políticas
(Pérez-Liñán, 2007; Bonner \& Dammert, 2022), como ocurrió en Chile
durante el estallido de 2019. Crucialmente, sus impactos en la opinión
pública no son uniformes: varían según ideología, proximidad
espacial/temporal y experiencia previa de protesta, con centristas
mostrando mayor susceptibilidad a cambios actitudinales frente a la
represión que los polos ideológicos, cuyas posiciones se mantienen más
estables (Disi Pavlic et al., 2025).

\subsection{Educación y actitudes
políticas}\label{educaciuxf3n-y-actitudes-poluxedticas}

La relación entre la educación y la participación política es uno de los
hallazgos más consistentes y documentados en las ciencias sociales
(Berinsky \& Lenz, 2011; Persson, 2015; Verba et al., 1995). Durante
décadas, la investigación ha demostrado una correlación robusta: los
ciudadanos con niveles más altos de educación formal tienden a
participar más en política, ya sea votando o involucrándose en
diferentes actividades cívicas (Wolfinger \& Rosenstone, 1980; Persson,
2015). Sin embargo, la naturaleza de esta relación, así como las
actitudes que se manifiestan, es un debate que sigue dando de qué
hablar.

\subsubsection{El efecto civilizatorio}\label{el-efecto-civilizatorio}

El argumento clásico del ``efecto civilizatorio'' (Lipset, 1959; Almond
\& Verba, 1963) postula que la educación fomenta la internalización de
normas democráticas, reduciendo la propensión a aceptar la violencia
política. Esta hipótesis descansa en tres supuestos: primero, que la
educación desarrolla habilidades cognitivas que permiten comprender la
complejidad social y, por ende, adoptar posturas moderadas (Converse,
1972; Nie et al., 1996); segundo, que promueve valores de tolerancia,
pluralismo y respeto a las instituciones (Siegel, 1981; Pascarella \&
Terenzini, 1991); y tercero, que fortalece la eficacia política
subjetiva ---la creencia de que las instituciones responden a las
demandas ciudadanas---, lo que reduce la percepción de que la violencia
sea necesaria como medio de acción (Dyrstad \& Hillesund, 2020).

Bajo este paradigma, el sistema educativo cumple una función
integradora: produce ciudadanos racionales y responsables que canalizan
sus conflictos mediante vías institucionales. Desde esta óptica, la
educación ``domestica'' la conflictividad política y moral,
transformando la violencia en algo ajeno a la ciudadanía moderna
(Weakliem, 2002). La justificación de la violencia, entonces, se
entiende como un residuo de déficit educativo o de exclusión cultural.

No obstante, este modelo presupone condiciones de igualdad estructural
que raramente existen. En sociedades donde el acceso a bienes, derechos
y oportunidades se encuentra profundamente estratificado, la educación
no opera sobre un terreno neutro, sino dentro de un campo desigual de
reconocimiento (Acemoglu et al.; 2005). Las instituciones educativas
reproducen jerarquías culturales y económicas (Bourdieu \& Passeron,
1970), y con ello también distribuyen desigualmente la confianza en el
orden político. Por tanto, la relación entre educación y justificación
de la violencia no puede entenderse sin considerar el contexto de
desigualdad estructural que moldea las expectativas de justicia y los
límites de la acción legítima (Castillo et al., 2015).

A pesar de su influencia, el modelo del ``efecto civilizatorio'' de la
educación enfrenta limitaciones empíricas y conceptuales relevantes. El
denominado ``dilema de Brody'' plantea una paradoja central: si la
educación incrementa la participación y modera actitudes
antidemocráticas, resulta difícil explicar por qué la participación
cívica agregada se ha mantenido estable o ha disminuido en muchos países
pese al fuerte aumento en los niveles educativos (Berinsky \& Lenz,
2011). Esta tensión dio lugar a la perspectiva de la ``educación como
proxy'', según la cual la asociación entre educación y actitudes
políticas es en gran medida espuria y refleja procesos de autoselección
vinculados a factores preadultos como el origen socioeconómico, la
socialización política temprana y rasgos cognitivos o disposicionales
(Persson, 2015; Langton \& Jennings, 1968).

La evidencia contemporánea respalda esta revisión crítica. Estudios que
emplean paneles, pareo y experimentos naturales muestran que los efectos
causales directos de la educación sobre actitudes políticas son
limitados, y que la mayor parte de la brecha entre graduados y no
graduados se explica por autoselección (Kam \& Palmer, 2008; Tenn, 2007;
Berinsky \& Lenz, 2011; Fryer, 2023). Además, el modelo civilizatorio ha
tendido a centrarse en actitudes abstractas, ignorando que la educación
no reduce de forma consistente el apoyo a la violencia política en
contextos específicos. Evidencia contraintuitiva ---como la presencia de
individuos altamente educados en organizaciones violentas o el apoyo a
la violencia bajo ciertas condiciones--- sugiere que los efectos de la
educación son contingentes al contexto y al tipo de participación
política en juego (Krueger \& Malečková, 2003; Fair \& Shepherd, 2006;
Carlin, 2011).

En contextos de alta desigualdad y deslegitimación institucional, la
educación puede dejar de operar como mecanismo de integración y
transformarse en un recurso de elaboración moral. Más que inhibir la
violencia, permite articular justificaciones sofisticadas que la
enmarcan como respuesta excepcional frente a un orden percibido como
estructuralmente injusto (Della Porta, 2017; Jasper, 1998). El resultado
es una relación no lineal entre educación y actitudes hacia la
violencia: mientras los sectores más educados tienden a justificarla
mediante marcos normativos universales, los menos educados pueden
normalizarla desde la experiencia cotidiana de violencia estructural y
simbólica, sin una mediación ideológica explícita (Wacquant, 2008;
Smolski, 2021; Varlik et al., 2025).

\subsubsection{Educación como
amplificador}\label{educaciuxf3n-como-amplificador}

Las limitaciones del consenso (la autoselección y el problema del
contexto) no invalidan la educación, sino que exigen una
reconceptualización. En lugar de un ``efecto civilizatorio'' directo y
universal, esta tesis propone que la educación funciona como un
amplificador cognitivo condicional. No determina qué pensar, sino cómo
pensar sobre el mundo político.

En esta visión, la educación no es ni una causa directa simple ni un
simple indicador pasivo. Su función principal es clasificar a los
individuos y amplificar ciertos valores o rasgos, lo que desencadena
efectos indirectos complejos (Sabucedo et al., 2018). El mecanismo clave
no es la inculcación de la tolerancia, sino la ``sofisticación
cognitiva'' (Nie et al., 1996): la educación proporciona las
herramientas analíticas para elaborar marcos morales y justificaciones
tácticas más complejas. Esta sofisticación puede usarse tanto para
deslegitimar prácticas que involucran la violencia (el argumento
civilizatorio), como para legitimarla si el contexto situacional lo
requiere (ej. re-enmarcarla como autodefensa legítima).

Por tanto, el efecto de la educación, en este marco, es condicional.
Dependería del contexto de activación, siendo la participación en
protestas uno de los más potentes. Como argumentan Sabucedo et
al.~(2018), la educación tiene ``efectos supresores'' morales
paradójicos: un efecto directo (liberal) y un efecto indirecto
(conservador, vía ingreso) que se contrarrestan. Weakliem (2002) ofrece
un mecanismo similar al argumentar que la educación amplifica el
individualismo, lo que lleva a los educados a ser liberales en lo social
pero conservadores en otros temas, como lo económico (Hastie, 2007). La
educación, por tanto, crea un potencial cognitivo que será activado y
dirigido por experiencias posteriores, como la participación política.

En contextos de alta desigualdad estructural y represión estatal, la
educación puede convertirse en un amplificador moral de la
radicalización cognitiva. Este efecto no implica que los individuos más
educados sean más propensos a la violencia, sino que poseen mayor
capacidad para racionalizar su legitimidad cuando consideran que los
canales institucionales han perdido eficacia o justicia.

La educación dota de vocabulario político, histórico y ético para
reinterpretar la violencia no como mera ruptura del orden, sino como
acción moralmente coherente con principios de justicia o defensa de
derechos fundamentales (Snow \& Benford, 1988). Esta capacidad de
reinterpretación moral puede observarse en movimientos donde los
sectores educados redefinen la protesta violenta como una forma de
``violencia defensiva'' o ``resistencia legítima'' frente a estructuras
percibidas como violentas en sí mismas (Varlik et al., 2025).

De este modo, el efecto de la educación no es inhibitorio, sino
transformativo: reconfigura la gramática moral mediante la cual los
individuos evalúan la violencia política. Donde el sentido común ve
desorden, los individuos más educados pueden ver contradicción
estructural o injusticia moral. La educación, entonces, no elimina la
violencia del horizonte político, sino que la reinscribe en un marco
moralmente argumentado, donde el conflicto puede concebirse como medio
legítimo de emancipación o denuncia.

\subsubsection{El mecanismo de activación: de lo abstracto a lo
situacional}\label{el-mecanismo-de-activaciuxf3n-de-lo-abstracto-a-lo-situacional}

El mecanismo de activación clave ocurre cuando la participación directa
en protestas expone a los individuos educados a experiencias
situacionales que entran en tensión con principios abstractos. Mientras
que las actitudes sobre la violencia política se forman típicamente en
contextos descontextualizados ---donde predominan normas democráticas
generales---, la experiencia de protestar introduce elementos que pueden
alterar este marco de referencia. Como argumentan Klandermans y Van
Stekelenburg (2013), la participación en acción colectiva transforma las
actitudes políticas no solo por exposición a información, sino mediante
la experiencia vivida del conflicto.

En primer lugar, la participación directa genera experiencia situada con
la represión y el conflicto político. Los manifestantes pueden
presenciar o experimentar personalmente el uso de la fuerza por parte
del Estado, encuentros con contra-manifestantes, o situaciones de
tensión que transforman la protesta de un concepto abstracto a una
realidad visceral (Della Porta, 2013). Esta experiencia directa puede
activar marcos de ``autodefensa legítima'' o ``resistencia necesaria''
que permanecen latentes en quienes sólo reflexionan sobre la protesta
desde fuera. La investigación sobre radicalización muestra que la
experiencia personal con la represión estatal es un predictor
significativo del apoyo a tácticas más confrontacionales (Marx, 1998;
Earl et al., 2003).

En segundo lugar, el contexto de protesta expone a los individuos a
narrativas de justificación más sofisticadas. En estos espacios circulan
marcos ideológicos elaborados que distinguen, por ejemplo, entre
``violencia contra la propiedad'' y ``violencia contra personas'', entre
``violencia como primer recurso'' y ``violencia como respuesta'', o
entre ``violencia estatal estructural'' y ``violencia de resistencia''
(Tilly, 2003; Gamson, 2002). Estos marcos no son simples
racionalizaciones, sino construcciones ideológicas complejas que
requieren precisamente el tipo de sofisticación cognitiva que la
educación proporciona para ser internalizadas y aplicadas. Como
documentan Benford y Snow (2000), de acuerdo con la teoría del ``frame
alignment'', los movimientos sociales desarrollan marcos interpretativos
específicos que resuenan diferencialmente según las capacidades
cognitivas de los participantes.

En tercer lugar, la participación crea una identidad colectiva capaz de
modificar el peso relativo de distintas consideraciones morales
(Polletta \& Jasper, 2001). La lealtad al grupo, la solidaridad con
compañeros manifestantes, y la identificación con una causa pueden
entrar en tensión con normas abstractas de no-violencia (Simon \&
Klandermans, 2001). Crucialmente, los individuos más educados poseen
mayor capacidad para manejar esta tensión mediante la
compartimentalización cognitiva: pueden mantener valores democráticos
generales mientras construyen excepciones situacionales específicas
(Tetlock, 1986; Jost et al., 2003).

Este último punto conecta directamente con la evidencia contraintuitiva
que mencionan Krueger y Malečková (2003) sobre la presencia de
individuos educados en organizaciones violentas, y Fair y Shepherd
(2006) sobre la relación no lineal entre educación y apoyo al
terrorismo. Estos hallazgos sugieren que la sofisticación cognitiva no
necesariamente conduce a la moderación, sino que permite elaborar
justificaciones más complejas y contextualizadas para acciones que, en
abstracto, serían rechazadas. Los individuos menos educados, por
contraste, tienden a mantener posiciones más consistentes ---ya sea de
rechazo o apoyo--- que no varían tanto según el contexto, precisamente
porque carecen de las herramientas cognitivas para construir estas
distinciones situacionales sofisticadas.

Con lo anterior, se podría decir que la participación en protestas no
simplemente ``activa'' un efecto latente de la educación, sino que crea
las condiciones específicas donde la sofisticación cognitiva se emplea
para legitimar tácticamente la violencia. Esto ocurre mediante la
exposición a experiencias situacionales, narrativas ideológicas
complejas, y presiones identitarias que, en conjunto, permiten a los
individuos educados reconfigurar sus marcos morales de manera que la
violencia en contextos de protesta puede ser vista como una excepción
legítima a la norma democrática general.

En este sentido, se presenta una especie de (H1) efecto paradoja de la
educación. Donde:

\textbf{H1a}: Entre individuos que no participan en protestas, mayor
nivel educativo está asociado con menor justificación de violencia en
manifestaciones, consistente con el ``efecto civilizatorio'' de la
educación.

\textbf{H1b}: Entre individuos que sí participan en protestas, el efecto
de la educación se invierte: universitarios muestran mayor justificación
de violencia en manifestaciones comparado con individuos de menor
educación.

La explicación de lo anterior radica en que la educación fomenta un
pensamiento político más sofisticado, pero este opera de forma distinta
según la participación. Los no-participantes utilizan esta capacidad
para reforzar su adhesión a la democracia no-violenta y a normas
abstractas de tolerancia. Por el contrario, los participantes emplean
esa misma sofisticación para elaborar marcos ideológicos que les
permiten legitimar tácticamente la violencia como un instrumento
político válido en situaciones de protesta puntuales, sin necesariamente
abandonar sus valores democráticos generales.

\subsection{Participación como
transformación}\label{participaciuxf3n-como-transformaciuxf3n}

La literatura clásica sobre participación política, anclada en el modelo
de recursos (Verba et al., 1995), ha interpretado históricamente la
acción política como el resultado de características preexistentes y
recursos disponibles. Desde este punto de vista, la participación es un
acto de selección racional: quienes poseen más educación, tiempo y
dinero tienen mayor probabilidad de involucrarse políticamente. Este
enfoque, de fuerte raigambre conductista, presupone que las actitudes
políticas ---como la confianza institucional, la orientación democrática
o las creencias sobre la violencia--- son estables, exógenas y previas a
la acción. Dicho de otro modo, la gente participa porque ya tiene
ciertas actitudes, y no porque la participación las transforme.

Sin embargo, este modelo lineal resulta insuficiente para explicar las
dinámicas de los ciclos de alta contención política, donde la protesta
adquiere una intensidad disruptiva y emocional que excede los patrones
habituales de movilización. En estos contextos, la participación no se
reduce a un comportamiento expresivo ni a una estrategia instrumental,
sino que constituye una experiencia socializadora que reconfigura las
orientaciones cognitivas, afectivas y morales de los individuos (Passy
\& Monsch, 2019). La literatura reciente ha comenzado a concebir la
participación como un proceso transformador: no solo refleja
predisposiciones políticas, sino que las produce, modifica y radicaliza
(Blühdorn \& Deflorian, 2021; McAdam, 1989). Así, la acción colectiva
deja de ser una mera consecuencia de las actitudes para convertirse en
un espacio donde se aprenden nuevas formas de interpretar el conflicto,
se redefinen los límites de la legitimidad y se reconfigura el sentido
moral de la acción política.

En este sentido, la protesta puede entenderse como un laboratorio moral
y cognitivo en el que los individuos confrontan de manera directa los
límites del orden político y las narrativas dominantes sobre justicia,
legalidad y violencia. La participación, especialmente en su forma de
alto riesgo, constituye una experiencia liminal en el sentido que
plantea Victor Turner (Wels et al., 2011): un punto de inflexión
biográfico en que se suspenden temporalmente las jerarquías normativas y
emergen nuevas formas de sentido. Estas experiencias no solo alteran los
marcos interpretativos de los participantes, sino que pueden redefinir
su identidad política y su evaluación moral del uso de la violencia
(Giugni, 2004; Vestergren et al., 2018).

\subsubsection{De selección a
socialización}\label{de-selecciuxf3n-a-socializaciuxf3n}

El giro conceptual que desplaza la participación del terreno de la
selección al de la socialización tiene su punto de partida en el trabajo
seminal de McAdam (1989) sobre las consecuencias biográficas del
activismo. McAdam aborda una pregunta metodológicamente desafiante: ¿los
activistas desarrollan actitudes distintas porque participaron, o
participaron porque ya las tenían? Para resolver este dilema del sesgo
de autoselección, el autor estudió el proyecto Freedom Summer de 1964
---una campaña de alto riesgo para registrar votantes afroamericanos en
Mississippi--- comparando a los voluntarios que efectivamente
participaron con un grupo de control compuesto por los ``no-shows'', es
decir, personas aceptadas en el proyecto pero que finalmente no
asistieron. Ambos grupos compartían las mismas motivaciones iniciales,
recursos y orientación política, lo que permitió aislar el efecto causal
de la experiencia participativa en sí misma.

Los resultados fueron contundentes: veinte años después, quienes
participaron seguían mostrando niveles significativamente más altos de
involucramiento político, y además habían experimentado transformaciones
duraderas en su identidad, trayectorias ocupacionales y proyectos de
vida. No se trataba de un episodio transitorio, sino de un evento que
``dejó una huella indeleble'' (McAdam, 1989, p.~756). Desde entonces,
una vasta literatura empírica ha documentado las consecuencias
biográficas de la participación, mostrando que el activismo transforma
las disposiciones políticas y morales de quienes lo experimentan
(Giugni, 2004; De Vydt \& Ketelaars, 2020; Passy \& Monsch, 2019). En
este marco, la protesta no solo es una práctica política, sino un
proceso de aprendizaje moral y cognitivo que reconfigura cómo los
individuos entienden la justicia, la autoridad y la violencia.

\subsubsection{Mecanismos de
transformación}\label{mecanismos-de-transformaciuxf3n}

La transformación biográfica inducida por la participación no ocurre de
manera automática; depende de mecanismos situacionales y relacionales
que median entre la experiencia y el cambio actitudinal. La literatura
ha identificado dos mecanismos principales: (1) la exposición a nuevos
marcos cognitivos y (2) la experiencia directa con la represión (Passy
\& Monsch, 2019; Crossley, 2003; Beckwith, 2025; McAdam \& Brandt,
2009).

En primer lugar, los movimientos sociales no son simples agregadores de
demandas, sino productores de significado (Snow \& Benford, 1988). A
través del trabajo de encuadre (framing), los movimientos elaboran
esquemas interpretativos que permiten a los individuos comprender,
diagnosticar y moralizar el conflicto. Este proceso involucra tres
dimensiones: (a) diagnóstico (qué y quién causa el problema), (b)
pronóstico (cómo puede resolverse), y (c) motivación (por qué actuar).
La participación inmersa en este entorno simbólico no solo refuerza
marcos previos, sino que puede provocar una transformación de marco
(frame transformation), es decir, un cambio radical en la forma en que
el individuo entiende la realidad social.

Durante el estallido social chileno, por ejemplo, muchos jóvenes
universitarios experimentaron una resignificación del uso de la
violencia en la protesta. Aquello que antes aparecía como un tabú
normativo ---efecto del aprendizaje institucional y del discurso
civilizatorio de la educación--- fue rearticulado dentro de un marco de
justicia moral que la redefinía como ``autodefensa legítima'' o
``resistencia necesaria''. Estos nuevos marcos no se imponen por mera
ideología, sino porque adquieren credibilidad empírica: se ajustan a la
experiencia concreta del participante, que presencia o sufre la
violencia estatal y la traduce en evidencia vivida de un orden injusto
(Snow \& Benford, 1988).

El segundo mecanismo se refiere a la vivencia corporal y emocional del
conflicto. La represión estatal, al producir experiencias de injusticia
procedimental (Tyler, 2006), tiene un efecto doble: erosiona la
legitimidad del Estado y valida las narrativas del movimiento. La teoría
de la justicia procedimental (Tyler \& Blader, 2003) sostiene que la
legitimidad de la autoridad depende menos de los resultados y más del
modo en que ejerce su poder ---particularmente del trato justo, el
respeto y la neutralidad percibidos. Cuando individuos, especialmente
con mayores niveles educativos, experimentan un trato arbitrario, la
legitimidad estatal se desmorona, generando un reencuadre moral del
conflicto. Lo que antes era ``violencia ilegítima'' pasa a ser
``violencia defensiva'', y lo que antes era ``orden público'' se
transforma en ``violencia estructural del Estado''.

Ambos mecanismos ---la reinterpretación cognitiva y la experiencia
emocional de injusticia--- se articulan en una secuencia dinámica: la
represión proporciona la evidencia empírica que valida los nuevos
marcos, y estos, a su vez, legitiman moralmente respuestas más
confrontacionales.

\subsubsection{Heterogeneidad del
efecto}\label{heterogeneidad-del-efecto}

No obstante, esta transformación no es homogénea. Como advierte Giugni
(2004), los efectos de la participación son heterogéneos y socialmente
mediados. La intensidad del cambio depende del tipo de experiencia
(positiva o negativa), del riesgo percibido, de la trayectoria previa y,
crucialmente, de la posición social y educativa del participante. La
literatura ha tendido a tratar a ``los activistas'' como una categoría
homogénea, ignorando cómo la posición social, el género o la educación
modulan la experiencia del activismo (Passy \& Monsch, 2019). Pero el
aprendizaje moral derivado de la protesta no es universal: está
estructuralmente filtrado por las disposiciones y capitales previos de
los individuos.

Una dimensión particularmente relevante de esta heterogeneidad se
refiere a la temporalidad de los efectos. Evidencia reciente sobre el
caso chileno sugiere que la exposición a la violencia política tiene
efectos diferenciados según el momento en que se miden. Rivera y autores
(2025), en su estudio sobre el estallido social chileno, encuentra que
la exposición directa a la represión policial genera un incremento
significativo en la justificación de la violencia política en el corto
plazo, particularmente entre manifestantes que experimentaron formas
intensas de coerción estatal. Sin embargo, este efecto tiende a
atenuarse con el paso del tiempo, sugiriendo que los shocks emocionales
y cognitivos producidos por eventos de alta tensión no necesariamente se
consolidan en transformaciones actitudinales duraderas.

De manera consistente, Disi Pavlic et al.~(2025) documentan una
trayectoria similar al analizar las consecuencias de largo plazo del
ciclo de protestas 2019-2020 en Chile. Sus resultados muestran que, si
bien la participación en manifestaciones incrementó inicialmente la
aceptación de tácticas confrontacionales, estos efectos se disipan
progresivamente en el período post-estallido. Los autores argumentan que
el retorno a la normalidad institucional, la fatiga movilizatoria y la
recomposición de las rutinas cotidianas operan como mecanismos de
``enfriamiento'' que revierten parcialmente las transformaciones
cognitivas inducidas por la protesta. Estos hallazgos introducen una
complejidad crucial: los efectos de la participación no solo son
heterogéneos entre grupos, sino también inestables a lo largo del
tiempo. En contextos de crisis política aguda, como el estallido social
chileno, la intensidad del conflicto puede producir efectos poderosos
pero transitorios, especialmente cuando las condiciones estructurales
que sostienen la movilización ---redes activistas, repertorios de
protesta, marcos de justificación--- se debilitan. Esto sugiere que la
transformación biográfica documentada en estudios como el de McAdam
(1989) puede depender no solo de la experiencia participativa en sí,
sino de la continuidad temporal y la integración comunitaria del
activismo.

En este punto se sitúa el aporte de esta tesis. La hipótesis central es
que los efectos transformadores de la participación no son uniformes,
sino que dependen de la interacción entre socialización educativa y
experiencia de protesta. La educación proporciona la capacidad cognitiva
para elaborar justificaciones morales sofisticadas; la participación, en
cambio, provee las condiciones emocionales y simbólicas que hacen
necesaria esa elaboración. El resultado es una reconfiguración
bidireccional de los marcos morales: quienes participan reinterpretan la
violencia estatal como ilegítima y la violencia de los manifestantes
como legítima. Donde, considerando lo anterior, se puede esperar que en
H3:

\textbf{H2a}: Universitarios que participan en protestas muestran mayor
justificación de la violencia ejercida por manifestantes, en comparación
con universitarios no participantes.

\textbf{H2b}: Los mismos universitarios participantes muestran menor
justificación de la violencia ejercida por el Estado, en comparación con
universitarios no participantes.

Se sugiere que la participación en protestas no sería un reflejo pasivo
de actitudes preexistentes, sino un proceso de reaprendizaje moral y
político, donde los individuos más educados ---precisamente por su
sofisticación cognitiva--- son los más capaces de reformular
coherentemente sus principios normativos en función de la experiencia.
De este modo, la acción colectiva se convierte en el espacio donde se
rearticulan las tensiones entre educación, desigualdad estructural y
legitimidad de la violencia política.

\subsection{El caso chileno: Del Malestar Estructural a la
Justificación}\label{el-caso-chileno-del-malestar-estructural-a-la-justificaciuxf3n}

\subsubsection{La ruptura del pacto
social}\label{la-ruptura-del-pacto-social}

El estudio del ciclo de protesta chileno iniciado en octubre de 2019
resulta crucial no solo por su magnitud histórica, sino porque
representa el colapso del pacto social de la post-transición y ofrece un
laboratorio crítico para analizar la relación entre desigualdad,
educación y violencia política. Chile no experimentó una mera
aceleración de tendencias previas, sino una ruptura tectónica en la
convivencia democrática. Según los datos del Observatorio de Conflictos
(COES, 2020), el último trimestre de 2019 registró más de 2.700 eventos
contenciosos, una cifra que multiplicó por nueve el promedio histórico
de conflictividad observado en la década anterior.

Este fenómeno se distingue no solo por su masividad, sino por la
centralidad que adquirió la violencia como repertorio de acción y
expresión política. Durante el estallido, la proporción de protestas con
presencia de violencia superó el 40\%, un salto cualitativo respecto a
los ciclos previos (COES, 2020). Más significativo aún para el análisis
de las actitudes políticas es el vacío de conducción orgánica que
caracterizó al movimiento: a diferencia de las movilizaciones
estudiantiles de 2011 (COES, 2020; Donoso et al., 2023), donde los
actores y petitorios eran claros, en 2019 el 68\% de las acciones
contenciosas no presentó una demanda articulada o identificable. Este
escenario de anomia y desborde institucional valida la necesidad de
estudiar cómo la ciudadanía reconfigura sus marcos morales y su
justificación de la violencia cuando los canales tradicionales de
resolución de conflictos se perciben agotados. En este sentido, el caso
chileno ilustra cómo la tríada de violencia, pobreza y falta de
oportunidades educativas, si no se aborda de manera integral, genera
ciclos de desigualdad estructural que perpetúan el conflicto social
(Varlik et al 2025).

\subsubsection{Crisis de legitimidad y la dinámica de la violencia
intergrupal}\label{crisis-de-legitimidad-y-la-dinuxe1mica-de-la-violencia-intergrupal}

Para comprender por qué la violencia se volvió un recurso aceptable para
amplios sectores de la población, es fundamental analizar la interacción
dinámica entre manifestantes y fuerzas de orden. La violencia política
en este periodo no fue un fenómeno unidireccional, sino el resultado de
una crisis profunda de legitimidad institucional. La evidencia empírica
recolectada durante el conflicto muestra que la percepción de injusticia
procedimental en el actuar de Carabineros ---caracterizada por el uso
desmedido de la fuerza y el trato denigrante--- erosionó drásticamente
la autoridad moral de la policía (Gerber et al., 2023).

Existe una relación inversa y significativa entre legitimidad y
violencia: a menor legitimidad percibida de la policía, mayor es la
justificación de la violencia ejercida por los manifestantes como una
herramienta válida para el ``cambio social'' (Gerber et al., 2023). Este
hallazgo es crucial para la tesis, pues indica que la represión estatal,
lejos de restaurar el orden, generó un efecto rebote que validó
moralmente la radicalización. Al percibir a la autoridad como injusta e
ilegítima, la ciudadanía re-significó la violencia civil no como
delincuencia, sino como un acto de resistencia y reivindicación de
derechos. Así, Chile se configura en este periodo como un escenario de
violencia intergrupal recíproca, donde la violencia policial para el
control social y la violencia civil para el cambio político se
retroalimentaron, quebrando los diques normativos que tradicionalmente
contenían el conflicto.

\subsubsection{La paradoja educativa: De la promesa de movilidad a la
politización del
malestar}\label{la-paradoja-educativa-de-la-promesa-de-movilidad-a-la-politizaciuxf3n-del-malestar}

Respecto a la educación, el caso de Chile desafía las teorías clásicas
de la modernización que asocian linealmente la expansión educativa con
la pacificación social y el fortalecimiento democrático. Si bien el país
experimentó una masificación acelerada de la educación superior
---pasando de una cobertura bruta del 16,8\% en 1990 al 59\% en 2012---,
este proceso se desarrolló bajo una lógica de mercado radical que incubó
nuevos conflictos (Bellei et al., 2014). La expansión de la matrícula no
fue impulsada por el Estado, sino por la proliferación de instituciones
privadas y mecanismos de financiamiento como el Crédito con Aval del
Estado (CAE), lo que resultó en que el 78\% del gasto en educación
superior proviniera de las familias, la cifra más alta de la OCDE
(Bellei et al., 2014).

Esta estructura generó una ``paradoja del bienestar'': la educación, en
lugar de actuar como un igualador social, reprodujo la estratificación y
generó una pesada carga de deuda para hogares trabajadores y sectores
medios emergentes. Lejos de derivar en conformismo, esta tensión
transformó a los estudiantes en actores políticos críticos. Como señalan
Donoso y Somma (2019), el movimiento estudiantil de 2011 no sólo instaló
la educación en la agenda pública, sino que generó una
``repolitización'' de la ciudadanía, demostrando que los mayores niveles
educativos proveen los recursos cognitivos y cívicos necesarios para
desafiar el statu quo. Así, la educación en Chile operó como un
catalizador de la movilización, donde los sectores más educados no
actuaron como amortiguadores del conflicto, sino como puntas de lanza
que articularon un cuestionamiento estructural al modelo neoliberal.

\section{Datos y Métodos}\label{datos-y-muxe9todos}

\subsection{Data}\label{data}

La investigación utiliza los datos del Estudio Longitudinal Social de
Chile (ELSOC), una encuesta panel implementada por el Centro de Estudios
de Conflicto y Cohesión Social (COES) que recoge información sobre la
población adulta urbana del país. La encuesta iene como propósito
examinar las actitudes, percepciones y comportamientos de las personas
frente a temas de conflicto y cohesión social. Su diseño de panel
permite seguir a los mismos individuos a lo largo del tiempo, ofreciendo
una mirada única sobre la evolución de la sociedad chilena. La encuesta
se ha aplicado anualmente desde 2016, con excepción de 2020 debido a la
pandemia de COVID-19, acumulando siete olas de datos (2016, 2017, 2018,
2019, 2021, 2022 y 2023).

ELSOC utiliza un muestreo probabilístico por conglomerados y
multietápico, que cubre tanto los principales centros urbanos como
ciudades medianas y pequeñas del país. El marco muestral se estratificó
proporcionalmente según el tamaño de la población urbana (en seis
categorías), seleccionando aleatoriamente hogares dentro de 1.067
manzanas censales. La población objetivo incluye a hombres y mujeres de
18 a 75 años residentes en viviendas particulares.

La encuesta se ha aplicado anualmente desde 2016, con excepción de 2020
debido a la pandemia de COVID-19, acumulando siete olas de datos (2016,
2017, 2018, 2019, 2021, 2022 y 2023).

Para los análisis de la investigación, y tras aplicar un criterio de
inclusión de encuestados que hayan participado en al menos tres olas, se
dispone de una muestra analítica de 20.007 observaciones anidadas en
3.666 individuos. La encuesta, sus manuales metodológicos y bases de
datos se encuentran disponibles públicamente en el portal de COES
\url{https://coes.cl/elsoc/} y en el repositorio de Harvard Dataverse
\url{https://dataverse.harvard.edu/dataverse/elsoc}.

\subsection{Variables}\label{variables}

\subsubsection{Variables dependientes: Justificación de violencia
política}\label{variables-dependientes-justificaciuxf3n-de-violencia-poluxedtica}

Para la medición de actitudes hacia la violencia política se
construyeron dos índices que capturan la justificación de violencia
ejercida por diferentes tipos de actores en contextos políticos
específicos. Esta distinción entre tipos de violencia según el actor que
la ejerce es teóricamente crucial, dado que la hipótesis de
reconfiguración bidireccional (H2) predice que la participación en
protestas genera legitimación diferenciada: aumenta la justificación de
violencia ejercida por manifestantes pero reduce la justificación de
violencia ejercida por fuerzas del orden.

El \textbf{Índice de Justificación de Violencia en Protestas}
(\texttt{justif\_violencia\_protesta}) se compone del promedio de dos
ítems que miden el grado de justificación de acciones disruptivas
ejercidas por actores sociales en contextos de movilización:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Que un grupo de trabajadores en huelga bloquee la calle con barricadas
  para exigir el cumplimiento de sus derechos laborales
\item
  Que estudiantes lancen piedras a carabineros en una marcha por la
  educación del país
\end{enumerate}

Cada ítem se midió en una escala Likert de 5 puntos desde 1 = ``Nunca se
justifica'' hasta 5 = ``Siempre se justifica''. El índice se calculó
como el promedio aritmético de los cinco ítems cuando el encuestado
respondió al menos tres de ellos, resultando en una escala continua de 1
a 5 donde valores más altos indican mayor justificación de violencia en
protestas. La consistencia interna del índice es satisfactoria, con un
alfa de Cronbach de 0.82 en la muestra analítica, indicando que los
ítems capturan un constructo latente común.

Adicionalmente, se relevaron otras variables sobre la justificación de
acciones disruptivas/violentas en contextos de protesta, tales como:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Que algunas personas incendien o dañen inmobiliario público para
  exigir cambios sociales.
\item
  Que algunas personas incendien o dañen medios de transporte (metro,
  microbuses, paraderos) para exigir cambios sociales.
\item
  Que algunas personas incendien o dañen negocios y locales comerciales
  para exigir cambios sociales.
\end{enumerate}

Estos indicadores, que igualmente reflejan la justificación de la
violencia, se encuentran disponibles sólo en la ola del año 2019 y
fueron considerados para algunos análisis descriptivos (presentes en los
anexos) con el fin de ampliar la perspectiva del fenómeno.

Para el \textbf{Índice de Justificación de Violencia Estatal}
(\texttt{justif\_violencia\_estatal}): Se compone del promedio de dos
ítems que miden justificación de violencia ejercida por Carabineros de
Chile (fuerzas de ley y orden) en contextos de control del orden
público:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Que Carabineros use la violencia para reprimir una manifestación
  pacífica
\item
  Que Carabineros desaloje a la fuerza a las personas que se toman
  edificios o universidades
\end{enumerate}

Cada ítem se midió en la misma escala de 5 puntos. El índice se calculó
como el promedio de ambos ítems (requiriendo respuesta en al menos uno),
resultando igualmente en una escala continua de 1 a 5. La correlación
entre ambos ítems es r = 0.58 (p \textless{} 0.001), indicando que miden
aspectos relacionados pero distinguibles de actitudes hacia violencia
policial.

Es importante notar que estos dos índices capturan formas
conceptualmente distintas de violencia política: violencia ``desde
abajo'' ejercida por actores sociales movilizados versus violencia
``desde arriba'' ejercida por agentes estatales. Como muestra la matriz
de correlación en la Tabla 1, ambos índices están negativamente
correlacionados (r = -0.23, p \textless{} 0.001), sugiriendo que
justificar un tipo de violencia tiende a asociarse con menor
justificación del otro tipo, aunque la correlación no es perfecta. Esta
distinción empírica valida la estrategia de analizar ambos tipos de
violencia por separado.

\subsubsection{Variables independientes
principales}\label{variables-independientes-principales}

Para la educación del encuestado se operacionalizó una variable
categórica de cinco niveles basada en el nivel educacional más alto
alcanzado:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Educación media (secundaria) completa o menos
\item
  Técnica superior incompleta (estudios terciarios no universitarios
  iniciados pero no completados)
\item
  Técnica superior completa (título técnico profesional o similar)
\item
  Universitaria incompleta (estudios universitarios iniciados pero no
  completados)
\item
  Universitaria completa (título universitario de pregrado o posgrado)
\end{enumerate}

Esta categorización se trata como factor no ordenado, utilizando
``educación media completa o menos'' como categoría de referencia. La
decisión de no tratar educación como variable ordinal responde a
evidencia previa que sugiere que los efectos de educación sobre
actitudes políticas no son necesariamente lineales, y que existen
diferencias cualitativas importantes entre educación técnica y
universitaria que van más allá de ``años de escolaridad'' (Nie et al.,
1996).

Para la \textbf{Participación en protestas} se elaboró una variable
dicotómica que indica si el encuestado participó en manifestaciones,
marchas o protestas durante los últimos 12 meses (1 = Sí participó, 0 =
No participó). Esta medición está basada en la pregunta: \emph{``Durante
los últimos 12 meses, ¿ha participado en manifestaciones o marchas?''¨}.
Esta variable captura participación reportada retrospectivamente y, por
tanto, está sujeta a posibles sesgos de recuerdo y deseabilidad social,
aunque existe evidencia previa que sugiere que el reporte de
participación en protestas tiene razonable validez cuando el período de
referencia es relativamente corto (Walgrave \& Wouters, 2014).

\subsubsection{Variables de Control}\label{variables-de-control}

Todos los modelos incluyen las siguientes variables de control para
reducir confusión y mejorar la precisión de las estimaciones:

\begin{itemize}
\item
  Edad: En años al momento de cada ola (variable continua centrada en la
  media).
\item
  Género: Variable dicotómica (1 = Mujer, 0 = Hombre).
\item
  Ideología política: Escala de auto-posicionamiento ideológico de 0
  (extrema izquierda) a 10 (extrema derecha), estandarizada con media 0
  y desviación estándar 1.
\item
  Tiempo: Tendencia temporal lineal (ola codificada como 0-6) para
  controlar por cambios sistemáticos en las actitudes a lo largo del
  período de estudio (2016-2023), incluyendo el impacto del estallido
  social de 2019.
\end{itemize}

\subsection{Estrategia Analítica}\label{estrategia-analuxedtica}

La naturaleza longitudinal de los datos implica que observamos a los
mismos individuos en múltiples ocasiones a lo largo del tiempo. Esta
estructura de los datos ---donde las observaciones individuales de Nivel
1 (mediciones en el tiempo) están anidadas dentro de individuos de Nivel
2--- viola uno de los supuestos fundamentales de los modelos de
regresión estándar: la independencia de las observaciones (Snijders \&
Bosker, 2012). Es altamente probable que las respuestas de un mismo
individuo en diferentes olas estén correlacionadas, dado que capturan
características estables de esa persona (personalidad, valores
arraigados, experiencias formativas previas) que afectan sus actitudes
de manera consistente a lo largo del tiempo.

Ignorar esta dependencia temporal dentro de individuos llevaría a
estimaciones sesgadas (errores estándar demasiado pequeños), inflando
artificialmente la significancia estadística y conduciendo a
conclusiones inválidas (Raudenbush \& Bryk, 2002; Gelman \& Hill, 2007).
En este sentido, los modelos multinivel (también llamados modelos
jerárquicos lineales, modelos de efectos mixtos o modelos de componentes
de varianza) ofrecen una solución explícita a este problema al modelar
tanto la heterogeneidad entre individuos como la dependencia dentro de
individuos a lo largo del tiempo (Singer \& Willett, 2003). Como señalan
Hox et al.~(2017), estos modelos permiten descomponer la variación total
en sus componentes estructurales y estimar correctamente la
incertidumbre de los parámetros en presencia de dependencia
intra-grupal.

La ecuación general del modelo de Nivel 1 (observación en el tiempo) y
Nivel 2 (individuo) es:

\textbf{Nivel 1 (intra-individual)}

\[y_{tj} = \beta_{0j} + \beta_{1j} X_{tj} + \varepsilon_{tj}\]

donde:

\begin{itemize}
\tightlist
\item
  \(y_{tj}\): Justificación de la violencia para el individuo \(j\) en
  el tiempo \(t\).
\item
  \(X_{tj}\): Variables de nivel 1 (tiempo), como participación en
  protestas, edad, etc.
\item
  \(\varepsilon_{tj}\): Error residual a nivel de observación.
\end{itemize}

\textbf{Nivel 2 (inter-individual)}

\[\beta_{0j} = \gamma_{00} + \gamma_{01} Z_j + u_{0j}\]
\[\beta_{1j} = \gamma_{10}\]

donde:

\begin{itemize}
\tightlist
\item
  \(\gamma_{00}\): Intercepto general (gran media).
\item
  \(\gamma_{01}\): Efecto de predictores de nivel 2 (entre individuos).
\item
  \(\gamma_{10}\): Efecto fijo de predictores de nivel 1
  (intra-individuos).
\item
  \(Z_j\): Predictores que no varían en el tiempo (educación, género).
\item
  \(u_{0j}\): Efecto aleatorio del intercepto para el individuo \(j\).
\end{itemize}

\textbf{Modelo integrado}

\[y_{tj} = \gamma_{00} + \gamma_{01} Z_j + \gamma_{10} X_{tj} + \gamma_{20} t + u_{0j} + \varepsilon_{tj}\]

donde \(t\) representa el tiempo (ola de medición, codificada como 0, 1,
2, \ldots, 6 para las olas 2016-2023). Este modelo descompone la
varianza total en dos componentes: varianza entre individuos
(\(\sigma^2_u\), capturada por los interceptos aleatorios) y varianza
dentro de individuos a lo largo del tiempo (\(\sigma^2_\varepsilon\),
error residual). El coeficiente de correlación intraclúster (ICC)
cuantifica la proporción de varianza total atribuible a diferencias
entre individuos. El parámetro \(\gamma_{20}\) captura la tendencia
temporal lineal promedio en la justificación de violencia.

\subsubsection{Modelos con
interacción}\label{modelos-con-interacciuxf3n}

\textbf{Interacción entre Educación y Participación}

Para testear las hipótesis centrales de este estudio, que predicen que
los efectos de educación sobre justificación de violencia son
contingentes a la participación en protestas, se estiman modelos que
incluyen términos de interacción multiplicativos:

\[
\begin{aligned}
y_{tj} = \gamma_{00} + \sum_{k=1}^{4} \gamma_{0k} \text{Educación}_{kj} + \gamma_{10} \text{Participación}_{tj} + \sum_{k=1}^{4} \gamma_{1k} (\text{Educación}_{kj} \times \text{Participación}_{tj}) + \\
\gamma_{20} t + \text{Controles} + u_{0j} + \varepsilon_{tj}
\end{aligned}
\]

Dado que educación es una variable categórica con 5 niveles (4 dummies),
este modelo estima 4 coeficientes de interacción
(\(\gamma_{11}, \gamma_{12}, \gamma_{13}, \gamma_{14}\)), uno para cada
nivel educativo respecto a la categoría de referencia.

La interpretación de términos de interacción en modelos multinivel sigue
la lógica estándar: el coeficiente de interacción representa cuánto
cambia el efecto de la participación en protestas sobre la justificación
de violencia al pasar de una categoría educativa a otra. Los gráficos de
efectos marginales (predicted values) se utilizan para visualizar estas
interacciones de forma intuitiva.

\subsubsection{Elección de la distribución y función de
enlace}\label{elecciuxf3n-de-la-distribuciuxf3n-y-funciuxf3n-de-enlace}

La variable dependiente principal es el índice continuo de justificación
de violencia (escala 1-5). Aunque técnicamente esta variable es ordinal
(niveles discretos ordenados), su tratamiento como variable continua se
justifica por tres razones metodológicas y sustantivas. Primero, los
índices promedian respuestas de múltiples ítems (2 para violencia en
protestas, 2 para violencia estatal), lo que genera una distribución más
continua y aproximadamente normal en la muestra. Segundo, trabajos
previos en psicología y ciencias políticas han demostrado que escalas
Likert con 5 o más puntos pueden tratarse como continuas sin pérdida
sustantiva de información cuando se promedian múltiples ítems (Norman,
2010; Lubke \& Muthen, 2004). Tercero, el uso de variables continuas
permite interpretar los efectos en términos de cambios promedio en la
escala de justificación, lo que resulta más intuitivo y permite capturar
gradaciones sutiles en las actitudes.

Por tanto, los modelos principales se estiman mediante Modelos Lineales
Generalizados Mixtos (GLMM) con distribución gaussiana (normal) y
función de enlace identidad, incorporando interceptos aleatorios por
individuo para modelar la estructura jerárquica de los datos. Esta
especificación es equivalente a un modelo de regresión lineal multinivel
estándar y se estima mediante máxima verosimilitud restringida (REML),
que produce estimadores insesgados de los componentes de varianza en
muestras finitas (Raudenbush \& Bryk, 2002).

\subsection{Software y replicabilidad}\label{software-y-replicabilidad}

Todos los análisis estadísticos se realizaron en R (versión 4.3.1)
utilizando el paquete glmmTMB (Brooks et al., 2017) para la estimación
de modelos mixtos generalizados, ggeffects (Lüdecke, 2018) para el
cálculo de efectos marginales y predicciones ajustadas, y ggplot2
(Wickham, 2016) para la visualización de resultados. Los scripts de
análisis completos, incluyendo código para limpieza de datos,
construcción de variables, estimación de modelos y generación de
figuras, se encuentran disponibles en un repositorio público de GitHub
(https://github.com/renejcanales/protest\_effects), garantizando
transparencia y replicabilidad computacional completa de los hallazgos
reportados.

\section{Resultados}\label{resultados}

En el presente apartado se presentan los resultados de los factores que
moldean la justificación de la violencia en el contexto de la protesta
social en Chile.

\subsection{Estadísticos
Descriptivos}\label{estaduxedsticos-descriptivos}

\subsubsection{Justificación de violencia por nivel
educativo}\label{justificaciuxf3n-de-violencia-por-nivel-educativo}

Los patrones observados en la Table~\ref{tbl-justificacion-educ}
muestran una tendencia relevante. Entre quienes no participan en
protestas, un mayor nivel educativo tenderían a una menor justificación
de la violencia por parte de manifestaciones, con medias que bajan de
aproximadamente 1.90 a 1.80. Sin embargo, esta tendencia se invierte
para quienes sí participan: aquellos participantes con educación
universitaria muestran los niveles más altos de justificación,
alcanzando medias en torno a 2.29 y 2.27. Este efecto diferenciado de la
educación parece ser específico de la violencia en protestas, ya que, en
contraste, la justificación de la violencia estatal exhibe un patrón
mucho más estable, con una variación considerablemente menor entre los
distintos niveles educativos.

\begin{table}

\caption{\label{tbl-justificacion-educ}Justificación de violencia según
nivel educativo y participación en protestas}

\centering{

\centering\begingroup\fontsize{9}{11}\selectfont

\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{threeparttable}
\begin{tabular}{llccccc}
\toprule
\multicolumn{3}{c}{ } & \multicolumn{2}{c}{Viol. Protestas} & \multicolumn{2}{c}{Viol. Estatal} \\
\cmidrule(l{3pt}r{3pt}){4-5} \cmidrule(l{3pt}r{3pt}){6-7}
Educación & Participación & N & Media & DE & Media & DE\\
\midrule
\cellcolor{gray!10}{Media completa o menos} & \cellcolor{gray!10}{No participó} & \cellcolor{gray!10}{8139} & \cellcolor{gray!10}{1.71} & \cellcolor{gray!10}{0.83} & \cellcolor{gray!10}{1.87} & \cellcolor{gray!10}{1.02}\\
Media completa o menos & Participó & 671 & 2.15 & 0.98 & 1.65 & 0.94\\
\cellcolor{gray!10}{Téc. sup.incompleta} & \cellcolor{gray!10}{No participó} & \cellcolor{gray!10}{448} & \cellcolor{gray!10}{1.70} & \cellcolor{gray!10}{0.79} & \cellcolor{gray!10}{1.93} & \cellcolor{gray!10}{1.03}\\
Téc. sup.incompleta & Participó & 79 & 2.34 & 0.96 & 1.75 & 0.90\\
\cellcolor{gray!10}{Téc. sup.completa} & \cellcolor{gray!10}{No participó} & \cellcolor{gray!10}{2267} & \cellcolor{gray!10}{1.62} & \cellcolor{gray!10}{0.74} & \cellcolor{gray!10}{1.90} & \cellcolor{gray!10}{0.98}\\
\addlinespace
Téc. sup.completa & Participó & 446 & 2.15 & 0.98 & 1.59 & 0.82\\
\cellcolor{gray!10}{Univ. incompleta} & \cellcolor{gray!10}{No participó} & \cellcolor{gray!10}{739} & \cellcolor{gray!10}{1.75} & \cellcolor{gray!10}{0.78} & \cellcolor{gray!10}{1.89} & \cellcolor{gray!10}{0.97}\\
Univ. incompleta & Participó & 292 & 2.29 & 1.03 & 1.52 & 0.77\\
\cellcolor{gray!10}{Univ. completa} & \cellcolor{gray!10}{No participó} & \cellcolor{gray!10}{2192} & \cellcolor{gray!10}{1.64} & \cellcolor{gray!10}{0.77} & \cellcolor{gray!10}{1.96} & \cellcolor{gray!10}{0.98}\\
Univ. completa & Participó & 971 & 2.27 & 1.06 & 1.47 & 0.71\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: } 
\item Elaboración propia a partir de ELSOC (2016-2023). Escala 1-5 donde 1 = Nunca se justifica y 5 = Siempre se justifica
\end{tablenotes}
\end{threeparttable}}
\endgroup{}

}

\end{table}%

\subsubsection{Evolución temporal: Justificación de la Violencia y
Participación en protestas
(2016-2023)}\label{evoluciuxf3n-temporal-justificaciuxf3n-de-la-violencia-y-participaciuxf3n-en-protestas-2016-2023}

\begin{figure}[H]

\centering{

\includegraphics[width=0.85\linewidth,height=\textheight,keepaspectratio]{paper_files/figure-pdf/fig-evolucion-temporal-1.pdf}

}

\caption{\label{fig-evolucion-temporal}Evolución de la participación en
protestas 2016-2023}

\end{figure}%

El análisis de los patrones temporales de la
Figure~\ref{fig-evolucion-temporal} muestra un resultado coherente con
el contexto del ciclo de protesta observado. Para el 2019 -año del
estallido social- se registra el promedio más alto de participación en
protestas, reflejando la intensidad de la movilización. En el período
post-2019. Y, aunque disminuye desde su punto álgido en ese periodo, se
mantiene en niveles ligeramente superiores a los observados antes del
2019 hasta su caída entre 2021 y 2023, donde reporta su promedio más
bajo en todo el ciclo reportado.

\begin{figure}[H]

\centering{

\includegraphics[width=0.85\linewidth,height=\textheight,keepaspectratio]{paper_files/figure-pdf/fig-participacion-estratificada-1.pdf}

}

\caption{\label{fig-participacion-estratificada}Composición
sociodemográfica de participantes en protestas por año: cambios
estructurales post-estallido. Elaboración propia a partir de ELSOC.}

\end{figure}%

La Figure~\ref{fig-participacion-estratificada} revela la transformación
radical de las jerarquías morales en torno a la violencia política.
Pre-2019 (2016-2018), ambas formas de violencia se evaluaban con
criterios similares (brecha ±0.05 puntos), reflejando consenso
liberal-democrático donde violencia ``desde abajo'' y ``desde arriba''
se rechazaban por igual (\textasciitilde1.6-1.7). En 2019, la brecha se
invierte dramáticamente: violencia estatal fue justificada
\textasciitilde0.15 puntos más que violencia en protestas, reflejando
shock inicial y polarización ante el ``caos'' percibido.

Sin embargo, en el post-2019 (2022-2023) las líneas se cruzan
definitivamente: violencia en protestas pasa a ser justificada
\textasciitilde0.10-0.15 puntos más que violencia estatal, y esta brecha
se estabiliza. Este es el hallazgo crítico: el estallido generó una
reconfiguración permanente de jerarquías morales colectivas, donde
violencia táctica disruptiva se normaliza más que represión estatal.
Este patrón evidencia la reconfiguración bidireccional: el marco moral
dual emergente post-estallido redefine los límites de la acción política
legítima según quién ejerce la violencia y en qué contexto.

\begin{figure}[H]

\centering{

\includegraphics[width=0.85\linewidth,height=\textheight,keepaspectratio]{paper_files/figure-pdf/fig-estallido-1-1.pdf}

}

\caption{\label{fig-estallido-1}Comparación de justificación de
violencia antes (2016-2018) y después (2022-2023) del estallido social
por educación y participación}

\end{figure}%

La Figure~\ref{fig-estallido-1} presenta la evolución temporal de la
justificación de violencia por educación, comparando año a año los
niveles antes (2016-2018) y después (2022-2023) del estallido social de
octubre 2019, revelando patrones críticos sobre la permanencia de los
efectos del shock político.

Entre no participantes, se observa estabilidad relativa en el periodo
pre-2019, con niveles de justificación que oscilan entre
\textasciitilde1.5-1.8 para mayor educación y \textasciitilde1.7-2.0
para menor educación. En el periodo post-2019 (2022-2023), todos los
grupos educativos muestran un incremento moderado: universitarios
completos pasan de \textasciitilde1.5 a \textasciitilde1.8, mientras
educación básica/media se mantiene en el rango \textasciitilde1.8-2.0.
Entre participantes, el patrón muestra convergencia sostenida: desde
2016 hasta 2023, todos los niveles educativos mantienen justificaciones
moderadamente altas (\textasciitilde2.0-2.3) con intervalos de confianza
superpuestos, indicando que la experiencia de movilización iguala
actitudes independientemente del capital cultural. Crucialmente, las
brechas entre participantes y no participantes se mantienen consistentes
año tras año en el post-2019, evidenciando que el efecto de la
participación persiste establemente años después del estallido.

El contraste revela que entre los no participantes, se observa un salto
dramático entre 2018 y 2022 en todos los grupos educativos:
universitarios completos pasan de \textasciitilde1.3-1.5 (2016-2018) a
\textasciitilde1.9-2.0 (2022-2023). Este es el hallazgo más crítico: el
estallido no generó rechazo permanente a la represión estatal, sino que
normalizó su justificación incluso entre sectores privilegiados, y esta
normalización se mantiene estable en 2022 y 2023. Entre participantes,
el patrón se invierte completamente: todos los grupos educativos
muestran descensos sostenidos post-2019, pasando de
\textasciitilde1.8-2.0 (2016-2018) a \textasciitilde1.5-1.7 (2022-2023),
con universitarios completos manteniendo niveles bajos estables
(\textasciitilde1.4). La trayectoria año a año confirma que la
experiencia directa de represión durante el estallido generó un efecto
de ``deslegitimación experiencial'' permanente entre manifestantes,
observable consistentemente en ambos años post-estallido.

Los datos revelan que el estallido de 2019 no fue un shock temporal sino
un punto de inflexión permanente que reconfiguró estructuralmente los
marcos morales duales. La visualización año por año demuestra que la
divergencia entre participantes y no participantes no es fluctuación
transitoria sino polarización estable: mientras participantes
desarrollan rechazo duradero a violencia estatal pero mantienen
justificación de violencia en protestas, no participantes experimentan
patrones divergentes según capital cultural. Estos marcos permanecen
estables 3-4 años después del evento crítico, cristalizando la hipótesis
de polarización bidireccional permanente.

\subsection{Estadísticos
exploratorios}\label{estaduxedsticos-exploratorios}

\begin{table}

\caption{\label{tbl-modelos-principales}Modelos principales de
justificación de violencia}

\centering{

\begin{center}
\scalebox{0.8}{
\begin{tabular}{l c c}
\toprule
 & Modelo 1 & Modelo 2 \\
\midrule
Educación (Ref.= Media completa o menos) &               &               \\
                                         &               &               \\
\quad Tecnica Incompleta                 & $-.096$       & $.106$        \\
                                         & $(.050)$      & $(.059)$      \\
\quad Tecnica Completa                   & $-.121^{***}$ & $.030$        \\
                                         & $(.025)$      & $(.029)$      \\
\quad Universitaria Incompleta           & $-.054$       & $.011$        \\
                                         & $(.038)$      & $(.044)$      \\
\quad Universitaria Completa             & $-.105^{***}$ & $.023$        \\
                                         & $(.025)$      & $(.029)$      \\
Controles                                &               &               \\
                                         &               &               \\
\quad Participa en protestas             & $.357^{***}$  & $-.133^{***}$ \\
                                         & $(.020)$      & $(.023)$      \\
\quad Edad                               & $-.009^{***}$ & $.004^{***}$  \\
                                         & $(.001)$      & $(.001)$      \\
\quad Mujer                              & $-.028$       & $-.133^{***}$ \\
                                         & $(.018)$      & $(.021)$      \\
\quad Ideología                          & $-.028^{***}$ & $.055^{***}$  \\
                                         & $(.003)$      & $(.004)$      \\
Año (Ref.= 2016)                         &               &               \\
                                         &               &               \\
\quad 2017                               & $-.043$       & $-.107^{***}$ \\
                                         & $(.023)$      & $(.026)$      \\
\quad 2018                               & $-.108^{***}$ & $.011$        \\
                                         & $(.021)$      & $(.024)$      \\
\quad 2019                               & $.049^{*}$    & $-.401^{***}$ \\
                                         & $(.021)$      & $(.024)$      \\
\quad 2022                               & $-.101^{***}$ & $-.128^{***}$ \\
                                         & $(.023)$      & $(.026)$      \\
\quad 2023                               & $-.099^{***}$ & $-.002$       \\
                                         & $(.023)$      & $(.026)$      \\
\midrule
Num. obs.                                & $3383$        & $3383$        \\
Num. groups: idencuesta                  & $.134$        & $.197$        \\
AIC                                      & $36296.693$   & $40375.594$   \\
BIC                                      & $15110$       & $15103$       \\
\bottomrule
\multicolumn{3}{l}{\scriptsize{*** p < 0.001; ** p < 0.01; * p < 0.05}}
\end{tabular}
}
\caption{Statistical models}
\label{}
\end{center}

}

\end{table}%

La Table~\ref{tbl-modelos-principales} presenta dos modelos principales
que guían el análisis de este estudio. El Modelo 1 examina los efectos
de educación y participación en protestas sobre violencia en protestas,
y el Modelo 2 evalúa esos mismos efectos sobre violencia estatal. Ambos
modelos incluyen efectos aleatorios por individuo y controles por edad,
género, ideología y año.

Los resultados revelan patrones diferenciados según el tipo de
violencia. Para violencia en protestas, la participación muestra un
efecto positivo consistente, incrementando la justificación en
aproximadamente 0.36 puntos. En contraste, para violencia estatal, el
efecto directo de la participación es negativo, aunque altamente
significativo, evidenciando que quienes participan en protestas no
justifican más la represión policial.

Los controles operan de manera consistente: ideología de derecha reduce
justificación de violencia en protestas (\textasciitilde-0.03 por punto
en la escala) pero la incrementa para violencia estatal
(\textasciitilde+0.05). Las mujeres rechazan más la violencia estatal
(\textasciitilde-0.13) sin diferencias en violencia en protestas. El año
2019 muestra el contraste más dramático: incremento moderado en
justificación de violencia en protestas pero fuerte caída en
justificación de violencia estatal (\textasciitilde-0.40), reflejando el
impacto del estallido social en las actitudes hacia la represión
policial.

\begin{table}

\caption{\label{tbl-modelos-interaccion}Modelos de interacción para
justificación de violencia}

\centering{

\begin{center}
\scalebox{0.8}{
\begin{tabular}{l c c}
\toprule
 & Model 1b & Model 2b \\
\midrule
Educación (Ref.= Media completa o menos)  &               &               \\
                                          &               &               \\
\quad Tecnica Incompleta                  & $-.133^{*}$   & $.095$        \\
                                          & $(.053)$      & $(.062)$      \\
\quad Tecnica Completa                    & $-.134^{***}$ & $.032$        \\
                                          & $(.026)$      & $(.031)$      \\
\quad Universitaria Incompleta            & $-.067$       & $.038$        \\
                                          & $(.041)$      & $(.048)$      \\
\quad Universitaria Completa              & $-.126^{***}$ & $.059$        \\
                                          & $(.026)$      & $(.031)$      \\
Participa en Protestas                    & $.265^{***}$  & $-.042$       \\
                                          & $(.035)$      & $(.040)$      \\
Interacciones Educación                   &               &               \\
                                          &               &               \\
\quad Tecnica Incompleta × Protesta       & $.281^{*}$    & $.021$        \\
                                          & $(.111)$      & $(.127)$      \\
\quad Tecnica Completa × Protesta         & $.129^{*}$    & $-.063$       \\
                                          & $(.056)$      & $(.064)$      \\
\quad Universitaria Incompleta × Protesta & $.109$        & $-.159^{*}$   \\
                                          & $(.068)$      & $(.078)$      \\
\quad Universitaria Completa × Protesta   & $.133^{**}$   & $-.183^{***}$ \\
                                          & $(.048)$      & $(.055)$      \\
Controles                                 &               &               \\
                                          &               &               \\
\quad Age                                 & $-.009^{***}$ & $.004^{***}$  \\
                                          & $(.001)$      & $(.001)$      \\
\quad Woman                               & $-.028$       & $-.133^{***}$ \\
                                          & $(.018)$      & $(.021)$      \\
\quad Ideología                           & $-.027^{***}$ & $.055^{***}$  \\
                                          & $(.003)$      & $(.004)$      \\
Año (Ref.= 2016)                          &               &               \\
                                          &               &               \\
\quad 2017                                & $-.043$       & $-.107^{***}$ \\
                                          & $(.023)$      & $(.026)$      \\
\quad 2018                                & $-.108^{***}$ & $.011$        \\
                                          & $(.021)$      & $(.024)$      \\
\quad 2019                                & $.049^{*}$    & $-.402^{***}$ \\
                                          & $(.021)$      & $(.024)$      \\
\quad 2022                                & $-.101^{***}$ & $-.129^{***}$ \\
                                          & $(.023)$      & $(.026)$      \\
\quad 2023                                & $-.098^{***}$ & $-.005$       \\
                                          & $(.023)$      & $(.026)$      \\
\midrule
Num. obs.                                 & $3383$        & $3383$        \\
Num. groups: idencuesta                   & $.133$        & $.197$        \\
AIC                                       & $36291.927$   & $40370.252$   \\
BIC                                       & $15110$       & $15103$       \\
\bottomrule
\multicolumn{3}{l}{\scriptsize{*** p < 0.001; ** p < 0.01; * p < 0.05}}
\end{tabular}
}
\caption{Statistical models}
\label{}
\end{center}

}

\end{table}%

Los modelos de la Table~\ref{tbl-modelos-interaccion} revelan que el
efecto de participación varía significativamente según nivel educativo.
Para violencia en protestas, las interacciones entre educación y
participación son positivas, indicando que el efecto legitimador de
participar es más fuerte entre personas educadas. Una persona con nivel
universitario completo participante incrementa su justificación 0.40
puntos versus 0.27 para educación media, evidenciando la ``paradoja
educativa'': la educación reduce justificación entre no participantes
(-0.13***) pero amplifica el efecto de la participación.

Para violencia estatal, el patrón se invierte completamente. Las
interacciones son negativas (universitario incompleto: -0.16\emph{;
universitario completo: -0.18}**), indicando que solo la combinación de
educación universitaria + participación genera rechazo significativo a
la represión (efecto total: -0.22 puntos). La educación sola (+0.06, ns)
o participación sola (-0.04, ns) no bastan; es su interacción la que
activa el rechazo diferenciado.

La reconfiguración bidireccional (legitimar protestas, rechazar
represión) es más nítida entre universitarios participantes, confirmando
que el marco moral dual requiere la combinación crítica de educación
superior y experiencia directa de movilización.

\begin{figure}[H]

\centering{

\includegraphics[width=0.85\linewidth,height=\textheight,keepaspectratio]{paper_files/figure-pdf/fig-efectos-marginales-1.pdf}

}

\caption{\label{fig-efectos-marginales}Efectos marginales de la
participación en protestas sobre justificación de violencia según
educación}

\end{figure}%

La Figure~\ref{fig-efectos-marginales} visualiza los efectos marginales
de participación según educación, permitiendo evaluar directamente las
hipótesis sobre efectos diferenciales.

En el Panel A, se observa como todos los niveles educativos muestran
efectos positivos significativos para justificación de la violencia en
protestas, con magnitudes que varían de +0.27 (educación media) a +0.55
(técnico superior incompleto). Crucialmente, el efecto legitimador es
más fuerte entre educación técnica-superior (+0.55) y universitaria
(+0.40) que entre educación media (+0.27), evidenciando que la educación
amplifica (no reduce) el efecto de participación, invirtiendo el efecto
civilizatorio entre quienes se movilizan.

Por otro lado, el Panel B muestra que solo universitarios tienen efectos
negativos significativos para justificación de la violencia estatal
(-0.20 a -0.22), mientras educación media y técnica exhiben efectos
nulos (puntos grises en línea roja). En este sentido, universitarios
participantes tenderían a legitimar violencia en protestas (+0.40) a la
vez que rechazan la violencia estatal (-0.22).

\subsubsection{El ``Efecto Paradoja'' de la
Educación}\label{el-efecto-paradoja-de-la-educaciuxf3n}

\begin{figure}[H]

\centering{

\includegraphics[width=0.85\linewidth,height=\textheight,keepaspectratio]{paper_files/figure-pdf/fig-paradoja-educacion-1.pdf}

}

\caption{\label{fig-paradoja-educacion}Análisis de interacción:
Educación × Participación en Protestas}

\end{figure}%

La Figure~\ref{fig-paradoja-educacion} revela la ``paradoja educativa''
predicha en las hipótesis H1a y H1b. El Panel A muestra que la educación
reduce la justificación de violencia entre observadores externos (línea
roja descendente de \textasciitilde1.95 en educación media a
\textasciitilde1.75 en universitaria completa), consistente con el
efecto civilizatorio. Sin embargo, la educación invierte su efecto
(línea azul ascendente de \textasciitilde2.20 en educación media a
\textasciitilde2.35 en técnico superior incompleto, luego
\textasciitilde2.30 en universitaria completa), evidenciando que
personas más educadas elaboran marcos ideológicos que legitiman la
violencia táctica en contextos de movilización. El Panel B cuantifica
esta inversión: la magnitud de la interacción es máxima en técnico
superior incompleto (+0.55) y universitaria incompleta (+0.45),
confirmando que la ``paradoja'' es más pronunciada en niveles educativos
medios-altos donde convergen capital cultural y experiencia de
movilización.

\subsection{Reconfiguración Bidireccional de la justificación de la
violencia (Violencia en Protestas vs Violencia
Estatal)}\label{reconfiguraciuxf3n-bidireccional-de-la-justificaciuxf3n-de-la-violencia-violencia-en-protestas-vs-violencia-estatal}

Los modelos con interacciones (Modelo 1b y Modelo 2b) revelan la
dinámica bidireccional predicha en H3a-H3b (universitarios). H3a se
confirma plenamente: para violencia en protestas, la educación
universitaria reduce justificación entre no participantes
(\(-0.13***\)), pero participación genera incremento (\(+0.27***\))
magnificado por interacciones positivas con educación superior (técnico
superior incompleto: \(+0.28*\); universitario completo: \(+0.13**\)),
anulando el efecto civilizatorio. H3b se confirma plenamente: para
violencia estatal, el patrón se invierte completamente: educación sola
(\(+0.06\), ns) y participación sola (\(-0.04\), ns) no generan efectos,
pero sus interacciones negativas producen rechazo significativo entre
universitarios (incompleto: \(-0.16*\); completo: \(-0.18***\)),
evidenciando que solo la combinación educación universitaria +
participación activa el marco crítico hacia represión.

Los controles confirman el impacto del estallido 2019: incremento
moderado en justificación de protestas (\(+0.05*\)) pero colapso en
violencia estatal (\(-0.40***\)), transformando radicalmente actitudes
hacia represión policial. Ideología opera en direcciones opuestas:
derecha reduce justificación de protestas (\(-0.03***\)) pero incrementa
la de violencia estatal (\(+0.05***\)). Las mujeres rechazan más
violencia estatal (\(-0.13***\)) sin diferencias en protestas. Este
patrón confirma que la reconfiguración bidireccional predicha en H3a-H3b
(legitimar protestas, rechazar represión) es completa solo entre quienes
combinan educación universitaria con experiencia directa de
movilización, cristalizando el marco moral dual sofisticado.

\begin{figure}[H]

\centering{

\includegraphics[width=0.85\linewidth,height=\textheight,keepaspectratio]{paper_files/figure-pdf/fig-bidireccional-tiempo-1.pdf}

}

\caption{\label{fig-bidireccional-tiempo}Evolución temporal de la
reconfiguración bidireccional según educación y participación
(2016-2023)}

\end{figure}%

La Figure~\ref{fig-bidireccional-tiempo} visualiza la dinámica temporal
de la reconfiguración bidireccional predicha en H3a-H3b, mostrando que
el marco moral dual requiere tanto educación como participación. Entre
no participantes (fila superior), las líneas amarilla (protestas) y azul
(estatal) permanecen paralelas y cercanas en todos los niveles
educativos, confirmando que sin participación no hay reconfiguración
bidireccional pese al efecto civilizatorio universitario (H1a opera pero
H3b no se activa).

Entre participantes (fila inferior), emergen tres patrnoes que permiten
evaluar H3a-H3b. Educación media/técnica muestra rechazo parcial de
H3a-H3b: elevación de justificación de protestas (+0.27 a +0.55,
confirmando H3a) pero sin rechazo significativo a violencia estatal
(rechazando H3b), evidenciando legitimación táctica sin marco crítico
hacia represión. Técnico superior incompleto alcanza la mayor
radicalización en protestas (\textgreater2.2 en 2019, \(+0.28*\)) pero
mantiene líneas paralelas, confirmando que capital técnico sin
socialización universitaria no genera la diferenciación normativa
predicha en H3b.

El marco dual completo predicho en H3a-H3b se confirma exclusivamente en
universitarios participantes: (1) línea amarilla elevada sostenida
(\textasciitilde2.0-2.1), anulando el efecto civilizatorio y confirmando
H3a; (2) colapso dramático de línea azul en 2019 desde
\textasciitilde1.75 a \textasciitilde1.35, el nivel más bajo de la
figura (\(-0.40***\)), confirmando H3b; (3) divergencia máxima post-2019
con brecha de \textasciitilde0.7 puntos, evidenciando permanencia del
marco dual. Este patrón confirma que H3a y H3b se cumplen conjuntamente
solo bajo la combinación crítica de educación universitaria +
experiencia de movilización, cristalizando el marco normativo dual
sofisticado.

\section{Discusión}\label{discusiuxf3n}

Como bien se planteó al comienzo, el presente trabajo parte de una
interrogante fundamental surgida tras el estallido social de 2019: ¿Por
qué y cómo sectores tradicionalmente asociados a la moderación política
y el apego institucional llegaron a legitimar formas de violencia
política disruptiva? Los resultados obtenidos permiten desafiar las
concepciones lineales clásicas sobre la educación, proponiendo en su
lugar un modelo donde la participación en protestas actúa como un
mecanismo de activación y transformación que invierte los efectos
esperados del capital cultural.

\subsection{La Paradoja de la Educación: Del Efecto Civilizatorio al
Amplificador
Cognitivo}\label{la-paradoja-de-la-educaciuxf3n-del-efecto-civilizatorio-al-amplificador-cognitivo}

La literatura clásica de la sociología política ha sostenido largamente
la hipótesis del ``efecto civilizatorio'' (Lipset, 1959; Nie et al.,
1996), bajo la premisa de que la educación fomenta la tolerancia y el
rechazo a la violencia como medio de acción. Los hallazgos de este
estudio confirman esta relación, pero con una salvedad crítica: es
cierta sólo para quienes observan la política desde lejos.

Entre los no participantes, efectivamente, a mayor educación, menor es
la justificación de la violencia. Sin embargo, al incorporar la
experiencia de la participación en protestas, la relación se invierte
dramáticamente, confirmando la Hipótesis 1 (H1). Los universitarios que
participan no solo justifican la violencia más que sus pares no
movilizados, sino que alcanzan los niveles más altos de justificación de
toda la muestra, superando incluso a los sectores con menor educación
formal.

Este hallazgo sugiere que la educación no opera como un freno moral
universal, sino como un amplificador cognitivo condicional. La
``sofisticación cognitiva'' que otorga la educación superior no
determina qué pensar (rechazo automático a la violencia), sino que
provee herramientas complejas para procesar la experiencia política.
Cuando esa experiencia implica confrontación con el Estado y
participación en un ciclo de alta intensidad como el de 2019, los
individuos educados utilizan su capital cultural no para moderarse, sino
para elaborar marcos interpretativos sofisticados (Snow \& Benford,
1988) que legitiman la violencia táctica como un recurso de
``resistencia necesaria'' o ``autodefensa''.

Sin embargo, esta interpretación socializadora debe matizarse con una
consideración crítica sobre la dirección causal. Los resultados no
permiten descartar completamente una explicación alternativa basada en
selección: es posible que los universitarios que eligen participar en
protestas ya posean disposiciones actitudinales previas más radicales o
críticas hacia el orden institucional, y que estas diferencias
preexistentes ---no la participación per se--- expliquen parte de la
mayor justificación de violencia observada. En otras palabras, la
educación universitaria podría estar ``seleccionando'' y concentrando
individuos con predisposiciones políticas específicas que luego se
reflejan en su participación y actitudes, más que transformándolos
directamente a través de la experiencia de movilización.

El diseño de este estudio, con controles por individuo mediante efectos
aleatorios y variables de ideología política, mitiga parcialmente esta
preocupación al aislar la variación within-person en el tiempo. No
obstante, la posibilidad de heterogeneidad no observada (por ejemplo,
``radicalismo político'' latente, redes sociales activistas, o
exposición previa a violencia policial) que correlacione simultáneamente
con educación universitaria, decisión de participar, y justificación de
violencia, no puede eliminarse por completo sin un diseño experimental o
cuasi-experimental más robusto. Futuras investigaciones podrían explorar
esta cuestión mediante diseños longitudinales que midan actitudes antes
y después de la primera participación en protestas, o mediante técnicas
de emparejamiento que comparen participantes y no participantes con
características observables idénticas.

Adicionalmente, la interpretación sobre ``sofisticación cognitiva''
requiere una distinción analítica crucial que los datos actuales no
permiten explorar completamente: la diferencia entre quienes están
activamente insertos en contextos universitarios (estudiantes activos) y
quienes poseen credenciales universitarias pero han abandonado los
campus (graduados o desertores). La literatura sobre socialización
universitaria (Gurin et al., 2002; Hurtado et al., 2012) sugiere que el
efecto formativo de la educación superior no reside únicamente en la
acumulación de capital cultural abstracto, sino en la inmersión
prolongada en espacios de deliberación política, diversidad ideológica,
y activismo estudiantil que caracterizan la vida en campus.

Si la ``amplificación cognitiva'' opera principalmente a través de la
socialización política que ocurre en las universidades ---donde
convergen debates críticos, organizaciones estudiantiles, y redes de
activismo---, entonces es esperable que los estudiantes activos exhiban
patrones cualitativamente diferentes a los universitarios graduados que
han transitado hacia el mercado laboral y han salido de esos espacios de
efervescencia política. Los primeros no solo poseen herramientas
cognitivas para procesar la protesta, sino que están inmersos en
ecologías sociales donde la participación en movilizaciones es
normalizada, discutida, y organizada colectivamente. Los segundos, en
cambio, aunque hayan adquirido capital cultural universitario, ya no
participan de esos espacios de socialización continua y podrían mostrar
efectos atenuados.

Esta distinción es especialmente relevante en el contexto chileno, donde
el movimiento estudiantil universitario ha sido históricamente un actor
protagónico de la protesta social (2006, 2011, 2019). Futuras
investigaciones deberían desagregar la categoría ``universitario'' entre
estudiantes activos, graduados recientes, y graduados hace más de cinco
años, permitiendo evaluar si el efecto de amplificación es más intenso
entre quienes permanecen en el campus, decae con el tiempo tras la
graduación, o persiste como un efecto permanente del credencialismo
educativo independiente del contexto institucional.

Así, la participación política rompe el dique del efecto civilizatorio.
El universitario movilizado no se ``des-civiliza''; más bien,
re-moraliza la violencia, dotándola de un sentido político que la hace
compatible con sus valores democráticos abstractos, resolviendo la
disonancia cognitiva mediante una justificación situada y táctica. No
obstante, esta transformación podría estar condicionada tanto por
procesos de socialización experiencial (el efecto causal de participar)
como por procesos de auto-selección (quiénes eligen participar) y
socialización institucional continua (quiénes permanecen en contextos
universitarios activos), mecanismos que este estudio no puede desenredar
completamente pero que representan avenidas críticas para investigación
futura.

\subsection{La Reconfiguración Bidireccional y el Marco Moral
Dual}\label{la-reconfiguraciuxf3n-bidireccional-y-el-marco-moral-dual}

Finalmente, y quizás el hallazgo más sustantivo para la comprensión del
conflicto chileno actual, es la confirmación de una reconfiguración
bidireccional de las actitudes. Contrario a la idea de que el estallido
generó una ``anomia'' generalizada o una validación de toda forma de
violencia, los datos muestran la emergencia de un marco moral dual
altamente sofisticado, especialmente entre los participantes educados.

La participación genera simultáneamente un aumento en la justificación
de la violencia de los manifestantes y una disminución aguda en la
justificación de la violencia estatal. Este patrón destruye la
correlación positiva que solía existir entre ambos tipos de violencia en
periodos de normalidad (donde quien rechazaba la violencia, rechazaba
toda violencia).

El estudio demuestra que los manifestantes, y en particular quienes
combinan educación universitaria con participación activa, operan bajo
una lógica de deslegitimación selectiva durante el momento más álgido
del conflicto. En 2019, mientras validan la violencia disruptiva como
herramienta política legítima (probablemente amparados en la falta de
respuesta institucional), retiran dramáticamente la legitimidad al uso
de la fuerza por parte de Carabineros. Esto es consistente con las
teorías de justicia procedimental (Tyler, 2006): la experiencia directa
de represión percibida como injusta o desproporcionada no lleva a la
sumisión, sino que erosiona temporalmente la autoridad moral del Estado,
haciendo que su violencia sea vista como ilegítima y la violencia propia
como defensiva.

Sin embargo, la temporalidad del efecto revela una dinámica más compleja
que una fractura permanente. Los datos post-2019 (olas 2022-2023)
muestran una convergencia progresiva entre ambos tipos de violencia
entre los participantes: mientras la justificación de violencia en
protestas decrece desde sus niveles máximos de 2019, la justificación de
violencia estatal aumenta gradualmente, reduciendo la brecha
bidireccional que había alcanzado su punto máximo durante el estallido.
Esta convergencia post-crisis sugiere que el marco moral dual no se
consolidó como una nueva subjetividad política permanente, sino que
respondió de manera reactiva al contexto político específico de 2019,
retrocediendo parcialmente cuando la intensidad del conflicto disminuyó.

Este patrón temporal es consistente con modelos de ``efectos de
contexto'' donde crisis políticas agudas generan realineamientos
actitudinales temporales que se atenúan una vez que el momento de
efervescencia colectiva declina (Snow \& Moss, 2014). La reducción de la
brecha bidireccional post-2019 entre participantes educados sugiere que,
si bien la experiencia de movilización generó una transformación
profunda en el momento, esta no se cristalizó en una ruptura permanente
del contrato social. En cambio, tanto participantes como no
participantes han experimentado un proceso de ``normalización''
posterior al estallido, aunque partiendo de posiciones diferenciadas:
los participantes reducen su legitimación de violencia en protestas pero
incrementan su tolerancia a la represión estatal, convergiendo hacia
niveles más cercanos a los observados antes de 2019.

No obstante, es importante señalar que la convergencia no implica un
retorno completo al statu quo ante. Las trayectorias de 2022-2023 aún
mantienen diferencias respecto al período pre-2019, y la experiencia del
estallido ha dejado una marca identitaria en los participantes,
particularmente en los sectores más educados. La investigación demuestra
que, durante el momento crítico de 2019, la violencia política fue
legitimada esencialmente por los sectores más educados e integrados
entre quienes participaron, desafiando las lecturas tradicionales que
atribuyen la violencia a la marginalidad. Sin embargo, esta legitimación
fue predominantemente coyuntural, respondiendo al contexto específico de
represión policial y crisis institucional, más que consolidándose como
una transformación cultural permanente de las reglas morales sobre el
uso de la fuerza.

\section{Conclusiones}\label{conclusiones}

El presente estudio surge de la necesidad de comprender un fenómeno
contraintuitivo observado a partir del ciclo contencioso chileno, y que
se insentificó en la discusión tras el estallido social de 2019: la
creciente justificación de la violencia política bajo el alero de
ciertos sectores que tradicionalmente se sitúan como garantes de la
moderación democrática. A través de un análisis multinivel que integró
educación y participación en protestas, esta investigación ha logrado
tensionar la presunta linealidad con la que se tratan estas actitudes,
revelando una dinámica compleja de reconfiguración moral y política.

En primer lugar, respecto al rol de la educación, se concluye que la
hipótesis clásica del ``efecto civilizatorio'' es insuficiente para
explicar el comportamiento político en contextos de alta conflictividad.
Si bien los datos confirman que, en ausencia de movilización, la
educación superior actúa como un factor de moderación y rechazo a la
violencia, esta relación se invierte radicalmente cuando se incorpora la
experiencia de la participación. Se ha demostrado que la educación opera
como un amplificador cognitivo condicional: lejos de inmunizar al
individuo contra la radicalización, el capital cultural provee a los
participantes de marcos interpretativos sofisticados que permiten
re-significar la violencia de protesta no como un acto delictual, sino
como una herramienta política legítima de resistencia. Así, los
manifestantes con educación universitaria no se ``des-civilizan'', sino
que utilizan sus recursos cognitivos para validar tácticamente la
disrupción.

No obstante, esta conclusión debe matizarse reconociendo que los diseños
observacionales no permiten descartar completamente explicaciones
alternativas basadas en selección: es posible que los universitarios que
eligen participar ya posean predisposiciones políticas más críticas o
radicales, y que estas diferencias preexistentes expliquen parte de la
mayor justificación observada. Adicionalmente, el concepto de
``amplificación cognitiva'' requiere una distinción que los datos
actuales no capturan: la diferencia entre estudiantes activos
---inmersos en espacios universitarios de deliberación política y
activismo--- y graduados que han abandonado esos contextos de
socialización continua. Futuras investigaciones deberían explorar si el
efecto de amplificación es más intenso entre quienes permanecen en el
campus o si persiste como un efecto permanente del credencialismo
educativo independiente del contexto institucional.

En segundo lugar, comprobamos la existencia de una reconfiguración
bidireccional de la legitimidad que da lugar a un ``marco moral dual''
durante el momento más álgido del conflicto. Contrario a la idea de una
anomia generalizada, los participantes ---especialmente los más
educados--- no validaron la violencia de forma indiscriminada en 2019.
Por el contrario, desarrollaron un juicio selectivo: aumentaron la
justificación de la violencia ``desde abajo'' (protesta) al tiempo que
retiraron drásticamente la legitimidad a la violencia ``desde arriba''
(represión estatal). Este patrón, robusto en los modelos estadísticos
para el período del estallido, indica una fractura temporal profunda en
el contrato social, donde la autoridad del Estado perdió su monopolio
moral sobre el uso de la fuerza ante los ojos de la ciudadanía
movilizada. Sin embargo, la evidencia post-2019 sugiere que este marco
dual fue predominantemente reactivo al contexto específico de represión
y crisis institucional, más que una transformación cultural permanente.

Finalmente, esta investigación documenta una transformación
significativa pero compleja en la cultura política chilena durante el
estallido social. La legitimación de la violencia en 2019 no fue un
fenómeno exclusivo de la marginalidad o la falta de integración
sistémica. Por el contrario, fue un producto político elaborado
intensamente por los sectores más integrados y educados de la sociedad
que, transformados por la experiencia del conflicto, reescribieron
temporalmente las reglas de lo aceptable. Sin embargo, las mediciones
post-2019 (2022-2023) revelan una convergencia progresiva: la
justificación de violencia en protestas decrece desde sus niveles
máximos mientras la justificación de violencia estatal aumenta
gradualmente entre los participantes, reduciendo la brecha bidireccional
que había alcanzado su punto máximo durante el estallido.

Esta convergencia post-crisis sugiere que, si bien la experiencia de
movilización generó una reconfiguración profunda en el momento álgido
del conflicto, esta no se consolidó como una fractura permanente del
contrato social. En cambio, tanto participantes como no participantes
han experimentado un proceso de ``normalización'' posterior al
estallido, aunque las trayectorias 2022-2023 aún mantienen diferencias
respecto al período pre-2019. El hallazgo central permanece: durante el
momento crítico de 2019, fueron los sectores más educados e integrados
quienes legitimaron más intensamente la violencia disruptiva, desafiando
las lecturas elitistas tradicionales. No obstante, esta legitimación
respondió predominantemente al contexto específico de represión policial
y crisis institucional, más que a una transformación cultural permanente
de las gramáticas morales sobre el uso de la fuerza política. Esto es
algo que futuros estudios podrían profundizar a partir de un enfoque
causal, cubriendo las limitaciones del presente trabajo.

\section{Bibliografía}\label{bibliografuxeda}

Acemoglu, D., Johnson, S., Robinson, J. A., \& Pierre Yared. (2005).
From Education to Democracy? The American Economic Review, 95(2), 44-49.
JSTOR.

Adam-Troian, J., Wagner-Egger, P., Motyl, M., Arciszewski, T., Imhoff,
R., Zimmer, F., Klein, O., Babinska, M., Bangerter, A., Bilewicz, M.,
Blanuša, N., Bovan, K., Bužarovska, R., Cichocka, A., Çelebi, E.,
Delouvée, S., Douglas, K.M., Dyrendal, A., Gjoneska, B., Graf, S.,
Gualda, E., Hirschberger, G., Kende, A., Krekó, P., Krouwel, A.,
Lamberty, P., Mari, S., Milosevic, J., Panasiti, M.S., Pantazi, M.,
Petkovski, L., Porciello, G., Prims, J.P., Rabelo, A., Schepisi, M.,
Sutton, R.M., Swami, V., Thórisdóttir, H., Turjačanin, V., Zezelj, I.
and van Prooijen, J.-W. (2021), Investigating the Links Between Cultural
Values and Belief in Conspiracy Theories: The Key Roles of Collectivism
and Masculinity. Political Psychology, 42: 597-618.
https://doi.org/10.1111/pops.12716

Almond, G. A. \& Verba, S. (1963). The Civic Culture. Princeton
University Press; JSTOR. http://www.jstor.org/stable/j.ctt183pnr2

Altemeyer, B. (1998). The Other ``Authoritarian Personality''. En
Advances in Experimental Social Psychology (Vol. 30, pp.~47-92).
Elsevier. https://doi.org/10.1016/S0065-2601(08)60382-2

Amnistía, I. (2020). Ojos sobre Chile: Violencia policial y
responsabilidad de mando durante el estallido social (No.~AMR
22/3133/2020). https://www.amnesty.org

Araujo, K. (2022). The circuit of detachment in Chile: Understanding the
fate of a neoliberal laboratory. Cambridge University Press.
https://doi.org/10.1017/9781009310697

Arthur, J. A., \& Case, C. E. (1994). Race, class and support for police
use of force. Crime, Law and Social Change, 21(2), 167-182.
https://doi.org/10.1007/BF01307910

Ayoub, P. M., Page, D., \& Whitt, S. (2021). Pride amid Prejudice: The
Influence of LGBT+ Rights Activism in a Socially Conservative Society.
American Political Science Review, 115(2), 467-485.
https://doi.org/10.1017/S0003055420001082

Aytaç, S. E., Schiumerini, L., \& Stokes, S. (2017). Protests and
Repression in New Democracies. Perspectives on Politics, 15(1), 62-82.
https://doi.org/10.1017/S1537592716004138

Beckwith, K. (2025). Protest embodied: Enacting the goal, resisting the
clothing of the state. European Journal of Politics and Gender, 8(2),
385-405. https://doi.org/10.1332/25151088Y2025D000000076

Beeghley, L. (1986). Social class and political participation: A review
and an explanation. Sociological Forum, 1(3), 496-513.
https://doi.org/10.1007/BF01123942

Bellei, C., Cabalin, C., \& Orellana, V. (2014). The 2011 Chilean
student movement against neoliberal educational policies. Studies in
Higher Education, 39(3), 426-440.
https://doi.org/10.1080/03075079.2014.896179

Benford, R. D., \& Snow, D. A. (2000). Framing Processes and Social
Movements: An Overview and Assessment. Annual Review of Sociology, 26,
611-639. JSTOR.

Berinsky, A. J., \& Lenz, G. S. (2011). Education and Political
Participation: Exploring the Causal Link. Political Behavior, 33(3),
357-373. JSTOR.

Blühdorn, I., \& Deflorian, M. (2021). Politicisation beyond
post-politics: New social activism and the reconfiguration of political
discourse. Social Movement Studies, 20(3), 259-275.
https://doi.org/10.1080/14742837.2021.1872375

Bonner, M. D., \& Dammert, L. (2022). Constructing police legitimacy
during protests: Frames and consequences for human rights. Policing and
Society, 32(5), 629-645. https://doi.org/10.1080/10439463.2021.1957887

Bottero, W. (2004). Class Identities and the Identity of Class.
Sociology, 38(5), 985-1003. https://doi.org/10.1177/0038038504047182

Bourdieu, P. \& Passeron, J.C. (2019). La Reproducción: Elementos para
una Teoría Del Sistema Educativo. Siglo XXI Editores.

Branton, R., Martinez-Ebers, V., Carey, T. E., \& Matsubayashi, T.
(2015). Social Protest and Policy Attitudes: The Case of the 2006
Immigrant Rallies. American Journal of Political Science, 59(2),
390-402. JSTOR.

Brehm, J. W. (1966). A theory of psychological reactance. Academic
Press.

Brooks, M., E., Kristensen, K., Benthem, K., J. ,van, Magnusson, A.,
Berg, C., W., Nielsen, A., Skaug, H., J., Mächler, M., \& Bolker, B., M.
(2017). glmmTMB Balances Speed and Flexibility Among Packages for
Zero-inflated Generalized Linear Mixed Modeling. The R Journal, 9(2),
378. https://doi.org/10.32614/RJ-2017-066

Canales Cerón, M. (2022). La pregunta de Octubre: Fundación, apogeo y
crisis del Chile neoliberal (Primera edición). LOM ediciones.

Carrasco Paillamilla, S. F., \& Disi Pavlic, R. (2023). Predictors of
perceptions of human rights violations during the Chilean social
outburst of 2019. Frontiers in Psychology, 14, 1133428.
https://doi.org/10.3389/fpsyg.2023.1133428

Castillo, J. C., Miranda, D., \& Madero Cabib, I. (2013). Todos somos de
clase media: Sobre el estatus social subjetivo en Chile. Latin American
Research Review, 48(1), 155--173.

Castillo, J. C., Palacios, D., Joignant, A., \& Tham, M. (2015).
Inequality, Distributive Justice and Political Participation: An
Analysis of the Case of Chile. Bulletin of Latin American Research,
34(4), 486-502. https://doi.org/10.1111/blar.12369

Converse, P. (1972). Change in the American electorate. The human
meaning of social change/Russell Sage Foundation.

Cox, L., González, R., \& Le Foulon, C. (2024). The 2019 Chilean Social
Upheaval: A Descriptive Approach. Journal of Politics in Latin America,
16(1), 68-89. https://doi.org/10.1177/1866802X231203747

Crossley, N. (2003). From Reproduction to Transformation: Social
Movement Fields and the Radical Habitus. Theory, Culture \& Society,
20(6), 43-68. https://doi.org/10.1177/0263276403206003

Davenport, C. (1995). Multi-Dimensional Threat Perception and State
Repression: An Inquiry into Why States Apply Negative Sanctions.
American Journal of Political Science, 39(3), 683.
https://doi.org/10.2307/2111650

Davenport, C., Soule, S. A., \& Armstrong, D. A. (2011). Protesting
While Black? The Differential Policing of American Activism, 1960 to
1990. American Sociological Review, 76(1), 152-178. JSTOR.

De Vydt, M., \& Ketelaars, P. (2021). Linking consensus to action: Does
frame alignment amongst sympathizers lead to protest participation?
Social Movement Studies, 20(4), 439-458.
https://doi.org/10.1080/14742837.2020.1770071

della Porta, D. (Ed.). (2017). Global Diffusion of Protest: Riding the
Protest Wave in the Neoliberal Crisis. Amsterdam University Press;
JSTOR. http://www.jstor.org/stable/j.ctt1zkjxq0

della Porta, D. (2018). Radicalization: A Relational Perspective. Annual
Review of Political Science, 21(1), 461-474.
https://doi.org/10.1146/annurev-polisci-042716-102314

della Porta, D., \& Fillieule, O. (2007). Policing Social Protest. En D.
A. Snow, S. A. Soule, \& H. Kriesi (Eds.), The Blackwell Companion to
Social Movements (pp.~217-241). Blackwell Publishing
Ltd.~https://doi.org/10.1002/9780470999103.ch10

Dewey, J. (2024). Democracy and Education (N. Tampio, Ed.). Columbia
University Press. http://www.jstor.org/stable/10.7312/dewe21010

Disi Pavlic, R., Medel, R. M., Bargsted, M., \& Somma, N. M. (2025).
Justification of violence, ideological preferences, and exposure to
protests: Causal evidence from the 2019 Chilean social unrest. Social
Forces, soaf102. https://doi.org/10.1093/sf/soaf102

Drury, J., \& Reicher, S. D. (2018). The Conservative Crowd?: How
Participation in Collective Events Transforms Participants'
Understandings of Collective Action. En B. Wagoner, F. M. Moghaddam, \&
J. Valsiner (Eds.), The Psychology of Radical Social Change (1.a ed.,
pp.~11-28). Cambridge University Press.
https://doi.org/10.1017/9781108377461.003

Donoso, S. Somma, N. (2019). ``You taught us to give an opinion, now
learn how to listen'': The Manifold Political Consequences of Chile's
Student Movement. En Arce, M., Rice, R. (Eds), Protest and democracy
(pp.~145-172). Calgary: University of Calgary Press.

Dyrstad, K., \& Hillesund, S. (2020). Explaining Support for Political
Violence. The Journal of Conflict Resolution, 64(9), 1724-1753. JSTOR.

Earl, J. (2003). Tanks, Tear Gas, and Taxes: Toward a Theory of Movement
Repression. Sociological Theory, 21(1), 44-68. JSTOR.

Earl, J. (2022). Repression and Social Movements. En D. Della Porta, B.
Klandermans, D. McAdam, \& D. A. Snow (Eds.), The Wiley-Blackwell
Encyclopedia of Social and Political Movements (1.a ed., pp.~1-7).
Wiley. https://doi.org/10.1002/9780470674871.wbespm446.pub2

Elsässer, L., \& Schäfer, A. (2023). Political Inequality in Rich
Democracies. Annual Review of Political Science, 26(1), 469-487.
https://doi.org/10.1146/annurev-polisci-052521-094617

Fair, C. C., \& Shepherd, B. (2006). Who Supports Terrorism? Evidence
from Fourteen Muslim Countries. Studies in Conflict \& Terrorism, 29(1),
51-74. https://doi.org/10.1080/10576100500351318

Francisco, R. A. (1995). The Relationship between Coercion and Protest:
An Empirical Evaluation in Three Coercive States. The Journal of
Conflict Resolution, 39(2), 263-282. JSTOR.

Fryer, T. (2023). Do the political attitudes of students change during
their time in higher education? Higher Education, 86(3), 563-590.
https://doi.org/10.1007/s10734-022-00915-8

Gamson, W. A. (2002). Talking politics (Transferred to digital
printing). Cambridge Univ. Press.

Garcés, M. (2019). October 2019: Social Uprising in Neoliberal Chile.
Journal of Latin American Cultural Studies, 28(3), 483-491.
https://doi.org/10.1080/13569325.2019.1696289

Gerber, M. M., Carvacho, H., \& González, R. (2016). Development and
validation of a scale of support for violence in the context of
intergroup conflict (SVIC): The case of violence perpetrated by Mapuche
people and the police in Chile. International Journal of Intercultural
Relations, 51, 61-68. https://doi.org/10.1016/j.ijintrel.2016.01.004

Gerber, M. M., Figueiredo, A., Sáez, L., \& Orchard, M. (2023).
Legitimidad, Justicia y Justificación de la Violencia Intergrupal entre
Carabineros y Manifestantes en Chile. Psykhe (Santiago), 32.

Gerber, M. M., González, R., Carvacho, H., Jiménez-Moya, G., Moya, C.,
\& Jackson, J. (2018). On the justification of intergroup violence: The
roles of procedural justice, police legitimacy, and group identity in
attitudes toward violence among indigenous people. Psychology of
Violence, 8(3), 379-389. https://doi.org/10.1037/vio0000177

Gerber, M. M., \& Jackson, J. (2017). Justifying violence: Legitimacy,
ideology and public support for police use of force. Psychology, Crime
\& Law, 23(1), 79-95. https://doi.org/10.1080/1068316X.2016.1220556

Giugni, M. (2004). Social protest and policy change: Ecology,
antinuclear, and peace movements in comparative perspective. Rowman \&
Littlefield.

Goodwin, J., Jasper, J. M., \& Polletta, F. (Eds.). (2001). Passionate
politics: Emotions and social movements. The University of Chicago
Press.

Gubler, J. R., \& Selway, J. S. (2012). Horizontal Inequality,
Crosscutting Cleavages, and Civil War. Journal of Conflict Resolution,
56(2), 206-232. https://doi.org/10.1177/0022002711431416

Gutting, R. S. (2020). Contentious Activities, Disrespectful Protesters:
Effect of Protest Context on Protest Support and Mobilization Across
Ideology and Authoritarianism. Political Behavior, 42(3), 865-890.
https://doi.org/10.1007/s11109-018-09523-8

Hastie, B. (2007). Higher education and sociopolitical orientation: The
role of social influence in the liberalisation of students. European
Journal of Psychology of Education, 22(3), 259-274. JSTOR.

Hox, J. J., Moerbeek, M., \& Schoot, R. van de. (2017). Multilevel
analysis: Techniques and applications (Third edition). Routledge, Taylor
\& Francis Group. https://doi.org/10.4324/9781315650982

Hsiao, Y., \& Radnitz, S. (2021). Allies or Agitators? How Partisan
Identity Shapes Public Opinion about Violent or Nonviolent Protests.
Political Communication, 38(4), 479-497.
https://doi.org/10.1080/10584609.2020.1793848

Human, R. W. (2019, noviembre 26). Chile: Llamado urgente a una reforma
policial tras las protestas.
https://www.hrw.org/es/news/2019/11/26/chile-llamado-urgente-una-reforma-policial-tras-las-protestas

Jackson, J., Huq, A. Z., Bradford, B., \& Tyler, T. R. (2013).
Monopolizing force? Police legitimacy and public attitudes toward the
acceptability of violence. Psychology, Public Policy, and Law, 19(4),
479-497. https://doi.org/10.1037/a0033852

Jasper, J. M. (1998). The Emotions of Protest: Affective and Reactive
Emotions In and Around Social Movements. Sociological Forum, 13(3),
397-424. https://doi.org/10.1023/A:1022175308081

Joignant, A., \& Somma, N. M. (Eds.). (2024). Social Protest and
Conflict in Radical Neoliberalism: Chile, 2008--2020. Springer Nature
Switzerland. https://doi.org/10.1007/978-3-031-58132-8

Joignant, Alfredo \& Somma, Nicolás \& Garreton, Matias \& Campos, Tomás
\& Brennan, Tammy. (2020). INFORME ANUAL Observatorio de Conflictos
2020.

Jost, J. T., Glaser, J., Kruglanski, A. W., \& Sulloway, F. J. (2003).
Political conservatism as motivated social cognition. Psychological
Bulletin, 129(3), 339-375. https://doi.org/10.1037/0033-2909.129.3.339

Kam, C. D., \& Palmer, C. L. (2008). Reconsidering the Effects of
Education on Political Participation. The Journal of Politics, 70(3),
612-631. https://doi.org/10.1017/S0022381608080651

Ketchley, N., \& El-Rayyes, T. (2021). Unpopular Protest: Mass
Mobilization and Attitudes to Democracy in Post-Mubarak Egypt. The
Journal of Politics, 83(1), 291-305. https://doi.org/10.1086/709298

Koopmans, R. (1993). The Dynamics of Protest Waves: West Germany, 1965
to 1989. American Sociological Review, 58(5), 637.
https://doi.org/10.2307/2096279

Korpi, W. (1985). Power Resources Approach vs.~Action and Conflict: On
Causal and Intentional Explanations in the Study of Power. Sociological
Theory, 3(2), 31. https://doi.org/10.2307/202223

Krause, K. (2009). Beyond definition: Violence in a global perspective.
Global Crime, 10(4), 337-355. https://doi.org/10.1080/17440570903248270

Krueger, A. B., \& Malečková, J. (2003). Education, Poverty and
Terrorism: Is There a Causal Connection? The Journal of Economic
Perspectives, 17(4), 119-144. JSTOR.

Kruglanski, A. W., Gelfand, M. J., Bélanger, J. J., Sheveland, A.,
Hetiarachchi, M., \& Gunaratna, R. (2014). The Psychology of
Radicalization and Deradicalization: How Significance Quest Impacts
Violent Extremism. Political Psychology, 35(S1), 69-93.
https://doi.org/10.1111/pops.12163

Langton, K. P., \& Jennings, M. K. (1968). Political Socialization and
the High School Civics Curriculum in the United States. American
Political Science Review, 62(3), 852-867.
https://doi.org/10.2307/1953435

Lerner, M. J. (1980). The Belief in a Just World. En M. J. Lerner, The
Belief in a Just World (pp.~9-30). Springer US.
https://doi.org/10.1007/978-1-4899-0448-5\_2

Lindh, A., \& McCall, L. (2020). Class Position and Political Opinion in
Rich Democracies. Annual Review of Sociology, 46(1), 419-441.
https://doi.org/10.1146/annurev-soc-121919-054609

Lipset, S. M. (1959). Some Social Requisites of Democracy: Economic
Development and Political Legitimacy. American Political Science Review,
53(1), 69-105. Cambridge Core. https://doi.org/10.2307/1951731

Lubke, G. H., \& Muthén, B. O. (2004). Applying Multigroup Confirmatory
Factor Models for Continuous Outcomes to Likert Scale Data Complicates
Meaningful Group Comparisons. Structural Equation Modeling: A
Multidisciplinary Journal, 11(4), 514-534.
https://doi.org/10.1207/s15328007sem1104\_2

Lüdecke, D. (2018). ggeffects: Tidy Data Frames of Marginal Effects from
Regression Models. Journal of Open Source Software, 3(26), 772.
https://doi.org/10.21105/joss.00772

Luna, J. P. (2024). Disjointed Polarization in Chile's Enduring Crisis
of Representation. Latin American Politics and Society, 66(2), 72-101.
Cambridge Core. https://doi.org/10.1017/lap.2024.19

Maguire, E., Barak, M., Wells, W., \& Katz, C. (2020). Attitudes towards
the Use of Violence against Police among Occupy Wall Street Protesters.
Policing: A Journal of Policy and Practice, 14(4), 883-899.
https://doi.org/10.1093/police/pay003

Marx, G. T. (1998). Policing Protest: The Control of Mass Demonstrations
in Western Democracies (D. della Porta \& H. Reiter, Eds.; NED-New
edition, Vol. 6). University of Minnesota Press.
http://www.jstor.org/stable/10.5749/j.ctttv1tv

Mazumder, S. (2018). The Persistent Effect of U.S. Civil Rights Protests
on Political Attitudes. American Journal of Political Science, 62(4),
922-935. https://doi.org/10.1111/ajps.12384

McAdam, D. (1989). The Biographical Consequences of Activism. American
Sociological Review, 54(5), 744. https://doi.org/10.2307/2117751

McAdam, D., \& Brandt, C. (2009). Assessing the Effects of Voluntary
Youth Service: The Case of Teach for America. Social Forces, 88(2),
945-969. https://doi.org/10.1353/sof.0.0279

Medel, R. M., \& Somma, N. M. (2022). Represión policial y grupos de
protesta en Chile: Un estudio longitudinal. Revista de Sociología,
37(1). https://doi.org/10.5354/0719-529X.2022.68149

Muller, E. N., \& Weede, E. (1990). Cross-National Variation in
Political Violence: A Rational Action Approach. Journal of Conflict
Resolution, 34(4), 624-651. https://doi.org/10.1177/0022002790034004003

Muñoz, J., \& Anduiza, E. (2019). `If a fight starts, watch the crowd':
The effect of violence on popular support for social movements. Journal
of Peace Research, 56(4), 485-498.
https://doi.org/10.1177/0022343318820575

Nie, N. H., Junn, J., \& Stehlik-Barry, K. (1996). Education and
democratic citizenship in America. University of Chicago Press.

Norman, G. (2010). Likert scales, levels of measurement and the ``laws''
of statistics. Advances in Health Sciences Education, 15(5), 625-632.
https://doi.org/10.1007/s10459-010-9222-y

Onursal, D., Hobbs, A., \& Wells, C. (2024). Violence, what is it good
for? Waves of riotous-violent protest and democracy. Democratization,
31(6), 1272-1296. https://doi.org/10.1080/13510347.2024.2302544

Ortiz, I., Burke, S., Berrada, M., \& Saenz Cortés, H. (2022). World
Protests: A Study of Key Protest Issues in the 21st Century. Springer
International Publishing. https://doi.org/10.1007/978-3-030-88513-7

Østby, G. (2013). Inequality and political violence: A review of the
literature. International Area Studies Review, 16(2), 206-231.
https://doi.org/10.1177/2233865913490937

Pascarella, E. T., \& Terenzini, P. T. (1991). How college affects
students (First edition). Jossey-Bass Publishers.

Passy, F., \& Monsch, G. (2019). Biographical Consequences of Activism.
En D. A. Snow, S. A. Soule, H. Kriesi, \& H. J. McCammon (Eds.), The
Wiley Blackwell Companion to Social Movements (1.a ed., pp.~499-514).
Wiley. https://doi.org/10.1002/9781119168577.ch28

Pérez Ahumada, P., \& Andrade De La Horra, V. (2021). Clase, política y
percepción del conflicto de clases en Chile. Revista Temas Sociológicos,
29, 323-353. https://doi.org/10.29344/07196458.29.2938

Pérez Ahumada, P., \& Andrade, V. (2023). Class identity in times of
social mobilization and labor union revitalization: Evidence from the
case of Chile (2009--2019). Current Sociology, 71(6), 1040-1062.
https://doi.org/10.1177/00113921211056052

Pérez-Liñán, A. S., \& Pérez-Liñán, A. S. (2010). Presidential
impeachment and the new political instability in Latin America (1.
paperback ed). Cambridge University Press.

Persson, M. (2015). Education and Political Participation. British
Journal of Political Science, 45(3), 689-703.
https://doi.org/10.1017/S0007123413000409

Pleyers, G. (2023). El estallido chileno a la luz de la década global de
los movimientos sociales. Polis, 22(65).
http://dx.doi.org/10.32735/s0718-6568/2023-n65-1868

Polletta, F., \& Jasper, J. M. (2001). Collective Identity and Social
Movements. Annual Review of Sociology, 27(1), 283-305.
https://doi.org/10.1146/annurev.soc.27.1.283

Pratto, F., Sidanius, J., Stallworth, L. M., \& Malle, B. F. (1994).
Social dominance orientation: A personality variable predicting social
and political attitudes. Journal of Personality and Social Psychology,
67(4), 741-763. https://doi.org/10.1037/0022-3514.67.4.741

Raudenbush, S., \& Bryk, A. S. (2010). Hierarchical linear models:
Applications and data analysis methods (2. ed., {[}Nachdr.{]}). Sage
Publ.

Reinka, M. A., \& Leach, C. W. (2017). Race and Reaction: Divergent
Views of Police Violence and Protest against. Journal of Social Issues,
73(4), 768-788. https://doi.org/10.1111/josi.12247

Rivera, S., Severino, F., \& Visconti, G. (2025). Exposure to protests
and support for different forms of violence: Evidence from the 2019
social outburst in Chile. Research \& Politics, 12(3),
20531680251355242. https://doi.org/10.1177/20531680251355242

Rodríguez, Á., Peña, S., Cavieres, I., Vergara, M. J., Pérez, M.,
Campos, M., Peredo, D., Jorquera, P., Palma, R., Cortés, D., López, M.,
\& Morales, S. (2021). Ocular trauma by kinetic impact projectiles
during civil unrest in Chile. Eye, 35(6), 1666-1672.
https://doi.org/10.1038/s41433-020-01146-w

Ryan, W. (2010). Blaming the Victim. Knopf Doubleday Publishing Group.

Saavedra, P., \& Drury, J. (2019). Including political context in the
psychological analysis of collective action: Development and validation
of a measurement scale for subjective political openness. Journal of
Social and Political Psychology, 7(2), 665-694.
https://doi.org/10.5964/jspp.v7i2.1030

Sabucedo, J.-M., Dono, M., Alzate, M., \& Seoane, G. (2018). The
Importance of Protesters' Morals: Moral Obligation as a Key Variable to
Understand Collective Action. Frontiers in Psychology, Volume 9-2018.
https://www.frontiersin.org/journals/psychology/articles/10.3389/fpsyg.2018.00418

Siegel, H. (1981). Kohlberg, Moral Adequacy, and the Justification of
Educational Interventions. Educational Theory, 31(3-4), 275-284.
https://doi.org/10.1111/j.1741-5446.1981.tb00970.x

Simon, B., \& Klandermans, B. (2001). Politicized collective identity: A
social psychological analysis. American Psychologist, 56(4), 319-331.
https://doi.org/10.1037/0003-066X.56.4.319

Singer, J. D., \& Willett, J. B. (2003). Applied Longitudinal Data
Analysis: Modeling Change and Event Occurrence (1.a ed.). Oxford
University PressNew York.
https://doi.org/10.1093/acprof:oso/9780195152968.001.0001

Smolski, A. R. (2021). Class Struggle and Violence in Latin American
Cities. Latin American Perspectives, 48(1), 280-284.
https://doi.org/10.1177/0094582X19860470

Snow, D. A., \& Bedford, R. D. (1988). Ideology, Frame Resonance, and
Participant Mobilization. International social movement research, 1,
197-218.

Somma, N. M., Bargsted, M., Disi Pavlic, R., \& Medel, R. M. (2021). No
water in the oasis: The Chilean Spring of 2019--2020. Social Movement
Studies, 20(4), 495-502. https://doi.org/10.1080/14742837.2020.1727737

Stewart, F. (2005). Horizontal Inequalities: A Neglected Dimension of
Development. En UNU-WIDER, A. B. Atkinson, K. Basu, J. N. Bhagwati, D.
C. North, D. Rodrik, F. Stewart, J. E. Stiglitz, \& J. G. Williamson,
Wider Perspectives on Global Development (pp.~101-135). Palgrave
Macmillan UK. https://doi.org/10.1057/9780230501850\_5

Sunshine, J., \& Tyler, T. R. (2003). The Role of Procedural Justice and
Legitimacy in Shaping Public Support for Policing. Law \& Society
Review, 37(3), 513-548. JSTOR.

Taber, C. S., \& Lodge, M. (2012). MOTIVATED SKEPTICISM IN THE
EVALUATION OF POLITICAL BELIEFS (2006). Critical Review, 24(2), 157-184.
https://doi.org/10.1080/08913811.2012.711019

Tarrow, S. G.. (1998). Power in movement: Social movements and
contentious politics (2nd ed). Cambridge University Press.

Tenn, S. (2007). The Effect of Education on Voter Turnout. Political
Analysis, 15(4), 446-464. JSTOR.

Tertytchnaya, K., \& Lankina, T. (2020). Electoral Protests and
Political Attitudes under Electoral Authoritarianism. The Journal of
Politics, 82(1), 285-299. https://doi.org/10.1086/705815

Tetlock, P. E. (1986). A value pluralism model of ideological reasoning.
Journal of Personality and Social Psychology, 50(4), 819-827.
https://doi.org/10.1037/0022-3514.50.4.819

Thaler, K. M., Mueller, L., \& Mosinger, E. (2023). Framing Police
Violence: Repression, Reform, and the Power of History in Chile. The
Journal of Politics, 85(4), 1198-1213. https://doi.org/10.1086/724967

Thompson, B. L., \& Lee, J. D. (2004). Who Cares If Police Become
Violent? Explaining Approval of Police Use of Force Using a National
Sample. Sociological Inquiry, 74(3), 381-410.
https://doi.org/10.1111/j.1475-682X.2004.00097.x

Tilly, C. (Ed.). (1998). Durable inequality. University of California
Press.

Tilly, C. (2003). The Politics of Collective Violence (1.a ed.).
Cambridge University Press. https://doi.org/10.1017/CBO9780511819131

Tyler, D. H., Barak, M., Maguire, E. R., \& Wells, W. (2018). The
effects of procedural injustice on the use of violence against police by
Occupy Wall Street protesters. Police Practice and Research, 19(2),
138-152. https://doi.org/10.1080/15614263.2018.1418153

Tyler, T. R. (2006). Restorative Justice and Procedural Justice: Dealing
with Rule Breaking. Journal of Social Issues, 62(2), 307-326.
https://doi.org/10.1111/j.1540-4560.2006.00452.x

Tyler, T. R., \& Blader, S. L. (2003). The Group Engagement Model:
Procedural Justice, Social Identity, and Cooperative Behavior.
Personality and Social Psychology Review, 7(4), 349-361.
https://doi.org/10.1207/S15327957PSPR0704\_07

Klandermans, B. \& Van Stekelenburg, J. (2013). The social psychology of
protest. Current Sociology, 61(5-6), 886-905.
https://doi.org/10.1177/0011392113479314

Varlık, S., Akpınar, S., Akpınar, Ö., \& Görünü, R. M. (2025). Education
as an antidote to violence and social inequality. Humanities and Social
Sciences Communications. https://doi.org/10.1057/s41599-025-06192-x

Verba, S., Schlozman, K. L., \& Brady, H. E. (2002). Voice and equality:
Civic voluntarism in American politics (Nachdr.). Harvard Univ. Press.

Vestergren, S., Drury, J., \& Chiriac, E. H. (2018). How collective
action produces psychological change and how that change endures over
time: A case study of an environmental campaign. British Journal of
Social Psychology, 57(4), 855-877. https://doi.org/10.1111/bjso.12270

Wacquant, L. (2008). Ghettos and Anti-Ghettos: An Anatomy of the New
Urban Poverty. Thesis Eleven, 94(1), 113-118.
https://doi.org/10.1177/0725513608093280

Walgrave, S., \& Wouters, R. (2014). The Missing Link in the Diffusion
of Protest: Asking Others. American Journal of Sociology, 119(6),
1670-1709. JSTOR. https://doi.org/10.1086/676853

Wallace, S. J., Zepeda‐Millán, C., \& Jones‐Correa, M. (2014). Spatial
and Temporal Proximity: Examining the Effects of Protests on Political
Attitudes. American Journal of Political Science, 58(2), 433-448.
https://doi.org/10.1111/ajps.12060

Wasow, O. (2020). Agenda Seeding: How 1960s Black Protests Moved Elites,
Public Opinion and Voting. American Political Science Review, 114(3),
638-659. https://doi.org/10.1017/S000305542000009X

Weakliem, D. L. (2002). The Effects of Education on Political Opinions:
An International Study. International Journal of Public Opinion
Research, 14(2), 141-157. https://doi.org/10.1093/ijpor/14.2.141

Wels, H., Van Der Waal, K., Spiegel, A., \& Kamsteeg, F. (2011). Victor
Turner and liminality: An introduction. Anthropology Southern Africa,
34(1-2), 1-4. https://doi.org/10.1080/23323256.2011.11500002

Wolfinger, R. E., \& Rosenstone, S. J. (1980). Who votes? Yale
University Press.

Wright, E. O. (Ed.). (2005). Approaches to Class Analysis (1.a ed.).
Cambridge University Press. https://doi.org/10.1017/CBO9780511488900

Xu, D., \& Guo, J. (2023). In sight, in mind: Spatial proximity to
protest sites and changes in peoples' political attitudes. The British
Journal of Sociology, 74(1), 83-104.
https://doi.org/10.1111/1468-4446.12988

Zaller, J. R. (1992). The Nature and Origins of Mass Opinion (1.a ed.).
Cambridge University Press. https://doi.org/10.1017/CBO9780511818691

Zhu, A. Y. F., \& Chou, K. L. (2025). The Social Psychology of
Procedural Justice: Findings in Hong Kong. Political Behavior, 47(1),
1-17. https://doi.org/10.1007/s11109-024-09938-6

\section{Anexos}\label{anexos}

\subsection{Anexo A: Intracluster Correlation
Coefficient}\label{anexo-a-intracluster-correlation-coefficient}

\begin{table}[!h]
\centering\begingroup\fontsize{9}{11}\selectfont

\begin{tabular}{lcc}
\toprule
Variable dependiente & ICC & Varianza entre individuos\\
\midrule
\cellcolor{gray!10}{Justificación de violencia en protestas} & \cellcolor{gray!10}{0.24} & \cellcolor{gray!10}{24\%}\\
Justificación de violencia estatal & 0.24 & 24\%\\
\bottomrule
\end{tabular}
\endgroup{}
\end{table}

Como paso inicial, se estimaron los modelos nulos para ambas variables
de justificación de la violencia, incluyendo únicamente los interceptos
aleatorios por individuo. Los coeficientes de correlación intraclúster
(ICC) calculados a partir de estos modelos confirman la idoneidad del
enfoque multinivel.

Para la justificación de la violencia en protestas, el ICC es de 0.229,
indicando que un 24\% de la varianza total es atribuible a diferencias
sistemáticas y estables entre los individuos. Para la justificación de
la violencia estatal, el valor se repite, alcanzando el mismo ICC de
0.240 (un 24.0\% de varianza entre-sujetos).

En ambos casos, estos valores son sustanciales y confirman la existencia
de una fuerte interdependencia en los datos, validando la elección de
los modelos de efectos aleatorios.

\subsection{Anexo B: Índices de violencia
desagregados}\label{anexo-b-uxedndices-de-violencia-desagregados}

\begin{figure}[H]

\centering{

\includegraphics[width=0.85\linewidth,height=\textheight,keepaspectratio]{paper_files/figure-pdf/fig-componentes-violencia-1.pdf}

}

\caption{\label{fig-componentes-violencia}Evolución de componentes
específicos de justificación de violencia}

\end{figure}%

La Figure~\ref{fig-componentes-violencia} desagrega los índices en sus
componentes disponibles en todas las olas. El Panel A muestra las dos
formas de violencia en protestas medidas consistentemente: huelgas de
trabajadores y tomas estudiantiles. Ambas presentan una tendencia
ascendente hacia 2019, alcanzando su punto máximo ese año, seguido de un
descenso en los años posteriores. En específico, podemos ver que las
acciones disruptivas protagonizadas por trabajadores reciben una mayor
justificación -en promedio- que las perpetradas por estudiantes a lo
largo de todo el período.

El Panel B revela un patrón contrastante para la violencia estatal.
Ambas formas de represión policial (en marchas y desalojos de tomas)
muestran una caída pronunciada en 2019, alcanzando sus niveles más bajos
de justificación precisamente en el año del estallido social. Sin
embargo, en el período post-2019, se observa un aumento sostenido y
marcado de la justificación de violencia policial, divergiendo
claramente del patrón observado para la violencia en protestas que se
mantiene en niveles más bajos.

\begin{table}

\caption{\label{tbl-2019-participacion}Justificación de violencia en
2019 según participación: todas las variables}

\centering{

\centering\begingroup\fontsize{8}{10}\selectfont

\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}{lcccccccc}
\toprule
\multicolumn{1}{c}{ } & \multicolumn{1}{c}{ } & \multicolumn{5}{c}{Violencia en Protestas} & \multicolumn{2}{c}{Violencia Estatal} \\
\cmidrule(l{3pt}r{3pt}){3-7} \cmidrule(l{3pt}r{3pt}){8-9}
Participacion & N & Trabajadores & Estudiantes & Inmobiliario & Transporte & Locales & Carab. Marchas & Carab. Tomas\\
\midrule
\cellcolor{gray!10}{No participó} & \cellcolor{gray!10}{2301} & \cellcolor{gray!10}{2.12} & \cellcolor{gray!10}{1.32} & \cellcolor{gray!10}{1.18} & \cellcolor{gray!10}{1.15} & \cellcolor{gray!10}{1.11} & \cellcolor{gray!10}{1.46} & \cellcolor{gray!10}{1.78}\\
Participó & 840 & 2.92 & 1.96 & 1.71 & 1.58 & 1.40 & 1.18 & 1.37\\
\bottomrule
\multicolumn{9}{l}{\rule{0pt}{1em}\textit{Nota:}}\\
\multicolumn{9}{l}{\rule{0pt}{1em}Datos solo de 2019. Escala 1-5 donde 1 = Nunca se justifica.}\\
\end{tabular}}
\endgroup{}

}

\end{table}%

Respecto a la violencia estatal, los niveles de justificación son
similares a los de violencia en protestas (≈1.5-1.6). Crucialmente, la
Table~\ref{tbl-2019-participacion} muestra que quienes participaron en
protestas justifican más la violencia en todas sus formas comparado con
los no participantes, sugiriendo que incluso en un contexto de baja
justificación generalizada, la experiencia directa de movilización sigue
siendo un predictor clave de actitudes hacia la violencia política.

\begin{figure}[H]

\centering{

\includegraphics[width=0.85\linewidth,height=\textheight,keepaspectratio]{paper_files/figure-pdf/fig-distribuciones-violin-1.pdf}

}

\caption{\label{fig-distribuciones-violin}Distribución de justificación
de violencia en protestas por educación y participación}

\end{figure}%

La Figure~\ref{fig-distribuciones-violin} complementa las tablas
descriptivas mostrando visualmente la distribución completa de
justificación de violencia, no solo las medias. El Panel A (educación)
revela varios patrones importantes. Primero, entre no participantes
(violines rojos), los niveles educativos más altos muestran
distribuciones más concentradas en valores bajos
(\textasciitilde1.5-2.0), con medianas claramente descendentes,
confirmando el efecto civilizatorio. Las distribuciones son
relativamente simétricas y unimodales. Entre participantes (violines
azules), las distribuciones se desplazan hacia arriba y se vuelven más
dispersas, especialmente en educación universitaria, donde la
distribución es más amplia (rango \textasciitilde1.5-3.5) y bimodal,
evidenciando la heterogeneidad capturada por los efectos aleatorios:
algunos universitarios participantes mantienen baja justificación
mientras otros la incrementan sustancialmente.

\subsection{Anexo C: Correlaciones entre variables
clave}\label{anexo-c-correlaciones-entre-variables-clave}

\begingroup\fontsize{9}{11}\selectfont

\begin{longtable}[t]{llcc}

\caption{\label{tbl-correlaciones}Correlaciones entre justificación de
violencia y variables sociodemográficas}

\tabularnewline

\toprule
 & Variable & Viol. en Protestas & Viol. Estatal\\
\midrule
\cellcolor{gray!10}{educ\_num} & \cellcolor{gray!10}{Educación} & \cellcolor{gray!10}{0.042} & \cellcolor{gray!10}{-0.020}\\
edad\_std & Edad & -0.177 & 0.075\\
\cellcolor{gray!10}{mujer\_num} & \cellcolor{gray!10}{Mujer} & \cellcolor{gray!10}{-0.026} & \cellcolor{gray!10}{-0.061}\\
ideologia\_std & Ideología (izq-der) & -0.139 & 0.192\\
\cellcolor{gray!10}{protesta\_dummy} & \cellcolor{gray!10}{Participación en protesta} & \cellcolor{gray!10}{0.224} & \cellcolor{gray!10}{-0.128}\\
\bottomrule
\multicolumn{4}{l}{\rule{0pt}{1em}\textit{Nota:}}\\
\multicolumn{4}{l}{\rule{0pt}{1em}* p < 0.05, ** p < 0.01, *** p < 0.001}\\

\end{longtable}

\endgroup{}

Las correlaciones de Pearson muestran patrones destacables. La
participación en protestas exhibe una correlación moderada-fuerte con la
justificación de la violencia en protestas (r = 0.224), mientras que con
la violencia estatal muestra una correlación negativa moderada (r =
-0.128), sugiriendo que participar reduce la legitimación de la
represión policial. La ideología opera de forma opuesta para cada tipo:
muestra una correlación negativa moderada con la violencia en protestas
(r = -0.139, a más derecha menos justificación), pero positiva moderada
con la violencia estatal (r = 0.192). La edad presenta una correlación
negativa moderada con violencia en protestas (r = -0.177), mientras que
la educación muestra correlaciones muy débiles con ambas variables
dependientes (r = 0.042 y -0.020), lo que sugiere que su efecto es
complejo, no-lineal, y fuertemente moderado por la participación,
confirmando la necesidad de los modelos de interacción propuestos.

\subsection{Anexo D: Validación
Metodológica}\label{anexo-d-validaciuxf3n-metodoluxf3gica}

\begin{figure}[H]

\centering{

\includegraphics[width=0.85\linewidth,height=\textheight,keepaspectratio]{paper_files/figure-pdf/fig-diagnosticos-modelos-1.pdf}

}

\caption{\label{fig-diagnosticos-modelos}Diagnósticos de los dos modelos
principales: residuos, normalidad y efectos aleatorios}

\end{figure}%

La Figure~\ref{fig-diagnosticos-modelos} presenta tres evaluaciones
críticas de la validez de los modelos principales. \textbf{Panel A
(Residuos vs Valores Ajustados)}: Ambos modelos muestran patrones
residuales satisfactorios. Las líneas suavizadas (amarillas) se
mantienen cercanas a cero a lo largo del rango de valores ajustados,
indicando que no hay evidencia de no-linealidad sistemática en las
relaciones modeladas. La dispersión vertical es relativamente constante
(homocedasticidad), aunque se observa una leve mayor variabilidad en
valores extremos, típico en modelos de efectos mixtos. El modelo de
violencia en protestas presenta dispersión ligeramente mayor que el de
violencia estatal, consistente con mayor heterogeneidad en actitudes
hacia violencia disruptiva. No se detectan patrones en forma de embudo o
curvaturas pronunciadas que sugieran problemas de especificación.

Los gráficos cuantil-cuantil revelan que los residuos se aproximan
razonablemente a distribución normal en ambos modelos. Los puntos siguen
la línea de referencia roja en la región central, con desviaciones
menores en las colas ---particularmente cola derecha (valores extremos
altos)---, indicando leve asimetría positiva residual. Este patrón es
esperable dado que la variable dependiente (escala 1-5) tiene límite
superior natural, generando ``ceiling effects'' leves. Crucialmente, las
desviaciones no son severas y no comprometen la inferencia: los
estimadores glmmTMB son robustos a desviaciones moderadas de normalidad
cuando el tamaño muestral es grande (n\textgreater10,000 observaciones
en nuestro caso). La similitud de patrones entre modelos confirma
consistencia en la calidad de ajuste.

Los interceptos aleatorios por individuo muestran distribuciones
aproximadamente normales centradas en cero para ambos modelos, validando
el supuesto clave de efectos aleatorios. La varianza de estos
interceptos (\textasciitilde SD = 0.35-0.40) es sustancial, confirmando
heterogeneidad individual significativa en niveles base de justificación
(ICC \textasciitilde0.23-0.24 reportado previamente). El modelo de
violencia en protestas presenta dispersión ligeramente mayor que el de
violencia estatal, consistente con mayor polarización individual en
actitudes hacia acción disruptiva. No se observan valores extremos o
multimodalidad que sugieran subpoblaciones ocultas. Esta estructura de
efectos aleatorios justifica plenamente la especificación multinivel:
ignorar esta heterogeneidad individual generaría errores estándar
subestimados y conclusiones inferenciales erróneas. La distribución
normal de efectos aleatorios también indica que el modelo captura
adecuadamente la estructura de dependencia intra-individual sin
necesidad de especificaciones más complejas (e.g., pendientes
aleatorias).

\begin{figure}[H]

\centering{

\includegraphics[width=0.85\linewidth,height=\textheight,keepaspectratio]{paper_files/figure-pdf/fig-robustez-sensibilidad-1.pdf}

}

\caption{\label{fig-robustez-sensibilidad}Análisis de robustez y
sensibilidad: modelos alternativos y exclusión de 2019}

\end{figure}%

La Figure~\ref{fig-robustez-sensibilidad} presenta tres evaluaciones
críticas de la robustez de los hallazgos principales. Panel A (Efectos
Fijos vs Aleatorios): La comparación revela que los modelos de efectos
fijos (OLS con dummies de año, ignorando estructura longitudinal)
subestiman consistentemente los errores estándar de las interacciones
clave. Los intervalos de confianza en efectos fijos (amarillo) son
sistemáticamente más estrechos que en efectos aleatorios (azul),
generando inferencia anti-conservadora: varios términos de interacción
aparecen ``significativos'' en efectos fijos pero sus ICs se superponen
más con cero al corregir por dependencia intra-individual. Crucialmente,
las magnitudes puntuales de los coeficientes son muy similares entre
especificaciones (diferencias \textless0.05 puntos), indicando que el
sesgo de estimación puntual es mínimo. El problema principal de efectos
fijos es la inflación de precisión: asume observaciones independientes
cuando en realidad individuos contribuyen múltiples olas, violando
supuesto de IID. Los efectos aleatorios corrigen esto modelando
explícitamente la correlación intra-individual (ICC
\textasciitilde0.23), produciendo SEs \textasciitilde15-20\% mayores
pero inferencialmente correctos. Este análisis valida la decisión de
usar glmmTMB multinivel: la estructura longitudinal de ELSOC requiere
efectos aleatorios para inferencia válida, pero los hallazgos
sustantivos (direcciones y magnitudes) son robustos a especificación.

Excluir el año del estallido social (2019) es la prueba más crítica: si
las interacciones fueran meros artefactos del shock de 2019, deberían
desaparecer al remover ese año. Los resultados demuestran robustez
sustantiva: todas las interacciones clave persisten con magnitudes y
significancia similares. En H1, la interacción Univ. completa ×
Participación es +0.13 en dataset completo vs +0.12 sin 2019 (diferencia
\textless0.01). Los intervalos de confianza se superponen casi
completamente, indicando que 2019 no es el único driver de los efectos
sino que amplifica patrones presentes en todo el periodo 2016-2023. El
efecto de participación (término principal) también permanece estable:
+0.27 vs +0.25 en H1. Esto confirma que las interacciones educación ×
participación no son contingentes al momento del estallido sino
estructuras relacionales persistentes: la educación superior amplifica
el efecto de participación tanto en años ``normales'' como en el pico de
movilización. Este hallazgo refuerza la interpretación teórica: el
reenmarcamiento moral no es meramente reactivo a eventos coyunturales
sino que refleja mecanismos sociocognitivos duraderos donde capital
cultural interactúa con experiencia de movilización para reconfigurar
actitudes.

La comparación revela cómo el estallido de 2019 modula pero no crea los
efectos de interacción. En modelos estimados solo con datos de 2019
(verde), las interacciones son consistentemente más fuertes que en el
periodo completo (rojo): en H1, Univ. completa × Participación es +0.18
en 2019 vs +0.13 en periodo completo. Sin embargo, crucialmente, las
direcciones son idénticas y los ICs se superponen parcialmente,
indicando que 2019 representa una intensificación cuantitativa de
patrones preexistentes, no una ruptura cualitativa. El efecto principal
de participación también se amplifica en 2019 (+0.35-0.40 vs +0.27-0.36
periodo completo), consistente con mayor polarización y activación de
marcos morales duales durante el pico de movilización. Este patrón
sugiere que el estallido actuó como coyuntura crítica que temporalmente
magnificó procesos relacionales latentes: la educación superior ya
moderaba el efecto de participación, pero 2019 elevó las apuestas y la
intensidad experiencial, amplificando tanto la justificación base como
las interacciones. Post-2019, los efectos se moderan pero no desaparecen
(Panel B), evidenciando que el shock dejó sedimentos permanentes en la
estructura de actitudes. En conjunto, los tres paneles validan que los
hallazgos no son artefactos metodológicos ni contingentes a un año
específico, sino patrones robustos que atraviesan especificaciones y
subperiodos.

\begin{figure}[H]

\centering{

\includegraphics[width=0.85\linewidth,height=\textheight,keepaspectratio]{paper_files/figure-pdf/fig-slopes-educacion-1.pdf}

}

\caption{\label{fig-slopes-educacion}Pendientes del efecto de
participación por nivel educativo: magnitud diferencial de la
experiencia de movilización}

\end{figure}%

\begin{figure}[H]

\centering{

\includegraphics[width=0.85\linewidth,height=\textheight,keepaspectratio]{paper_files/figure-pdf/fig-slopes-educacion-nopart-1.pdf}

}

\caption{\label{fig-slopes-educacion-nopart}Pendientes del efecto
civilizatorio entre no participantes: reducción de justificación por
nivel educativo}

\end{figure}%

La Figure~\ref{fig-slopes-educacion-nopart} visualiza el efecto
civilizatorio clásico entre quienes no participan en protestas,
mostrando cómo cada nivel educativo superior reduce la justificación de
violencia comparado con la categoría de referencia (educación media o
menos). Las barras negativas (azules) confirman que todos los niveles de
educación técnica y universitaria se asocian con menor justificación
entre observadores externos, aunque con magnitudes variables. Este
patrón contrasta radicalmente con el efecto entre participantes
(fig-slopes-educacion), donde la educación amplifica la justificación,
evidenciando la dependencia contextual del capital cultural.

La Figure~\ref{fig-slopes-educacion} complementa el gráfico de líneas
cruzadas visualizando la magnitud del efecto de participación en cada
nivel educativo, revelando heterogeneidad sustantiva en cómo la
experiencia de movilización transforma actitudes. Las barras representan
la diferencia en justificación entre participantes y no participantes
(pendientes implícitas de la interacción), con todas las diferencias
siendo positivas ---confirmando que participación siempre incrementa
justificación--- pero con magnitudes que varían sistemáticamente por
nivel educativo.

El efecto de participación es menor en educación media (slope = +0.15,
CI: {[}0.05, 0.25{]}), sugiriendo que individuos con menos educación
formal experimentan un incremento más modesto en justificación al
participar, posiblemente porque parten de niveles base ya relativamente
altos (\textasciitilde1.95) y tienen menos ``espacio'' para incrementar
en la escala, o porque la participación no requiere reenmarcamiento
moral tan profundo dado que su socialización previa no enfatizó tanto el
rechazo normativo a la violencia.

En contraste, el efecto de participación es mayor y creciente en niveles
educativos altos: educación técnica superior muestra slopes de +0.25 a
+0.35, mientras que universitaria completa alcanza +0.35 (CI: {[}0.22,
0.48{]}). Este patrón confirma que la educación superior amplifica el
impacto transformador de la participación. Los universitarios no solo
incrementan más su justificación al participar, sino que este incremento
representa un cambio cualitativo más dramático dado que partían de los
niveles más bajos entre no participantes (\textasciitilde1.65).

Este hallazgo tiene implicaciones teóricas críticas: la participación
política no es un ``tratamiento'' homogéneo sino una experiencia cuyo
efecto depende del capital cultural previo. Los recursos cognitivos
provistos por educación superior ---pensamiento crítico, exposición a
narrativas contra-hegemónicas--- actúan como catalizadores que
magnifican el reenmarcamiento moral inducido por la experiencia de
movilización. Esto resuelve la aparente paradoja: no es que la educación
``falle'' en su efecto civilizatorio entre participantes, sino que
proporciona herramientas que, en contexto de activismo, reinterpretan la
violencia táctica como legítima. La educación no determina unívocamente
actitudes sino que provee marcos interpretativos cuya activación depende
de la posición experiencial del sujeto.

El gráfico Figure~\ref{fig-paradoja-educacion} revela patrones complejos
de moderación educativa sobre la justificación de violencia en
protestas.

Entre quienes no han participado en protestas, la mayoría de los niveles
de educación superior muestran efectos negativos significativos
comparados con educación media completa o menos (categoría de
referencia). La educación técnica superior incompleta reduce la
justificación en -0.13 (p\textless0.05), la técnica completa en -0.13
(p\textless0.001), y la universitaria completa en -0.13
(p\textless0.001). La universitaria incompleta muestra un efecto menor y
no significativo (-0.07). Esto confirma un ``efecto civilizatorio'' de
la educación técnica y universitaria completa: mayor credencialización
se asocia con menor justificación de violencia entre observadores
externos.

Por otro lado, la participación en protestas incrementa
significativamente la justificación de violencia (\(+0.27\),
p\textless0.001) para el grupo de referencia (educación media o menos),
un efecto sustantivo considerable.

En cuanto a los términos de interacción, son todos positivos, revelando
que la educación superior magnifica el efecto de la participación,
aunque con magnitudes diferentes. La técnica superior incompleta muestra
la interacción más fuerte (\(+0.28\), p\textless0.05), seguida por
técnica completa y universitaria completa (ambas \(+0.13\),
p\textless0.05 y p\textless0.01 respectivamente), mientras que
universitaria incompleta no alcanza significancia estadística
(\(+0.11\), ns). Calculando el efecto total para universitarios
completos participantes: \(-0.13\) (efecto principal) \(+0.27\)
(participación) \(+0.13\) (interacción) = \(+0.27\). Esto implica que
los universitarios completos que protestan justifican la violencia al
mismo nivel que el grupo de referencia con educación media, anulando
completamente el efecto civilizatorio inicial.

Ahora, el año 2019 muestra un coeficiente positivo (\(+0.05\),
p\textless0.05), consistente con el contexto del estallido social. Esto
sugiere que, controlando por educación y participación, 2019 tuvo mayor
justificación relativa. Los otros años post-2016 muestran coeficientes
negativos (2018: \(-0.11***\), 2022 y 2023: \(-0.10***\)), indicando una
tendencia general descendente, mientras 2017 no difiere
significativamente del año base.

Finalmente, podemos ver que controles como la edad reduce la
justificación (\(-0.01\), p\textless0.001), la ideología de derecha
también la reduce (\(-0.03\), p\textless0.001), mientras que el género
(mujer) no tiene efecto significativo (\(-0.03\), ns). El modelo muestra
una varianza del intercepto aleatorio de 0.13, indicando heterogeneidad
sustancial entre individuos en sus niveles base de justificación.




\end{document}
