# Bibliografía

Acemoglu, D., Johnson, S., Robinson, J. A., & Pierre Yared. (2005). From Education to Democracy? The American Economic Review, 95(2), 44-49. JSTOR.

Adam‐Troian, J., Wagner‐Egger, P., Motyl, M., Arciszewski, T., Imhoff, R., Zimmer, F., Klein, O., Babinska, M., Bangerter, A., Bilewicz, M., Blanuša, N., Bovan, 

K., Bužarovska, R., Cichocka, A., Çelebi, E., Delouvée, S., Douglas, K. M., Dyrendal, A., Gjoneska, B., … Van Prooijen, J. (2021). Investigating the Links Between Cultural Values and Belief in Conspiracy Theories: The Key Roles of Collectivism and Masculinity. Political Psychology, 42(4), 597-618. https://doi.org/10.1111/pops.12716

Almond, G. A. & Verba, S. (1963). The Civic Culture. Princeton University Press; JSTOR. http://www.jstor.org/stable/j.ctt183pnr2

Altemeyer, B. (1998). The Other “Authoritarian Personality”. En Advances in Experimental Social Psychology (Vol. 30, pp. 47-92). Elsevier. https://doi.org/10.1016/S0065-2601(08)60382-2

Amnistía, I. (2020). Ojos sobre Chile: Violencia policial y responsabilidad de mando durante el estallido social (No. AMR 22/3133/2020). https://www.amnesty.org

Araujo, K. (2022). The circuit of detachment in Chile: Understanding the fate of a neoliberal laboratory. Cambridge University Press. https://doi.org/10.1017/9781009310697

Arthur, J. A., & Case, C. E. (1994). Race, class and support for police use of force. Crime, Law and Social Change, 21(2), 167-182. https://doi.org/10.1007/BF01307910

Ayoub, P. M., Page, D., & Whitt, S. (2021). Pride amid Prejudice: The Influence of LGBT+ Rights Activism in a Socially Conservative Society. American Political Science Review, 115(2), 467-485. https://doi.org/10.1017/S0003055420001082

Aytaç, S. E., Schiumerini, L., & Stokes, S. (2017). Protests and Repression in New Democracies. Perspectives on Politics, 15(1), 62-82. https://doi.org/10.1017/S1537592716004138

Beckwith, K. (2025). Protest embodied: Enacting the goal, resisting the clothing of the state. European Journal of Politics and Gender, 8(2), 385-405. https://doi.org/10.1332/25151088Y2025D000000076

Beeghley, L. (1986). Social class and political participation: A review and an explanation. Sociological Forum, 1(3), 496-513. https://doi.org/10.1007/BF01123942

Bellei, C., Cabalin, C., & Orellana, V. (2014). The 2011 Chilean student movement against neoliberal educational policies. Studies in Higher Education, 39(3), 426-440. https://doi.org/10.1080/03075079.2014.896179

Benford, R. D., & Snow, D. A. (2000). Framing Processes and Social Movements: An Overview and Assessment. Annual Review of Sociology, 26, 611-639. JSTOR.

Berinsky, A. J., & Lenz, G. S. (2011). Education and Political Participation: Exploring the Causal Link. Political Behavior, 33(3), 357-373. JSTOR.

Blühdorn, I., & Deflorian, M. (2021). Politicisation beyond post-politics: New social activism and the reconfiguration of political discourse. Social Movement Studies, 20(3), 259-275. https://doi.org/10.1080/14742837.2021.1872375

Bonner, M. D., & Dammert, L. (2022). Constructing police legitimacy during protests: Frames and consequences for human rights. Policing and Society, 32(5), 629-645. https://doi.org/10.1080/10439463.2021.1957887

Bottero, W. (2004). Class Identities and the Identity of Class. Sociology, 38(5), 985-1003. https://doi.org/10.1177/0038038504047182

Bourdieu, P. (with Passeron, J.-C., Pasquali, P., Poupeau, F., & Georgiadis, M. de la P.). (2019). La Reproducción: Elementos para una Teoría Del Sistema Educativo. Siglo XXI Editores.

Branton, R., Martinez-Ebers, V., Carey, T. E., & Matsubayashi, T. (2015). Social Protest and Policy Attitudes: The Case of the 2006 Immigrant Rallies. American Journal of Political Science, 59(2), 390-402. JSTOR.

Brehm, J. W. (1966). A theory of psychological reactance. Academic Press.

Brooks, M., E., Kristensen, K., Benthem, K., J. ,van, Magnusson, A., Berg, C., W., Nielsen, A., Skaug, H., J., Mächler, M., & Bolker, B., M. (2017). glmmTMB Balances Speed and Flexibility Among Packages for Zero-inflated Generalized Linear Mixed Modeling. The R Journal, 9(2), 378. https://doi.org/10.32614/RJ-2017-066

Canales Cerón, M. (2022). La pregunta de Octubre: Fundación, apogeo y crisis del Chile neoliberal (Primera edición). LOM ediciones.

Carrasco Paillamilla, S. F., & Disi Pavlic, R. (2023). Predictors of perceptions of human rights violations during the Chilean social outburst of 2019. Frontiers in Psychology, 14, 1133428. https://doi.org/10.3389/fpsyg.2023.1133428

Castillo, J. C., Miranda, D., & Madero Cabib, I. (2013). Todos somos de clase media: Sobre el estatus social subjetivo en Chile. Latin American Research Review, 48(1), 155–173.

Castillo, J. C., Palacios, D., Joignant, A., & Tham, M. (2015). Inequality, Distributive Justice and Political Participation: An Analysis of the Case of Chile. Bulletin of Latin American Research, 34(4), 486-502. https://doi.org/10.1111/blar.12369

Clark, W. R., & Golder, M. (2006). Understanding interaction models: Improving empirical analyses. Political analysis, 14(1), 63-82.

Converse, P. (1972). Change in the American electorate. The human meaning of social change/Russell Sage Foundation.

Cox, L., González, R., & Le Foulon, C. (2024). The 2019 Chilean Social Upheaval: A Descriptive Approach. Journal of Politics in Latin America, 16(1), 68-89. https://doi.org/10.1177/1866802X231203747

Crossley, N. (2003). From Reproduction to Transformation: Social Movement Fields and the Radical Habitus. Theory, Culture & Society, 20(6), 43-68. https://doi.org/10.1177/0263276403206003

Davenport, C. (1995). Multi-Dimensional Threat Perception and State Repression: An Inquiry into Why States Apply Negative Sanctions. American Journal of Political Science, 39(3), 683. https://doi.org/10.2307/2111650

Davenport, C., Soule, S. A., & Armstrong, D. A. (2011). Protesting While Black? The Differential Policing of American Activism, 1960 to 1990. American Sociological Review, 76(1), 152-178. JSTOR.

De Vydt, M., & Ketelaars, P. (2021). Linking consensus to action: Does frame alignment amongst sympathizers lead to protest participation? Social Movement Studies, 20(4), 439-458. https://doi.org/10.1080/14742837.2020.1770071

della Porta, D. (Ed.). (2017). Global Diffusion of Protest: Riding the Protest Wave in the Neoliberal Crisis. Amsterdam University Press; JSTOR. http://www.jstor.org/stable/j.ctt1zkjxq0

Della Porta, D. (2018). Radicalization: A Relational Perspective. Annual Review of Political Science, 21(1), 461-474. https://doi.org/10.1146/annurev-polisci-042716-102314

Della Porta, D., & Fillieule, O. (2007). Policing Social Protest. En D. A. Snow, S. A. Soule, & H. Kriesi (Eds.), The Blackwell Companion to Social Movements (pp. 217-241). Blackwell Publishing Ltd. https://doi.org/10.1002/9780470999103.ch10

Dewey, J. (2024). Democracy and Education (N. Tampio, Ed.). Columbia University Press. http://www.jstor.org/stable/10.7312/dewe21010

Disi Pavlic, R., Medel, R. M., Bargsted, M., & Somma, N. M. (2025). Justification of violence, ideological preferences, and exposure to protests: Causal evidence from the 2019 Chilean social unrest. Social Forces, soaf102. https://doi.org/10.1093/sf/soaf102

Drury, J., & Reicher, S. D. (2018). The Conservative Crowd?: How Participation in Collective Events Transforms Participants’ Understandings of Collective Action. En B. Wagoner, F. M. Moghaddam, & J. Valsiner (Eds.), The Psychology of Radical Social Change (1.a ed., pp. 11-28). Cambridge University Press. https://doi.org/10.1017/9781108377461.003

Donoso, S., & Somma, N. M. (2019). The Manifold Political Consequences of Chile’s Student Movement. En M. Arce & R. Rice (Eds.), Protest and Democracy (pp. 145–172). University of Calgary Press.

Dyrstad, K., & Hillesund, S. (2020). Explaining Support for Political Violence. The Journal of Conflict Resolution, 64(9), 1724-1753. JSTOR.

Earl, J. (2003). Tanks, Tear Gas, and Taxes: Toward a Theory of Movement Repression. Sociological Theory, 21(1), 44-68. JSTOR.

Earl, J. (2022). Repression and Social Movements. En D. Della Porta, B. Klandermans, D. McAdam, & D. A. Snow (Eds.), The Wiley-Blackwell Encyclopedia of Social and Political Movements (1.a ed., pp. 1-7). Wiley. https://doi.org/10.1002/9780470674871.wbespm446.pub2

Elsässer, L., & Schäfer, A. (2023). Political Inequality in Rich Democracies. Annual Review of Political Science, 26(1), 469-487. https://doi.org/10.1146/annurev-polisci-052521-094617

Fair, C. C., & Shepherd, B. (2006). Who Supports Terrorism? Evidence from Fourteen Muslim Countries. Studies in Conflict & Terrorism, 29(1), 51-74. https://doi.org/10.1080/10576100500351318

Francisco, R. A. (1995). The Relationship between Coercion and Protest: An Empirical Evaluation in Three Coercive States. The Journal of Conflict Resolution, 39(2), 263-282. JSTOR.

Fryer, T. (2023). Do the political attitudes of students change during their time in higher education? Higher Education, 86(3), 563-590. https://doi.org/10.1007/s10734-022-00915-8

Gamson, W. A. (2002). Talking politics (Transferred to digital printing). Cambridge Univ. Press.

Garcés, M. (2019). October 2019: Social Uprising in Neoliberal Chile. Journal of Latin American Cultural Studies, 28(3), 483-491. https://doi.org/10.1080/13569325.2019.1696289

Gelman, A., & Hill, J. (2021). Data analysis using regression and multilevel/hierarchical models (23rd printing). Cambridge Univ. Press.

Gerber, M. M., Carvacho, H., & González, R. (2016). Development and validation of a scale of support for violence in the context of intergroup conflict (SVIC): The case of violence perpetrated by Mapuche people and the police in Chile. International Journal of Intercultural Relations, 51, 61-68. https://doi.org/10.1016/j.ijintrel.2016.01.004

Gerber, M. M., Figueiredo, A., Sáez, L., & Orchard, M. (2023). Legitimidad, Justicia y Justificación de la Violencia Intergrupal entre Carabineros y Manifestantes en Chile. Psykhe (Santiago), 32.

Gerber, M. M., González, R., Carvacho, H., Jiménez-Moya, G., Moya, C., & Jackson, J. (2018). On the justification of intergroup violence: The roles of procedural justice, police legitimacy, and group identity in attitudes toward violence among indigenous people. Psychology of Violence, 8(3), 379-389. https://doi.org/10.1037/vio0000177

Gerber, M. M., & Jackson, J. (2017). Justifying violence: Legitimacy, ideology and public support for police use of force. Psychology, Crime & Law, 23(1), 79-95. https://doi.org/10.1080/1068316X.2016.1220556

Giugni, M. (2004). Social protest and policy change: Ecology, antinuclear, and peace movements in comparative perspective. Rowman & Littlefield.

Gonzalez, R., & Morán, C. L. F. (2020). The 2019–2020 Chilean protests: A first look at their causes and participants. International Journal of Sociology, 50(3), 227-235. https://doi.org/10.1080/00207659.2020.1752499

Goodwin, J., Jasper, J. M., & Polletta, F. (Eds.). (2001). Passionate politics: Emotions and social movements. The University of Chicago Press.

Gubler, J. R., & Selway, J. S. (2012). Horizontal Inequality, Crosscutting Cleavages, and Civil War. Journal of Conflict Resolution, 56(2), 206-232. https://doi.org/10.1177/0022002711431416

Gutting, R. S. (2020). Contentious Activities, Disrespectful Protesters: Effect of Protest Context on Protest Support and Mobilization Across Ideology and Authoritarianism. Political Behavior, 42(3), 865-890. https://doi.org/10.1007/s11109-018-09523-8

Hastie, B. (2007). Higher education and sociopolitical orientation: The role of social influence in the liberalisation of students. European Journal of Psychology of Education, 22(3), 259-274. JSTOR.

Hox, J. J., Moerbeek, M., & Schoot, R. van de. (2018). Multilevel analysis: Techniques and applications (Third edition). Routledge, Taylor & Francis Group. https://doi.org/10.4324/9781315650982

Hsiao, Y., & Radnitz, S. (2021). Allies or Agitators? How Partisan Identity Shapes Public Opinion about Violent or Nonviolent Protests. Political Communication, 38(4), 479-497. https://doi.org/10.1080/10584609.2020.1793848

Human, R. W. (2019, noviembre 26). Chile: Llamado urgente a una reforma policial tras las protestas. https://www.hrw.org/es/news/2019/11/26/chile-llamado-urgente-una-reforma-policial-tras-las-protestas

Jackson, J., Huq, A. Z., Bradford, B., & Tyler, T. R. (2013). Monopolizing force? Police legitimacy and public attitudes toward the acceptability of violence. Psychology, Public Policy, and Law, 19(4), 479-497. https://doi.org/10.1037/a0033852

Jasper, J. M. (1998). The Emotions of Protest: Affective and Reactive Emotions In and Around Social Movements. Sociological Forum, 13(3), 397-424. https://doi.org/10.1023/A:1022175308081

Joignant, A., & Somma, N. M. (Eds.). (2024). Social Protest and Conflict in Radical Neoliberalism: Chile, 2008–2020. Springer Nature Switzerland. https://doi.org/10.1007/978-3-031-58132-8

Joignant, Alfredo & Somma, Nicolás & Garreton, Matias & Campos, Tomás & Brennan, Tammy. (2020). INFORME ANUAL Observatorio de Conflictos 2020. 

Jost, J. T., Glaser, J., Kruglanski, A. W., & Sulloway, F. J. (2003). Political conservatism as motivated social cognition. Psychological Bulletin, 129(3), 339-375. https://doi.org/10.1037/0033-2909.129.3.339

Kam, C. D., & Palmer, C. L. (2008). Reconsidering the Effects of Education on Political Participation. The Journal of Politics, 70(3), 612-631. https://doi.org/10.1017/S0022381608080651

Ketchley, N., & El-Rayyes, T. (2021). Unpopular Protest: Mass Mobilization and Attitudes to Democracy in Post-Mubarak Egypt. The Journal of Politics, 83(1), 291-305. https://doi.org/10.1086/709298

Koopmans, R. (1993). The Dynamics of Protest Waves: West Germany, 1965 to 1989. American Sociological Review, 58(5), 637. https://doi.org/10.2307/2096279

Korpi, W. (1985). Power Resources Approach vs. Action and Conflict: On Causal and Intentional Explanations in the Study of Power. Sociological Theory, 3(2), 31. https://doi.org/10.2307/202223

Krause, K. (2009). Beyond definition: Violence in a global perspective. Global Crime, 10(4), 337-355. https://doi.org/10.1080/17440570903248270

Krueger, A. B., & Malečková, J. (2003). Education, Poverty and Terrorism: Is There a Causal Connection? The Journal of Economic Perspectives, 17(4), 119-144. JSTOR.

Kruglanski, A. W., Gelfand, M. J., Bélanger, J. J., Sheveland, A., Hetiarachchi, M., & Gunaratna, R. (2014). The Psychology of Radicalization and Deradicalization: How Significance Quest Impacts Violent Extremism. Political Psychology, 35(S1), 69-93. https://doi.org/10.1111/pops.12163

Langton, K. P., & Jennings, M. K. (1968). Political Socialization and the High School Civics Curriculum in the United States. American Political Science Review, 62(3), 852-867. https://doi.org/10.2307/1953435

Lerner, M. J. (1980). The Belief in a Just World. En M. J. Lerner, The Belief in a Just World (pp. 9-30). Springer US. https://doi.org/10.1007/978-1-4899-0448-5_2

Lindh, A., & McCall, L. (2020). Class Position and Political Opinion in Rich Democracies. Annual Review of Sociology, 46(1), 419-441. https://doi.org/10.1146/annurev-soc-121919-054609

Lipset, S. M. (1959). Some Social Requisites of Democracy: Economic Development and Political Legitimacy. American Political Science Review, 53(1), 69-105. Cambridge Core. https://doi.org/10.2307/1951731

Lubke, G. H., & Muthén, B. O. (2004). Applying Multigroup Confirmatory Factor Models for Continuous Outcomes to Likert Scale Data Complicates Meaningful Group Comparisons. Structural Equation Modeling: A Multidisciplinary Journal, 11(4), 514-534. https://doi.org/10.1207/s15328007sem1104_2

Lüdecke, D. (2018). ggeffects: Tidy Data Frames of Marginal Effects from Regression Models. Journal of Open Source Software, 3(26), 772. https://doi.org/10.21105/joss.00772

Luna, J. P. (2024). Disjointed Polarization in Chile’s Enduring Crisis of Representation. Latin American Politics and Society, 66(2), 72-101. Cambridge Core. https://doi.org/10.1017/lap.2024.19

Maguire, E., Barak, M., Wells, W., & Katz, C. (2020). Attitudes towards the Use of Violence against Police among Occupy Wall Street Protesters. Policing: A Journal of Policy and Practice, 14(4), 883-899. https://doi.org/10.1093/police/pay003

Marx, G. T. (1998). Policing Protest (NED-New edition, Vol. 6). University of Minnesota Press; JSTOR. http://www.jstor.org/stable/10.5749/j.ctttv1tv

Mazumder, S. (2018). The Persistent Effect of U.S. Civil Rights Protests on Political Attitudes. American Journal of Political Science, 62(4), 922-935. https://doi.org/10.1111/ajps.12384

McAdam, D. (1989). The Biographical Consequences of Activism. American Sociological Review, 54(5), 744. https://doi.org/10.2307/2117751

McAdam, D., & Brandt, C. (2009). Assessing the Effects of Voluntary Youth Service: The Case of Teach for America. Social Forces, 88(2), 945-969. https://doi.org/10.1353/sof.0.0279

Medel, R. M., & Somma, N. M. (2022). Represión policial y grupos de protesta en Chile: Un estudio longitudinal. Revista de Sociología, 37(1). https://doi.org/10.5354/0719-529X.2022.68149

Meraviglia, C., & Buis, M. L. (2015). Class, Status, and Education: The Influence of Parental Resources on IEO in Europe, 1893-1987. International Review of Social Research, 5(1), 35-60. https://doi.org/10.1515/irsr-2015-0004

Muller, E. N., & Weede, E. (1990). Cross-National Variation in Political Violence: A Rational Action Approach. Journal of Conflict Resolution, 34(4), 624-651. https://doi.org/10.1177/0022002790034004003

Muñoz, J., & Anduiza, E. (2019). ‘If a fight starts, watch the crowd’: The effect of violence on popular support for social movements. Journal of Peace Research, 56(4), 485-498. https://doi.org/10.1177/0022343318820575

Nie, N. H., Junn, J., & Stehlik-Barry, K. (1996). Education and democratic citizenship in America. University of Chicago Press.

Norman, G. (2010). Likert scales, levels of measurement and the “laws” of statistics. Advances in Health Sciences Education, 15(5), 625-632. https://doi.org/10.1007/s10459-010-9222-y

Onursal, D., Hobbs, A., & Wells, C. (2024). Violence, what is it good for? Waves of riotous-violent protest and democracy. Democratization, 31(6), 1272-1296. https://doi.org/10.1080/13510347.2024.2302544

Ortiz, I., Burke, S., Berrada, M., & Saenz Cortés, H. (2022). World Protests: A Study of Key Protest Issues in the 21st Century. Springer International Publishing. https://doi.org/10.1007/978-3-030-88513-7

Østby, G. (2013). Inequality and political violence: A review of the literature. International Area Studies Review, 16(2), 206-231. https://doi.org/10.1177/2233865913490937

Pascarella, E. T., & Terenzini, P. T. (1991). How college affects students (First edition). Jossey-Bass Publishers.

Passy, F., & Monsch, G. (2018). Biographical Consequences of Activism. En D. A. Snow, S. A. Soule, H. Kriesi, & H. J. McCammon (Eds.), The Wiley Blackwell Companion to Social Movements (1.a ed., pp. 499-514). Wiley. https://doi.org/10.1002/9781119168577.ch28

Pavlic, R. D. (2021). The Nearness of Youth. Latin American Politics and Society, 63(1), 72-94. JSTOR.

Pérez Ahumada, P., & Andrade De La Horra, V. (2021). Clase, política y percepción del conflicto de clases en Chile. Revista Temas Sociológicos, 29, 323-353. https://doi.org/10.29344/07196458.29.2938

Pérez Ahumada, P., & Andrade, V. (2023). Class identity in times of social mobilization and labor union revitalization: Evidence from the case of Chile (2009–2019). Current Sociology, 71(6), 1040-1062. https://doi.org/10.1177/00113921211056052

Pérez-Liñán, A. S., & Pérez-Liñán, A. S. (2010). Presidential impeachment and the new political instability in Latin America (1. paperback ed). Cambridge University Press.

Persson, M. (2015). Education and Political Participation. British Journal of Political Science, 45(3), 689-703. https://doi.org/10.1017/S0007123413000409

Pleyers, G. (2023). El estallido chileno a la luz de la década global de los movimientos sociales. Polis, 22(65). http://dx.doi.org/10.32735/s0718-6568/2023-n65-1868

Polletta, F., & Jasper, J. M. (2001). Collective Identity and Social Movements. Annual Review of Sociology, 27(1), 283-305. https://doi.org/10.1146/annurev.soc.27.1.283

Pratto, F., Sidanius, J., Stallworth, L. M., & Malle, B. F. (1994). Social dominance orientation: A personality variable predicting social and political attitudes. Journal of Personality and Social Psychology, 67(4), 741-763. https://doi.org/10.1037/0022-3514.67.4.741

Raudenbush, S., & Bryk, A. S. (2010). Hierarchical linear models: Applications and data analysis methods (2. ed., [Nachdr.]). Sage Publ.

Reinka, M. A., & Leach, C. W. (2017). Race and Reaction: Divergent Views of Police Violence and Protest against. Journal of Social Issues, 73(4), 768-788. https://doi.org/10.1111/josi.12247

Rivera, S., Severino, F., & Visconti, G. (2025). Exposure to protests and support for different forms of violence: Evidence from the 2019 social outburst in Chile. Research & Politics, 12(3), 20531680251355242. https://doi.org/10.1177/20531680251355242

Rodríguez, Á., Peña, S., Cavieres, I., Vergara, M. J., Pérez, M., Campos, M., Peredo, D., Jorquera, P., Palma, R., Cortés, D., López, M., & Morales, S. (2021). Ocular trauma by kinetic impact projectiles during civil unrest in Chile. Eye, 35(6), 1666-1672. https://doi.org/10.1038/s41433-020-01146-w

Ryan, W. (2010). Blaming the Victim. Knopf Doubleday Publishing Group.

Saavedra, P., & Drury, J. (2019). Including political context in the psychological analysis of collective action: Development and validation of a measurement scale for subjective political openness. Journal of Social and Political Psychology, 7(2), 665-694. https://doi.org/10.5964/jspp.v7i2.1030

Sabucedo, J.-M., Dono, M., Alzate, M., & Seoane, G. (2018). The Importance of Protesters’ Morals: Moral Obligation as a Key Variable to Understand Collective Action. Frontiers in Psychology, Volume 9-2018. https://www.frontiersin.org/journals/psychology/articles/10.3389/fpsyg.2018.00418

Schwabbauer, M. L. (1975). Use of the latent image technique to develop and evaluate problem-solving skills. The American Journal of Medical Technology, 41(12), 457-462.

Siegel, H. (1981). Kohlberg, Moral Adequacy, and the Justification of Educational Interventions. Educational Theory, 31(3-4), 275-284. https://doi.org/10.1111/j.1741-5446.1981.tb00970.x

Simon, B., & Klandermans, B. (2001). Politicized collective identity: A social psychological analysis. American Psychologist, 56(4), 319-331. https://doi.org/10.1037/0003-066X.56.4.319

Singer, J. D., & Willett, J. B. (2003). Applied Longitudinal Data Analysis: Modeling Change and Event Occurrence (1.a ed.). Oxford University PressNew York. https://doi.org/10.1093/acprof:oso/9780195152968.001.0001

Smolski, A. R. (2021). Class Struggle and Violence in Latin American Cities. Latin American Perspectives, 48(1), 280-284. https://doi.org/10.1177/0094582X19860470

Snow, D. A., & Bedford, R. D. (1988). Ideology, Frame Resonance, and Participant Mobilization. International social movement research, 1, 197-218.

Somma, N. M., Bargsted, M., Disi Pavlic, R., & Medel, R. M. (2021). No water in the oasis: The Chilean Spring of 2019–2020. Social Movement Studies, 20(4), 495-502. https://doi.org/10.1080/14742837.2020.1727737

Stewart, F. (2005). Horizontal Inequalities: A Neglected Dimension of Development. En UNU-WIDER, A. B. Atkinson, K. Basu, J. N. Bhagwati, D. C. North, D. Rodrik, F. Stewart, J. E. Stiglitz, & J. G. Williamson, Wider Perspectives on Global Development (pp. 101-135). Palgrave Macmillan UK. https://doi.org/10.1057/9780230501850_5

Sunshine, J., & Tyler, T. R. (2003). The Role of Procedural Justice and Legitimacy in Shaping Public Support for Policing. Law & Society Review, 37(3), 513-548. JSTOR.

Taber, C. S., & Lodge, M. (2012). MOTIVATED SKEPTICISM IN THE EVALUATION OF POLITICAL BELIEFS (2006). Critical Review, 24(2), 157-184. https://doi.org/10.1080/08913811.2012.711019

Tarrow, S. G.. (1998). Power in movement: Social movements and contentious politics (2nd ed). Cambridge University Press.

Tenn, S. (2007). The Effect of Education on Voter Turnout. Political Analysis, 15(4), 446-464. JSTOR.

Tertytchnaya, K., & Lankina, T. (2020). Electoral Protests and Political Attitudes under Electoral Authoritarianism. The Journal of Politics, 82(1), 285-299. https://doi.org/10.1086/705815

Tetlock, P. E. (1986). A value pluralism model of ideological reasoning. Journal of Personality and Social Psychology, 50(4), 819-827. https://doi.org/10.1037/0022-3514.50.4.819

Thaler, K. M., Mueller, L., & Mosinger, E. (2023). Framing Police Violence: Repression, Reform, and the Power of History in Chile. The Journal of Politics, 85(4), 1198-1213. https://doi.org/10.1086/724967

Thompson, B. L., & Lee, J. D. (2004). Who Cares If Police Become Violent? Explaining Approval of Police Use of Force Using a National Sample. Sociological Inquiry, 74(3), 381-410. https://doi.org/10.1111/j.1475-682X.2004.00097.x

Tilly, C. (Ed.). (1998). Durable inequality. University of California Press.

Tilly, C. (2003). The Politics of Collective Violence (1.a ed.). Cambridge University Press. https://doi.org/10.1017/CBO9780511819131

Tyler, D. H., Barak, M., Maguire, E. R., & Wells, W. (2018). The effects of procedural injustice on the use of violence against police by Occupy Wall Street protesters. Police Practice and Research, 19(2), 138-152. https://doi.org/10.1080/15614263.2018.1418153

Tyler, T. R. (2006). Restorative Justice and Procedural Justice: Dealing with Rule Breaking. Journal of Social Issues, 62(2), 307-326. https://doi.org/10.1111/j.1540-4560.2006.00452.x

Tyler, T. R., & Blader, S. L. (2003). The Group Engagement Model: Procedural Justice, Social Identity, and Cooperative Behavior. Personality and Social Psychology Review, 7(4), 349-361. https://doi.org/10.1207/S15327957PSPR0704_07

Van Stekelenburg, J., & Klandermans, B. (2013). The social psychology of protest. Current Sociology, 61(5-6), 886-905. https://doi.org/10.1177/0011392113479314

Varlık, S., Akpınar, S., Akpınar, Ö., & Görünü, R. M. (2025). Education as an antidote to violence and social inequality. Humanities and Social Sciences Communications. https://doi.org/10.1057/s41599-025-06192-x

Verba, S., Schlozman, K. L., & Brady, H. E. (2002). Voice and equality: Civic voluntarism in American politics (Nachdr.). Harvard Univ. Press.

Vestergren, S., Drury, J., & Chiriac, E. H. (2018). How collective action produces psychological change and how that change endures over time: A case study of an environmental campaign. British Journal of Social Psychology, 57(4), 855-877. https://doi.org/10.1111/bjso.12270

Wacquant, L. (2008). Ghettos and Anti-Ghettos: An Anatomy of the New Urban Poverty. Thesis Eleven, 94(1), 113-118. https://doi.org/10.1177/0725513608093280

Walgrave, S., & Wouters, R. (2014). The Missing Link in the Diffusion of Protest: Asking Others. American Journal of Sociology, 119(6), 1670-1709. JSTOR. https://doi.org/10.1086/676853

Wallace, S. J., Zepeda‐Millán, C., & Jones‐Correa, M. (2014). Spatial and Temporal Proximity: Examining the Effects of Protests on Political Attitudes. American Journal of Political Science, 58(2), 433-448. https://doi.org/10.1111/ajps.12060

Wasow, O. (2020). Agenda Seeding: How 1960s Black Protests Moved Elites, Public Opinion and Voting. American Political Science Review, 114(3), 638-659. https://doi.org/10.1017/S000305542000009X

Weakliem, D. L. (2002). The Effects of Education on Political Opinions: An International Study. International Journal of Public Opinion Research, 14(2), 141-157. https://doi.org/10.1093/ijpor/14.2.141

Wels, H., Van Der Waal, K., Spiegel, A., & Kamsteeg, F. (2011). Victor Turner and liminality: An introduction. Anthropology Southern Africa, 34(1-2), 1-4. https://doi.org/10.1080/23323256.2011.11500002

Wolfinger, R. E., & Rosenstone, S. J. (1980). Who votes? Yale University Press.

Wright, E. O. (Ed.). (2005). Approaches to Class Analysis (1.a ed.). Cambridge University Press. https://doi.org/10.1017/CBO9780511488900

Xu, D., & Guo, J. (2023). In sight, in mind: Spatial proximity to protest sites and changes in peoples’ political attitudes. The British Journal of Sociology, 74(1), 83-104. https://doi.org/10.1111/1468-4446.12988

Zaller, J. R. (1992). The Nature and Origins of Mass Opinion (1.a ed.). Cambridge University Press. https://doi.org/10.1017/CBO9780511818691

Zhu, A. Y. F., & Chou, K. L. (2025). The Social Psychology of Procedural Justice: Findings in Hong Kong. Political Behavior, 47(1), 1-17. https://doi.org/10.1007/s11109-024-09938-6
